import type { SpecificationMetadata } from "../shared/visualizationModes";

const allFilters="Processo, órgão de destino e situação da validação contra o SIES.";
const story="US Controle PSS — Controle de Vagas";
const spec=(id:string,title:string,description:string,businessRule:string,source:string,dataType:string,component:string,route?:string,behavior?:string,filters=allFilters):SpecificationMetadata=>({id,title,description,businessRule,source,dataType,component,filters,status:"CONFIRMADO",route,behavior,userStory:story});

export const vagasPssScreenSpecification=spec("PSS-VAGA","Controle de Vagas do PSS","Controlar as vagas dos certames por secretaria de destino — quantos temporários ocupam vagas, quanto saldo resta e onde estão lotados — e evidenciar as divergências de cadastro entre o SIGEP e o SIES.","O controle de vagas é atribuição do SIGEP (RN05); a ocupação considera apenas ingressos efetivados e cada vaga permanece rastreável ao processo de origem (RN08). Divergência é diagnóstico técnico e não altera a situação legal do processo.","VagaProcessoPss, IngressoServidorPss, ProcessoPss e catálogo de cargos do SIES.","ResumoSecretariaPss[] + VagaProcessoPss[]","Página React com painel por secretaria, indicadores, filtros e tabela","/prototipos/sigep/controle-pss/vagas","Recalcula a conciliação sempre que os dados do store forem alterados.");

export const vagasPssKpiSpecifications:Record<string,SpecificationMetadata>={
 "Vagas cadastradas":spec("PSS-VAGA-KPI-001","Vagas cadastradas","Quantidade de registros de vaga/cargo recebidos nos processos filtrados.","Cada registro agrupa um cargo do certame, com vagas imediatas e cadastro de reserva.","VagaProcessoPss.","integer","KPI",undefined,"Respeita os filtros da tela."),
 "Validadas contra o SIES":spec("PSS-VAGA-KPI-002","Validadas contra o SIES","Vagas com correspondência confirmada no catálogo de cargos do SIES e sem divergência apurada.","Validação exige cargo correspondente e CBO compatível; a marcação manual sem correspondência não torna a vaga consistente.","VagaProcessoPss.validadaContraSies e conciliação.","integer + percentual","KPI",undefined,"O percentual usa o total de vagas filtradas."),
 "Com divergência":spec("PSS-VAGA-KPI-003","Com divergência SIGEP × SIES","Vagas com ao menos uma divergência apurada na conciliação.","Cargo sem correspondência, CBO divergente e quantitativo divergente são contados como divergências distintas.","Rotina calcularDivergenciasSies.","integer","KPI",undefined,"Clicar aplica o filtro de divergência."),
 "Vagas disponíveis":spec("PSS-VAGA-KPI-004","Vagas disponíveis","Saldo de vagas dos certames ainda não ocupado por servidor temporário.","RN05 — total ofertado ao órgão menos os ingressos efetivados; não pode ser negativo.","VagaProcessoPss e IngressoServidorPss consolidados por secretaria.","integer","KPI",undefined,"Respeita os filtros da tela."),
};

export const vagasPssFilterSpecifications:Record<string,SpecificationMetadata>={
 "Processo":spec("PSS-VAGA-FLT-001","Processo","Restringir as vagas a um processo seletivo.","O filtro é preenchido automaticamente quando a tela é aberta a partir do stepper ou do Painel Geral.","ProcessoPss.","string | vazio","select simples",undefined,"Vazio consolida todos os processos."),
 "Órgão de destino":spec("PSS-VAGA-FLT-002","Órgão de destino","Restringir as vagas ao órgão que receberá os aprovados.","O órgão de destino pode diferir do órgão solicitante em certames centralizados.","VagaProcessoPss.orgaoDestino.","string | vazio","select simples",undefined,"Vazio representa todos os órgãos."),
 "Validação SIES":spec("PSS-VAGA-FLT-003","Situação da validação","Separar vagas validadas, pendentes de validação e divergentes.","A situação é derivada da conciliação e do indicador de validação da vaga.","VagaProcessoPss e conciliação.","'' | VALIDADA | PENDENTE | DIVERGENTE","select simples",undefined,"Vazio representa todas as situações."),
};

export const vagasPssBlockSpecifications={
 secretarias:spec("PSS-VAGA-BLC-001","Painel de vagas por secretaria","Consolidar, por órgão de destino, quantos temporários ocupam vagas do certame, quantas vagas permanecem disponíveis e quais são as lotações de destino.","RN05/RN08 — ocupação considera apenas ingressos efetivados; vagas imediatas e cadastro de reserva compõem o total ofertado ao órgão e a vaga permanece rastreável ao processo de origem.","VagaProcessoPss, IngressoServidorPss e ProcessoPss.","ResumoSecretariaPss[]","cartões por órgão",undefined,"É o bloco principal da tela e respeita os filtros."),
 alerta:spec("PSS-VAGA-BLC-002","Alerta de divergência de cadastro","Destacar que existem vagas sem correspondência confiável entre SIGEP e SIES.","O alerta é informativo e não bloqueia o cadastro; o bloqueio ocorre na etapa do fluxo correspondente.","Rotina calcularDivergenciasSies.","DivergenciaSiesPss[]","faixa de alerta",undefined,"Exibido apenas quando houver divergências nos registros filtrados."),
 filtros:spec("PSS-VAGA-BLC-003","Filtros da consulta","Restringir as vagas exibidas na tela.","Os filtros são cumulativos e não alteram os dados recebidos do SIES.","Estado local da tela.","FiltrosVagaPss","formulário de filtros",undefined,"Limpar restaura todos os critérios."),
 tabela:spec("PSS-VAGA-TBL-001","Vagas individuais do certame","Listar os cargos do certame com quantitativos e situação da validação contra o SIES.","Quantitativos de vagas imediatas e cadastro de reserva são independentes e não devem ser somados como uma única grandeza.","VagaProcessoPss.","VagaProcessoPss[]","tabela",undefined,"A linha abre o detalhe da vaga."),
 detalhe:spec("PSS-VAGA-BLC-004","Detalhe da vaga do processo","Apresentar exigências, remuneração, lotação prevista e resultado da conciliação com o SIES.","O detalhe evidencia o cargo correspondente no SIES quando existir, e a descrição da divergência quando não existir.","VagaProcessoPss e CargoSiesReferencia.","VagaProcessoPss","modal de detalhe",undefined,"Abre a partir da tabela."),
 divergencias:spec("PSS-VAGA-BLC-005","Divergências apuradas","Listar as divergências de conciliação encontradas nas vagas filtradas.","A correção deve ocorrer na fonte responsável: catálogo de cargos do SIES ou cadastro do processo recebido.","Rotina calcularDivergenciasSies.","DivergenciaSiesPss[]","lista de diagnósticos",undefined,"Cada item indica gravidade e cargo afetado."),
} satisfies Record<string,SpecificationMetadata>;

export const vagasPssActionSpecifications:Record<string,SpecificationMetadata>={
 "Revalidar contra o SIES":spec("PSS-VAGA-ACT-001","Revalidar contra o SIES","Reexecutar a conciliação da vaga com o catálogo de cargos do SIES.","A revalidação apenas registra o resultado da conferência; não cria nem altera cargos no SIES.","Catálogo de cargos do SIES.","command","botão de ação",undefined,"Atualiza o indicador de validação da vaga no protótipo."),
 "Abrir processo":spec("PSS-VAGA-ACT-002","Abrir o processo da vaga","Navegar para o acompanhamento etapa a etapa do processo de origem da vaga.","RN08 — a vaga sempre mantém o vínculo com o processo de origem.","Rota do módulo.","route","botão de ação","/prototipos/sigep/controle-pss/processos/:id","Abre Processos Seletivos com o processo selecionado."),
 "Limpar":spec("PSS-VAGA-ACT-003","Limpar filtros","Restaurar os critérios de consulta.","Não altera os dados recebidos.","Estado local da tela.","command","botão",undefined,"Executa uma atualização única do estado de filtros."),
};

export const vagasPssBusinessItems=[...Object.values(vagasPssFilterSpecifications),...Object.values(vagasPssBlockSpecifications),...Object.values(vagasPssKpiSpecifications),...Object.values(vagasPssActionSpecifications)];
