import type { SpecificationMetadata } from "../shared/visualizationModes";

const allFilters="Aba selecionada, criticidade da integração e processo de origem.";
const story="US Controle PSS — Integração SIES";
const spec=(id:string,title:string,description:string,businessRule:string,source:string,dataType:string,component:string,route?:string,behavior?:string,filters=allFilters):SpecificationMetadata=>({id,title,description,businessRule,source,dataType,component,filters,status:"CONFIRMADO",route,behavior,userStory:story});

export const integracaoScreenSpecification=spec("PSS-INT","Integração SIES","Reunir em uma tela a situação das integrações do fluxo do certame — SIES, IOMAT, Diário Oficial e TCE-MT — o de-para de candidatos recebido do SIES e a única ação de escrita do módulo: o ingresso do servidor.","O SIGEP consome dados do SIES; convocação e publicação são de propriedade do SIES e do veículo oficial e aqui aparecem apenas como status de leitura. Integração parcial não equivale a integração implantada.","IntegracaoExterna, CampoDeParaPss, RegistroDeParaPss, CandidatoPss e IngressoServidorPss.","IntegracaoExterna[] + RegistroDeParaPss[]","Página React com duas abas","/prototipos/sigep/controle-pss/integracao-sies","A tela não estabelece conexão com sistemas externos; a carga de dados é simulada.");

export const integracaoTabSpecifications:Record<string,SpecificationMetadata>={
 "Integrações":spec("PSS-INT-TAB-001","Aba Integrações","Listar as integrações externas com situação atual e lacunas.","Cada integração é avaliada isoladamente; a criticidade indica o impacto no andamento do certame.","IntegracaoExterna.","IntegracaoExterna[]","aba",undefined,"Exibe a contagem de integrações."),
 "De-Para, Candidatos e Ingresso":spec("PSS-INT-TAB-002","Aba De-Para, Candidatos e Ingresso","Apresentar o mapeamento de campos SIES ↔ SIGEP, os registros de candidatos carregados e a efetivação do ingresso do servidor.","O de-para é a única forma de vincular o candidato do certame ao servidor do SIGEP sem redigitação; enquanto a convocação não for dado estruturado no SIES, a carga permanece pendente (RN07).","CampoDeParaPss, RegistroDeParaPss, CandidatoPss e IngressoServidorPss.","RegistroDeParaPss[]","aba",undefined,"Exibe a contagem de registros de-para carregados."),
};

export const integracaoBlockSpecifications={
 aviso:spec("PSS-INT-BLC-001","Aviso de protótipo","Esclarecer que a tela é de acompanhamento e não executa integrações reais.","Nenhuma ação desta tela produz efeito em sistemas externos; o registro de verificação apenas documenta a conferência realizada.","Regra do protótipo.","estático","faixa informativa",undefined,"Conteúdo fixo, sem cálculo."),
 resumo:spec("PSS-INT-BLC-002","Resumo das integrações","Consolidar quantas integrações estão implantadas, parciais e não implantadas.","Integração parcial ainda exige trâmite manual em pelo menos uma etapa.","IntegracaoExterna.situacaoAtual.","Record<SituacaoIntegracaoPss, number>","cartões de resumo",undefined,"Respeita o filtro de criticidade."),
 cartao:spec("PSS-INT-BLC-003","Cartão da integração","Apresentar finalidade, situação atual, responsável e lacunas de uma integração.","O bloco 'o que falta' descreve o que impede considerar a integração implantada; não é um plano de projeto.","IntegracaoExterna.","IntegracaoExterna","cartão",undefined,"Cada item de lacuna é exibido como lista."),
 pendencias:spec("PSS-INT-BLC-004","Pontos para validação com a área de negócio","Registrar as definições ainda pendentes que afetam o comportamento do módulo.","Enquanto pendente, o protótipo aplica a premissa provisória descrita no item.","Lista de pendências do módulo.","string[]","nota colapsável",undefined,"Inicia recolhida; o conteúdo é estático."),
 mapeamento:spec("PSS-INT-BLC-005","Mapeamento de campos SIES ↔ SIGEP","Relacionar cada campo do SIES ao campo correspondente do SIGEP, conforme a seção 7 do RF-001.","O mapeamento é fixo e normativo: alterar a correspondência de campos exige revisão do requisito, não configuração de tela.","Tabela de-para do RF-001 §7.","CampoDeParaPss[]","tabela",undefined,"Conteúdo estático derivado do requisito."),
 registrosDePara:spec("PSS-INT-BLC-006","Registros de-para carregados","Listar os candidatos já convertidos em dados de servidor no SIGEP, com a situação da carga, o status de convocação e publicação recebidos e o processo de origem.","RN08 — todo registro mantém o número do processo de origem para rastreabilidade da vaga; registro em contingência manual é provisório e não substitui a carga estruturada. Status de convocação e de publicação são somente leitura: pertencem ao SIES e ao veículo oficial.","RegistroDeParaPss, ConvocacaoPss e PublicacaoPss.","RegistroDeParaPss[]","tabela",undefined,"Atualiza a cada execução da carga de dados."),
 ingresso:spec("PSS-INT-BLC-007","Ingresso do Servidor","Vincular o candidato convocado ou nomeado à vaga do processo e à lotação de destino no SIGEP, a partir do registro de-para carregado do SIES.","RN06 — o ingresso só é efetivado com convocação confirmada no SIES e validação documental concluída; sem esses requisitos, apenas o registro provisório de contingência é admitido.","CandidatoPss, RegistroDeParaPss, VagaProcessoPss e IngressoServidorPss.","IngressoServidorPss[]","tabela com ação",undefined,"Candidatos sem carga de-para aparecem com a carga pendente."),
 contingencia:spec("PSS-INT-BLC-008","Contingência manual do ingresso","Registrar provisoriamente o ingresso quando a convocação ainda não é dado estruturado no SIES ou a validação documental não foi concluída.","RN07: a contingência é controlada e exige justificativa; o registro nasce provisório, marcado como contingência manual, e não substitui a carga estruturada do de-para.","Ação do usuário sobre o registro de-para do candidato.","IngressoServidorPss","modal com justificativa",undefined,"Abre automaticamente quando a efetivação do ingresso é recusada pela regra."),
} satisfies Record<string,SpecificationMetadata>;

export const integracaoFilterSpecifications:Record<string,SpecificationMetadata>={
 "Criticidade":spec("PSS-INT-FLT-001","Criticidade","Restringir as integrações exibidas por impacto no andamento do certame.","Criticidade alta indica integração cuja ausência trava ou atrasa etapas obrigatórias.","IntegracaoExterna.criticidade.","'' | ALTA | MEDIA | BAIXA","select simples",undefined,"Vazio consolida todas as criticidades."),
 "Processo":spec("PSS-INT-FLT-002","Processo de origem","Restringir os registros de-para, os candidatos e os ingressos a um processo seletivo.","RN08 — o processo de origem é o vínculo de rastreabilidade entre o candidato do SIES e a vaga do SIGEP.","ProcessoPss.","string | vazio","select simples",undefined,"Vazio consolida todos os processos."),
};

export const integracaoActionSpecifications:Record<string,SpecificationMetadata>={
 "Registrar verificação":spec("PSS-INT-ACT-001","Registrar verificação","Atualizar a situação da integração após conferência com o responsável técnico.","O registro reflete a conferência realizada; não estabelece conexão com o sistema externo.","Ação do usuário.","command","botão de ação",undefined,"Alterna a situação da integração no protótipo."),
 "Executar carga de dados":spec("PSS-INT-ACT-002","Executar carga de dados (de-para)","Gerar os registros de-para dos candidatos convocados ou nomeados que ainda não possuem carga.","A carga só alcança candidatos convocados ou nomeados; convocação gerada manualmente produz registro em contingência manual, pendente de estruturação no SIES (RN07).","CandidatoPss, ProcessoPss, VagaProcessoPss e ConvocacaoPss.","command","botão de ação",undefined,"Simula a execução da integração no protótipo, sem conexão com o SIES."),
 "Efetivar ingresso":spec("PSS-INT-ACT-003","Efetivar ingresso do servidor","Registrar o ingresso do candidato na vaga e na lotação de destino do órgão.","RN06 — só efetiva com convocação confirmada no SIES e validação documental concluída; caso contrário o sistema exige o registro de contingência manual justificado (RN07).","RegistroDeParaPss e VagaProcessoPss.","command","botão de ação",undefined,"Cria ou atualiza o ingresso do candidato no protótipo, sem conexão com sistemas externos."),
};

export const integracaoBusinessItems=[...Object.values(integracaoTabSpecifications),...Object.values(integracaoFilterSpecifications),...Object.values(integracaoBlockSpecifications),...Object.values(integracaoActionSpecifications)];
