import type { SpecificationMetadata } from "../shared/visualizationModes";

const allFilters="Data de referência, órgão solicitante, fase do fluxo e situação do processo.";
const story="US Controle PSS — Painel Geral";
const spec=(id:string,title:string,description:string,businessRule:string,source:string,dataType:string,component:string,route?:string,behavior?:string,filters=allFilters):SpecificationMetadata=>({id,title,description,businessRule,source,dataType,component,filters,status:"CONFIRMADO",route,behavior,userStory:story});

export const painelPssScreenSpecification=spec("PSS-PAINEL","Painel Geral do Controle PSS","Consolidar em uma única visão a posição dos processos seletivos que o SIGEP controla — status geral, pendências manuais, divergências com o SIES e saldo de vagas.","O SIGEP não cadastra o processo seletivo: os processos exibidos existem por terem sido recebidos do SIES via de-para. O status geral de três estados (RN04) é o indicador primário; a situação detalhada aparece apenas no detalhe do processo.","Processos PSS, etapas do fluxo, vagas do processo e catálogo de cargos do SIES.","DashboardPssViewModel","Página React + seletores derivados do store","/prototipos/sigep/controle-pss/painel","Recalcula a visão sempre que filtros ou dados do store forem alterados.");

export const painelPssFilterSpecifications:Record<string,SpecificationMetadata>={
 "Data de referência":spec("PSS-PAINEL-FLT-002","Data de referência","Reconstruir a posição dos processos na data escolhida.","Considerar apenas processos abertos até a data informada; a data de abertura é a do protocolo no Sigadoc.","Filtro informado pelo usuário e ProcessoPss.dataAbertura.","string ISO date (YYYY-MM-DD)","input[type=date]",undefined,"Ao alterar, recalcula indicadores, alertas e a tabela de processos."),
 "Órgão solicitante":spec("PSS-PAINEL-FLT-003","Órgão solicitante","Restringir a visão aos processos abertos por um órgão.","O órgão solicitante é o que formalizou a necessidade, ainda que a execução seja centralizada na SEPLAG.","ProcessoPss.orgaoSolicitante.","string | vazio","select simples",undefined,"Vazio representa todos; as opções derivam dos processos existentes."),
 "Fase do fluxo":spec("PSS-PAINEL-FLT-004","Fase do fluxo","Separar processos conforme a fase em que a etapa atual se encontra.","Fase 1 é documental (Sigadoc), Fase 2 é a gestão do concurso (SIES) e Fase 3 é o controle de pessoas (SIGEP); a fase é derivada da etapa atual e não é informada manualmente.","EtapaFluxoPss e catálogo de definições de etapa.","'' | DOCUMENTAL | SIES | SIGEP","select simples",undefined,"Vazio consolida as três fases."),
 "Situação":spec("PSS-PAINEL-FLT-005","Situação do processo","Consultar processos por sua situação administrativa detalhada.","Em elaboração e em andamento são considerados ativos; homologado e encerrado compõem o status geral Fechado.","ProcessoPss.situacao.","'' | EM_ELABORACAO | EM_ANDAMENTO | SUSPENSO | HOMOLOGADO | ENCERRADO","select simples",undefined,"Vazio representa todas as situações."),
 "Somente divergências":spec("PSS-PAINEL-FLT-006","Somente divergências SIGEP × SIES","Exibir apenas processos com divergência apurada entre o cadastro do SIGEP e o do SIES.","A divergência é calculada por conciliação das vagas do processo com o catálogo de cargos do SIES; não é informada manualmente.","Rotina calcularDivergenciasSies sobre VagaProcessoPss e CargoSiesReferencia.","boolean","checkbox",undefined,"Marcado restringe toda a visão."),
 "Limpar":spec("PSS-PAINEL-FLT-007","Limpar filtros","Restaurar os filtros para os valores iniciais.","Restaurar a data padrão e remover órgão, fase, situação e marcações.","Constante filtrosIniciais.","command","botão",undefined,"Executa uma atualização única do estado de filtros."),
};

export const painelPssKpiSpecifications:Record<string,SpecificationMetadata>={
 "Processos abertos":spec("PSS-PAINEL-KPI-001","Processos abertos","Processos recebidos do SIES que ainda não iniciaram a execução do certame.","RN04 — status geral Aberto corresponde à situação Em elaboração; o SIGEP não cria o processo, apenas registra o recebimento.","statusGeralDoProcesso sobre ProcessoPss.situacao.","integer","KPI navegável","/prototipos/sigep/controle-pss/processos","Abre Processos Seletivos."),
 "Processos em andamento":spec("PSS-PAINEL-KPI-002","Processos em andamento","Processos com o certame em execução ou suspenso.","RN04 — status geral Em andamento reúne as situações Em andamento e Suspenso.","statusGeralDoProcesso sobre ProcessoPss.situacao.","integer","KPI navegável","/prototipos/sigep/controle-pss/processos","Abre Processos Seletivos."),
 "Processos fechados":spec("PSS-PAINEL-KPI-003","Processos fechados","Processos homologados ou encerrados.","RN04 — status geral Fechado reúne as situações Homologado e Encerrado; processo fechado não gera novos ingressos.","statusGeralDoProcesso sobre ProcessoPss.situacao.","integer","KPI navegável","/prototipos/sigep/controle-pss/processos","Abre Processos Seletivos."),
 "Com pendência manual":spec("PSS-PAINEL-KPI-004","Processos com pendência manual","Processos que possuem ao menos uma etapa não concluída de trâmite manual ou parcial.","Etapa automatizada não gera pendência; etapa fora do escopo sistêmico conta como manual.","EtapaProcessoPss.automacao e situacao.","integer","KPI navegável","/prototipos/sigep/controle-pss/processos","Abre Processos Seletivos."),
 "Com divergência SIGEP × SIES":spec("PSS-PAINEL-KPI-005","Processos com divergência SIGEP × SIES","Processos com ao menos uma divergência apurada entre os cadastros dos dois sistemas.","A conciliação compara cargo, CBO e quantitativo de vagas; a divergência não interrompe o processo automaticamente.","Rotina calcularDivergenciasSies.","integer","KPI navegável","/prototipos/sigep/controle-pss/vagas","Abre Controle de Vagas."),
 "Vagas disponíveis":spec("PSS-PAINEL-KPI-006","Vagas disponíveis","Saldo de vagas dos certames ainda não ocupado por servidor temporário.","RN05 — a ocupação considera apenas ingressos efetivados; vagas imediatas e cadastro de reserva compõem o total ofertado ao órgão.","VagaProcessoPss e IngressoServidorPss consolidados por secretaria.","integer","KPI navegável","/prototipos/sigep/controle-pss/vagas","Abre Controle de Vagas."),
};

export const painelPssAlertSpecifications:Record<string,SpecificationMetadata>={
 "Etapas bloqueadas":spec("PSS-PAINEL-ALT-001","Etapas bloqueadas","Identificar etapas que não podem avançar até a solução de uma pendência.","Contar etapas com situação BLOQUEADA nos processos filtrados; bloqueio não é atraso, é impedimento formal.","EtapaProcessoPss.situacao.","integer","alerta navegável","/prototipos/sigep/controle-pss/processos","Abre Processos Seletivos."),
 "Divergências SIGEP × SIES":spec("PSS-PAINEL-ALT-002","Divergências SIGEP × SIES","Evidenciar processos cujo cadastro de vagas não confere entre os dois sistemas.","Cargo sem correspondência, CBO divergente e quantitativo divergente são tratados como divergências distintas.","Rotina calcularDivergenciasSies.","integer","alerta navegável","/prototipos/sigep/controle-pss/vagas","Abre Controle de Vagas."),
 "Registros de-para em contingência":spec("PSS-PAINEL-ALT-003","Registros de-para em contingência manual","Indicar candidatos cuja carga de-para do SIES nasceu provisória.","RN07 — enquanto a convocação não for dado estruturado no SIES, o registro permanece em contingência e o ingresso não pode ser efetivado.","RegistroDeParaPss.contingenciaManual.","integer","alerta navegável","/prototipos/sigep/controle-pss/integracao-sies","Abre Integração SIES."),
 "Publicações pendentes":spec("PSS-PAINEL-ALT-004","Publicações pendentes","Indicar atos do certame ainda não publicados no veículo oficial.","O SIGEP apenas exibe o status recebido do SIES e do Diário Oficial; a publicação não é ação deste módulo.","PublicacaoPss.situacao.","integer","alerta navegável","/prototipos/sigep/controle-pss/integracao-sies","Abre Integração SIES."),
};

export const painelPssBlockSpecifications={
 filtros:spec("PSS-PAINEL-BLC-001","Filtros da consulta","Abrir ou recolher os critérios que restringem toda a posição do Painel Geral.","Todos os indicadores, alertas e a tabela devem usar a mesma instância de DashboardPssFiltros.","Estado local DashboardPssFiltros e listas derivadas do store.","DashboardPssFiltros","Accordion + formulário",undefined,"Inicia fechado; abrir não altera os resultados."),
 aviso:spec("PSS-PAINEL-BLC-002","Origem dos processos","Esclarecer que os processos exibidos vêm do SIES e que o SIGEP não os cadastra.","O SIGEP recebe os processos por integração (de-para) e controla status, vagas por secretaria e ingresso do servidor.","Regra do módulo (RF-001 RN01/RN02).","estático","faixa informativa",undefined,"Conteúdo fixo, sem cálculo."),
 alertas:spec("PSS-PAINEL-BLC-003","Alertas do Controle PSS","Destacar situações que travam ou atrasam o andamento dos certames.","Cada alerta abre a tela que permite tratar o problema; alertas não substituem a análise do processo.","Etapas bloqueadas, divergências, registros em contingência e publicações pendentes.","AlertaPss[]","lista de links",undefined,"Os valores respeitam os filtros gerais."),
 recentes:spec("PSS-PAINEL-BLC-004","Eventos recentes","Exibir os últimos eventos registrados na trilha de auditoria dos processos.","Ordenar pela data de efeito decrescente e limitar aos itens mais recentes.","EventoTemporalPss consolidado.","EventoTemporalPss[]","lista temporal",undefined,"Somente leitura."),
 tabela:spec("PSS-PAINEL-TBL-001","Processos em acompanhamento","Apresentar a posição resumida de cada processo controlado pelo SIGEP.","Exibir apenas processo, órgão, status geral, fase e vagas; o detalhamento por etapa fica na tela Processos Seletivos.","Processos PSS, etapas e divergências apuradas.","GrupoProcessoDashboardPss[]","tabela gerencial","/prototipos/sigep/controle-pss/processos/:id","O número do processo abre o detalhe em Processos Seletivos."),
} satisfies Record<string,SpecificationMetadata>;

export const painelPssBusinessItems=[...Object.values(painelPssFilterSpecifications),...Object.values(painelPssBlockSpecifications),...Object.values(painelPssAlertSpecifications),...Object.values(painelPssKpiSpecifications)];
