import type { SpecificationMetadata } from "../shared/visualizationModes";

const allFilters="Pesquisa por número, edital ou órgão e filtro por fase do fluxo.";
const story="US Controle PSS — Processos Seletivos";
const spec=(id:string,title:string,description:string,businessRule:string,source:string,dataType:string,component:string,route?:string,behavior?:string,filters=allFilters):SpecificationMetadata=>({id,title,description,businessRule,source,dataType,component,filters,status:"CONFIRMADO",route,behavior,userStory:story});

export const processosScreenSpecification=spec("PSS-PROC","Processos Seletivos","Consultar os processos seletivos e concursos controlados pelo SIGEP e acompanhar, processo a processo, todas as etapas do fluxo entre Sigadoc, SIES e SIGEP.","Somente leitura: o SIGEP não cadastra, versiona nem encerra processo seletivo — quem o faz é o SIES (fase documental no Sigadoc). Os processos existem aqui por terem sido recebidos pela integração de-para.","ProcessoPss e suas etapas geradas pelo catálogo de definições do fluxo.","ProcessoPss + EtapaProcessoPss[]","Página React com lista mestre e detalhe com stepper vertical","/prototipos/sigep/controle-pss/processos/:id","Selecionar um processo troca a rota e abre o detalhe com o stepper.");

export const processosBlockSpecifications={
 aviso:spec("PSS-PROC-BLC-001","Origem dos processos","Esclarecer que a lista é alimentada pelo SIES e não admite cadastro manual no SIGEP.","O SIGEP consome os processos por integração; não há formulário de criação nem versionamento de processo neste módulo.","Regra do módulo (RF-001 RN01/RN02).","estático","faixa informativa",undefined,"Conteúdo fixo, sem cálculo."),
 lista:spec("PSS-PROC-BLC-002","Lista de processos","Selecionar o processo cujo fluxo será acompanhado.","Somente um processo pode estar selecionado; a seleção define a rota e todo o conteúdo do detalhe. O status geral (RN04) é o badge primário da lista.","ProcessoPss filtrados por pesquisa e fase.","ProcessoPss[]","tabela selecionável","/prototipos/sigep/controle-pss/processos/:id","Sem identificador na rota, a tela exibe apenas a lista."),
 cabecalho:spec("PSS-PROC-BLC-003","Identificação do processo","Apresentar a identificação, a situação e o andamento do processo selecionado.","O percentual de andamento considera apenas etapas concluídas sobre o total de etapas da esteira do processo.","ProcessoPss e progressoProcesso.","ProcessoPss","cabeçalho + barra de progresso",undefined,"Atualiza ao trocar o processo selecionado."),
 stepper:spec("PSS-PROC-BLC-004","Stepper vertical das etapas","Materializar o fluxo do processo seletivo em etapas ordenadas, agrupadas pelas três fases.","A ordem das etapas é fixa e definida pelo catálogo do fluxo; etapas fora do escopo sistêmico permanecem visíveis, sinalizadas, para não esconder o trâmite real.","Catálogo definicoesEtapasPss e EtapaProcessoPss do processo.","EtapaProcessoPss[]","stepper vertical",undefined,"Cada etapa é expansível e exibe descrição, observação e pendências."),
 etapa:spec("PSS-PROC-BLC-005","Etapa do fluxo","Exibir situação, grau de automação, responsável, datas e pendências de uma etapa.","Situação e automação são dimensões independentes: uma etapa concluída pode ter sido executada manualmente. Etapa bloqueada exige a solução de uma pendência formal antes da retomada.","EtapaProcessoPss.","EtapaProcessoPss","cartão expansível",undefined,"Expandir não altera dados; a etapa em andamento inicia expandida."),
 legenda:spec("PSS-PROC-BLC-006","Legenda de situação e automação","Explicar o significado dos indicadores visuais usados no stepper.","A legenda reproduz a classificação do fluxo mapeado: automatizada, parcial e manual.","Catálogo de rótulos do módulo.","estático","legenda",undefined,"Conteúdo fixo, sem cálculo."),
 pendencias:spec("PSS-PROC-BLC-007","Pendências da etapa","Listar o que impede a etapa de ser considerada sistêmica ou concluída.","Pendência descreve trâmite fora do sistema ou impedimento formal; não é uma tarefa atribuída automaticamente.","EtapaProcessoPss.pendencias.","string[]","lista",undefined,"Exibida apenas quando a etapa possuir pendências."),
 historico:spec("PSS-PROC-BLC-008","Histórico do processo","Apresentar a trilha de eventos registrados para o processo selecionado.","Registros anteriores não são editados ou removidos; novos eventos são acrescidos ao final.","ProcessoPss.historico.","HistoricoProcessoPss[]","linha do tempo",undefined,"Ordenado do evento mais recente para o mais antigo."),
} satisfies Record<string,SpecificationMetadata>;

export const processosFilterSpecifications:Record<string,SpecificationMetadata>={
 "Pesquisar processo":spec("PSS-PROC-FLT-001","Pesquisar processo","Localizar um processo pelo número, edital ou órgão solicitante.","A pesquisa é textual e não diferencia maiúsculas, minúsculas ou acentuação.","ProcessoPss.numero, edital e orgaoSolicitante.","string","campo de busca",undefined,"Filtra apenas a lista; não altera o processo selecionado."),
 "Fase do fluxo":spec("PSS-PROC-FLT-002","Fase do fluxo","Restringir a lista aos processos cuja etapa atual pertence a uma fase.","A fase é derivada da etapa atual; não é informada manualmente.","EtapaFluxoPss e catálogo de definições.","'' | DOCUMENTAL | SIES | SIGEP","select simples",undefined,"Vazio consolida as três fases."),
};

export const processosActionSpecifications:Record<string,SpecificationMetadata>={
 "Selecionar processo":spec("PSS-PROC-ACT-001","Selecionar processo","Abrir o detalhe com o fluxo do processo escolhido.","A troca substitui integralmente o conteúdo do detalhe; não há comparação simultânea de processos.","Lista de processos filtrada.","route","link de tabela","/prototipos/sigep/controle-pss/processos/:id","Atualiza a rota com o identificador do processo."),
 "Abrir tela da etapa":spec("PSS-PROC-ACT-002","Abrir a tela responsável pela etapa","Navegar da etapa do stepper para a tela do módulo que trata aquela etapa.","Cada etapa do catálogo declara a tela responsável entre os quatro itens do menu; a navegação leva o contexto do processo selecionado.","DefinicaoEtapaPss.telaDestino.","route","botão de navegação","/prototipos/sigep/controle-pss","Abre a tela correspondente já filtrada pelo processo."),
 "Fechar detalhe":spec("PSS-PROC-ACT-003","Fechar o detalhe","Voltar à lista sem processo selecionado.","Fechar o detalhe não altera dados; apenas retorna à rota da lista.","Rota do módulo.","route","botão","/prototipos/sigep/controle-pss/processos","Retorna à listagem."),
};

export const processosBusinessItems=[...Object.values(processosFilterSpecifications),...Object.values(processosBlockSpecifications),...Object.values(processosActionSpecifications)];
