import type { VagaProcessoPss } from "./types";

export const vagasProcessoPssMock:VagaProcessoPss[]=[
 {id:"VPS-2026-001-01",processoId:"PSS-2026-001",cargo:"Professor de Educação Básica",cbo:"231205",perfilProfissional:"Docência — Anos finais",orgaoDestino:"SEDUC",lotacaoPrevista:"Unidades escolares da rede estadual — 87 municípios",vagasImediatas:1080,cadastroReserva:2160,escolaridade:"Licenciatura plena na área de atuação",remuneracao:5211.42,cargaHoraria:30,validadaContraSies:true,cargoSiesId:"SIES-CGO-0012",cargoSiesNome:"Professor de Educação Básica",cadastradaEm:"2026-04-20",usuarioCadastro:"Marcelo Tavares de Assunção"},
 {id:"VPS-2026-001-02",processoId:"PSS-2026-001",cargo:"Técnico Administrativo Educacional",cbo:"411005",perfilProfissional:"Apoio administrativo escolar",orgaoDestino:"SEDUC",lotacaoPrevista:"Secretarias das unidades escolares",vagasImediatas:160,cadastroReserva:320,escolaridade:"Ensino médio completo",remuneracao:2418.75,cargaHoraria:40,validadaContraSies:true,cargoSiesId:"SIES-CGO-0018",cargoSiesNome:"Técnico Administrativo Educacional",cadastradaEm:"2026-04-20",usuarioCadastro:"Marcelo Tavares de Assunção"},
 {id:"VPS-2026-002-01",processoId:"PSS-2026-002",cargo:"Profissional Técnico de Nível Superior em Serviços de Saúde do SUS",cbo:"223505",perfilProfissional:"Enfermagem",orgaoDestino:"SES",lotacaoPrevista:"Hospitais regionais de Rondonópolis, Sinop e Cáceres",vagasImediatas:96,cadastroReserva:192,escolaridade:"Superior em Enfermagem com registro no COREN",remuneracao:7842.10,cargaHoraria:30,validadaContraSies:true,cargoSiesId:"SIES-CGO-0031",cargoSiesNome:"Profissional Técnico de Nível Superior em Serviços de Saúde do SUS",cadastradaEm:"2026-04-02",usuarioCadastro:"Rosângela Batista de Souza"},
 {id:"VPS-2026-002-02",processoId:"PSS-2026-002",cargo:"Profissional Técnico de Nível Médio em Serviços de Saúde do SUS",cbo:"322205",perfilProfissional:"Técnico em enfermagem",orgaoDestino:"SES",lotacaoPrevista:"Hospitais regionais e policlínicas",vagasImediatas:90,cadastroReserva:180,escolaridade:"Ensino médio com curso técnico em enfermagem",remuneracao:3204.88,cargaHoraria:30,validadaContraSies:true,cargoSiesId:"SIES-CGO-0032",cargoSiesNome:"Profissional Técnico de Nível Médio em Serviços de Saúde do SUS",cadastradaEm:"2026-04-02",usuarioCadastro:"Rosângela Batista de Souza"},
 {id:"VPS-2026-003-01",processoId:"PSS-2026-003",cargo:"Investigador de Polícia",cbo:"516210",perfilProfissional:"Investigação criminal",orgaoDestino:"PJC",lotacaoPrevista:"Delegacias regionais do interior",vagasImediatas:280,cadastroReserva:560,escolaridade:"Superior completo em qualquer área",remuneracao:8930.55,cargaHoraria:40,validadaContraSies:false,cadastradaEm:"2026-06-24",usuarioCadastro:"Delegado Fernando Kruger Lima",divergencia:"Vaga ainda não submetida ao SIES: o certame não foi cadastrado."},
 {id:"VPS-2026-003-02",processoId:"PSS-2026-003",cargo:"Escrivão de Polícia",cbo:"351305",perfilProfissional:"Cartório policial",orgaoDestino:"PJC",lotacaoPrevista:"Delegacias regionais do interior",vagasImediatas:132,cadastroReserva:264,escolaridade:"Superior completo em qualquer área",remuneracao:8930.55,cargaHoraria:40,validadaContraSies:false,cadastradaEm:"2026-06-24",usuarioCadastro:"Delegado Fernando Kruger Lima",divergencia:"Vaga ainda não submetida ao SIES: o certame não foi cadastrado."},
 {id:"VPS-2026-004-01",processoId:"PSS-2026-004",cargo:"Assistente do Sistema Penitenciário",cbo:"411005",perfilProfissional:"Apoio administrativo prisional",orgaoDestino:"SEJUS",lotacaoPrevista:"Unidades prisionais da região metropolitana",vagasImediatas:120,cadastroReserva:240,escolaridade:"Ensino médio completo",remuneracao:3986.20,cargaHoraria:40,validadaContraSies:true,cargoSiesId:"SIES-CGO-0055",cargoSiesNome:"Assistente do Sistema Penitenciário",cadastradaEm:"2026-06-29",usuarioCadastro:"Cláudia Reis Nakamura",divergencia:"Quantitativo divergente: 120 vagas imediatas no SIGEP e 90 registradas no SIES."},
 {id:"VPS-2026-004-02",processoId:"PSS-2026-004",cargo:"Auxiliar do Sistema Penitenciário",cbo:"514320",perfilProfissional:"Serviços gerais prisionais",orgaoDestino:"SEJUS",lotacaoPrevista:"Unidades prisionais da região metropolitana",vagasImediatas:90,cadastroReserva:180,escolaridade:"Ensino fundamental completo",remuneracao:2612.40,cargaHoraria:40,validadaContraSies:false,cadastradaEm:"2026-06-29",usuarioCadastro:"Cláudia Reis Nakamura",divergencia:"Cargo sem correspondência no catálogo do SIES; CBO 514320 não validado contra o eSocial."},
 {id:"VPS-2026-005-01",processoId:"PSS-2026-005",cargo:"Fiscal de Tributos Estaduais",cbo:"212405",perfilProfissional:"Tributação, Arrecadação e Fiscalização",orgaoDestino:"SEFAZ",lotacaoPrevista:"Superintendências de fiscalização — Cuiabá e regionais",vagasImediatas:96,cadastroReserva:192,escolaridade:"Superior completo em qualquer área",remuneracao:19640.32,cargaHoraria:40,validadaContraSies:true,cargoSiesId:"SIES-CGO-0071",cargoSiesNome:"Fiscal de Tributos Estaduais",cadastradaEm:"2026-01-15",usuarioCadastro:"Henrique Portela Vasconcelos",divergencia:"CBO divergente: 212405 no edital e 212410 no cargo cadastrado."},
 {id:"VPS-2026-006-01",processoId:"PSS-2026-006",cargo:"Analista do Desenvolvimento Econômico e Social",cbo:"251605",perfilProfissional:"Serviço social",orgaoDestino:"SETASC",lotacaoPrevista:"CRAS e CREAS do interior do Estado",vagasImediatas:64,cadastroReserva:128,escolaridade:"Superior em Serviço Social com registro no CRESS",remuneracao:6310.00,cargaHoraria:30,validadaContraSies:false,cadastradaEm:"2026-07-14",usuarioCadastro:"Patrícia Nunes de Almeida",divergencia:"Vaga cadastrada antes da publicação do edital; validação contra o SIES ainda não executada."},
 {id:"VPS-2025-014-01",processoId:"PSS-2025-014",cargo:"Analista de Meio Ambiente",cbo:"213155",perfilProfissional:"Licenciamento ambiental",orgaoDestino:"SEMA",lotacaoPrevista:"Superintendências de licenciamento e fiscalização",vagasImediatas:52,cadastroReserva:104,escolaridade:"Superior nas áreas ambientais",remuneracao:9120.75,cargaHoraria:30,validadaContraSies:true,cargoSiesId:"SIES-CGO-0090",cargoSiesNome:"Analista de Meio Ambiente",cadastradaEm:"2025-04-10",usuarioCadastro:"Vinícius Duarte Peçanha"},
 {id:"VPS-2025-014-02",processoId:"PSS-2025-014",cargo:"Técnico de Meio Ambiente",cbo:"311715",perfilProfissional:"Fiscalização ambiental",orgaoDestino:"SEMA",lotacaoPrevista:"Escritórios regionais",vagasImediatas:26,cadastroReserva:52,escolaridade:"Ensino médio com curso técnico ambiental",remuneracao:4380.90,cargaHoraria:40,validadaContraSies:true,cargoSiesId:"SIES-CGO-0091",cargoSiesNome:"Técnico de Meio Ambiente",cadastradaEm:"2025-04-10",usuarioCadastro:"Vinícius Duarte Peçanha"},
];
