export type SimbologiaDga = `DGA-${number}`;
export type LimiteDgaLinha = { simbologia: SimbologiaDga; cargos: number; funcoes: number };
export type SituacaoLimiteDga = "RASCUNHO" | "AGENDADA" | "VIGENTE" | "ENCERRADA";
export interface VigenciaLimiteDga { id: string; inicio: string; fim?: string; documentoLegal: string; situacao: SituacaoLimiteDga; limites: LimiteDgaLinha[]; }
export interface LimiteDgaOrgao { id: string; codigoOrgao: string; orgao: string; vigencias: VigenciaLimiteDga[]; }
export interface LimiteDgaSnapshot { vigenciaId: string; documentoLegal: string; inicio: string; fim?: string; limites: LimiteDgaLinha[]; }
const CHAVE = "sigep:estrutura-organizacional:limites-dga:v1";
export const simbologiasDga: SimbologiaDga[] = Array.from({ length: 10 }, (_, index) => `DGA-${index + 1}` as SimbologiaDga);
const limitesReferencia = (): LimiteDgaLinha[] => [[0, 0], [0, 3], [2, 1], [0, 8], [8, 19], [17, 63], [0, 0], [26, 9], [0, 4], [0, 2]].map(([cargos, funcoes], index) => ({ simbologia: simbologiasDga[index], cargos, funcoes }));
const orgaosIniciais = [["SEPLAG", "Secretaria de Estado de Planejamento e Gestão"], ["POLITEC", "Perícia Oficial e Identificação Técnica"], ["SESP", "Secretaria de Estado de Segurança Pública"], ["SES", "Secretaria de Estado de Saúde"], ["SEDUC", "Secretaria de Estado de Educação"], ["SEMA", "Secretaria de Estado de Meio Ambiente"]] as const;
function estadoInicial(): LimiteDgaOrgao[] { return orgaosIniciais.map(([codigoOrgao, orgao]) => ({ id: `limite-dga-${codigoOrgao.toLowerCase()}`, codigoOrgao, orgao, vigencias: [{ id: `vigencia-dga-${codigoOrgao.toLowerCase()}-2026`, inicio: "01/01/2026", documentoLegal: "Decreto nº 872, de 07/05/2024", situacao: "VIGENTE", limites: limitesReferencia() }] })); }
export function listarLimitesDga(): LimiteDgaOrgao[] { try { const persistido = window.localStorage.getItem(CHAVE); if (persistido) return JSON.parse(persistido) as LimiteDgaOrgao[]; } catch { /* referência inicial */ } const inicial = estadoInicial(); try { window.localStorage.setItem(CHAVE, JSON.stringify(inicial)); } catch { /* sem persistência */ } return inicial; }
export function salvarLimitesDga(registros: LimiteDgaOrgao[]) { window.localStorage.setItem(CHAVE, JSON.stringify(registros)); return registros; }
function numeroData(valor?: string) { if (!valor) return 0; const partes = valor.includes("/") ? valor.split("/") : valor.split("-").reverse(); const [dia, mes, ano] = partes.map(Number); return ano * 10000 + mes * 100 + dia; }
export function obterVigenciaLimiteDga(orgao: string, competencia: string): VigenciaLimiteDga | null { const chave = orgao.trim().toLocaleLowerCase("pt-BR"); const data = numeroData(competencia); if (!chave || !data) return null; const registro = listarLimitesDga().find((item) => item.codigoOrgao.toLocaleLowerCase("pt-BR") === chave || item.orgao.toLocaleLowerCase("pt-BR") === chave); return registro?.vigencias.filter((v) => v.situacao === "VIGENTE" && numeroData(v.inicio) <= data && (!v.fim || numeroData(v.fim) >= data)).sort((a, b) => numeroData(b.inicio) - numeroData(a.inicio))[0] ?? null; }
export function criarSnapshotLimiteDga(vigencia: VigenciaLimiteDga): LimiteDgaSnapshot { return { vigenciaId: vigencia.id, documentoLegal: vigencia.documentoLegal, inicio: vigencia.inicio, fim: vigencia.fim, limites: structuredClone(vigencia.limites) }; }
