import { useState } from "react";
import { useForm } from "react-hook-form";
import { BotaoSalvarSeplag, BotaoSeplag, BotaoVoltarSeplag } from "@componentes/Botao";
import { CardSeplag } from "@componentes/Card";
import { CNPJFieldSeplag, DateFieldSeplag, DropdownFieldSeplag, EmailFieldSeplag, TextFieldSeplag } from "@componentes/Fields";
import "./orgaosEntidades.css";

type Tipo = "ente" | "orgao" | "entidade";
type Dados = Record<string, any> & { tipo: Tipo };
const opts = (v: string[]) => v.map((label) => ({ label, value: label }));
const noError = () => null;
const etapas = [["Identificação Institucional", "Classificação, dados cadastrais e eSocial."], ["Localização e Contato", "Endereço oficial e canais institucionais."], ["Responsável e Dados Bancários", "Representante vigente e conta bancária."], ["Integrações", "Códigos externos. Preenchimento opcional."]];
const tipos = { ente: ["Ente Federativo", "Estado de Mato Grosso", "Ente Federativo", "Sim", "O próprio Ente Federativo"], orgao: ["Órgão", "SEPLAG, CGE, PM/MT", "Administração Direta", "Não", "Estado de Mato Grosso - GOV"], entidade: ["Entidade", "DETRAN, MTI, EMPAER", "Administração Indireta", "Sim", "Órgão de vinculação / supervisão"] };

export function OrgaosEntidadesCadastro() {
  const [etapa, setEtapa] = useState(0); const [feedback, setFeedback] = useState("");
  const { control, watch, setValue } = useForm<Dados>({ defaultValues: { tipo: "orgao", enteSuperior: tipos.orgao[4], esferaGoverno: "Estadual", esferaPoder: "Executivo", forma: tipos.orgao[2], personalidade: tipos.orgao[3], estabelecimento: "Matriz", cnpj: "03.507.415/0011-16", razao: "SECRETARIA DE ESTADO DE PLANEJAMENTO E GESTÃO", fantasia: "SEPLAG", sigla: "SEPLAG", natureza: "Órgão Público do Poder Executivo Estadual", situacao: "Ativa", cep: "78049-938", uf: "MT", municipio: "Cuiabá", bairro: "Centro Político Administrativo", tipoLogradouro: "Avenida", logradouro: "Historiador Rubens de Mendonça", numero: "3415", telefone: "(65) 3613-0000", email: "atendimento@seplag.mt.gov.br", site: "www.seplag.mt.gov.br" } });
  const tipo = watch("tipo"); const dados = watch(); const common = { control, getFormErrorMessage: noError };
  const dd = (name: string, label: string, values: string[], required = false) => <DropdownFieldSeplag name={name} label={label} required={required} options={opts(values)} optionLabel="label" optionValue="value" {...common} />;
  const tx = (name: string, label: string, required = false, disabled = false) => <TextFieldSeplag name={name} label={label} required={required} disabled={disabled} {...common} />;
  const go = (n: number) => { setFeedback(""); setEtapa(Math.max(0, Math.min(3, n))); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const selectType = (v: Tipo) => { setValue("tipo", v); setValue("forma", tipos[v][2]); setValue("personalidade", tipos[v][3]); setValue("enteSuperior", tipos[v][4]); };
  return <div className="orgao-page prototype-page-content">
    <header className="orgao-page-header"><span>Estrutura Organizacional</span><h1>Cadastrar - Órgãos e Entidades</h1></header>
    <nav className="orgao-stepper">{etapas.map(([t, d], i) => <button type="button" key={t} className={`${i === etapa ? "active" : ""} ${i < etapa ? "done" : ""}`} onClick={() => go(i)}><span className="orgao-step-number">{i < etapa ? <i className="pi pi-check" /> : i + 1}</span><strong>{t}</strong><small>{d}</small></button>)}</nav>
    {etapa > 0 && <div className="orgao-summary"><strong>{dados.sigla} - {dados.razao}</strong><span>{tipos[tipo][0]} • CNPJ {dados.cnpj} • {dados.esferaGoverno}</span></div>}
    {etapa === 0 && <><CardSeplag title="Classificação institucional" cols="12" legenda={() => <p className="orgao-description">Informe como este registro se enquadra na estrutura institucional.</p>}><div className="orgao-type-grid">{(Object.keys(tipos) as Tipo[]).map(v => <button type="button" key={v} className={tipo === v ? "active" : ""} onClick={() => selectType(v)}><span /><strong>{tipos[v][0]}</strong><small>{tipos[v][1]}</small></button>)}</div><div className="orgao-grid cols-3">{dd("enteSuperior", "Ente superior", [tipos[tipo][4], "Outro ente superior"], true)}{dd("esferaGoverno", "Esfera de Governo", ["Federal", "Estadual", "Municipal"], true)}{dd("esferaPoder", "Esfera de Poder", ["Executivo", "Legislativo", "Judiciário"], true)}{tx("forma", "Forma de Administração", false, true)}{tx("personalidade", "Personalidade Jurídica Própria", false, true)}{dd("estabelecimento", "Tipo de Estabelecimento", ["Matriz", "Filial"], true)}</div></CardSeplag>
    <CardSeplag title="Identificação cadastral" cols="12"><div className="orgao-grid cols-4"><CNPJFieldSeplag name="cnpj" required validarCNPJ={false} {...common} />{tx("razao", "Nome/Razão Social", true)}{tx("fantasia", "Nome Fantasia")}{tx("sigla", "Sigla", true)}<DateFieldSeplag name="abertura" label="Data de Abertura" required {...common} /><DateFieldSeplag name="extincao" label="Data de Extinção" {...common} />{tx("inscricaoEstadual", "Inscrição Estadual")}{tx("inscricaoMunicipal", "Inscrição Municipal")}{dd("natureza", "Natureza Jurídica", ["Órgão Público do Poder Executivo Estadual"], true)}{dd("cnae", "Atividade Econômica Principal (CNAE)", ["8411-6/00 - Administração pública em geral"], true)}{dd("aplic", "Tipo do APLIC TCE/MT", ["Administração", "Gestão"])}</div></CardSeplag>
    <CardSeplag title="Informações para o eSocial" cols="12"><div className="orgao-grid cols-3">{dd("situacao", "Situação da Pessoa Jurídica", ["Ativa", "Baixada"], true)}{dd("tributaria", "Classificação Tributária", ["85 - Administração pública"], true)}{tx("siafi", "Número SIAFI")}{dd("registro", "Opção pelo Registro Eletrônico de Empregado", ["Sim", "Não"], true)}{dd("desoneracao", "Indicativo de Desoneração de Folha", ["Sim", "Não"], true)}<CNPJFieldSeplag name="cnpjEfr" label="CNPJ do Ente Federativo Responsável - EFR" validarCNPJ={false} {...common} /></div><div className="orgao-note"><i className="pi pi-info-circle" /> Dados agrupados nesta etapa para facilitar a conferência.</div></CardSeplag></>}
    {etapa === 1 && <><CardSeplag title="Endereço" cols="12"><div className="orgao-grid cols-4">{tx("cep", "CEP", true)}{dd("uf", "UF", ["MT"], true)}{tx("municipio", "Município", true)}{tx("bairro", "Bairro/Distrito", true)}{dd("tipoLogradouro", "Tipo de Logradouro", ["Avenida", "Rua"], true)}{tx("logradouro", "Logradouro", true)}{tx("numero", "Número", true)}{tx("complemento", "Complemento")}</div></CardSeplag><CardSeplag title="Contato" cols="12"><div className="orgao-grid cols-3">{tx("telefone", "Telefone", true)}<EmailFieldSeplag name="email" label="E-mail institucional" required {...common} />{tx("site", "Website")}</div></CardSeplag></>}
    {etapa === 2 && <><CardSeplag title="Responsável" cols="12"><div className="orgao-grid cols-3">{tx("cpfResponsavel", "CPF", true)}{tx("nomeResponsavel", "Nome", true)}{dd("cargoResponsavel", "Cargo/Função", ["Secretário de Estado", "Presidente", "Governador"], true)}<DateFieldSeplag name="inicioResponsavel" label="Data Início" required {...common} /><DateFieldSeplag name="fimResponsavel" label="Data Fim" {...common} /></div></CardSeplag><CardSeplag title="Dados Bancários" cols="12"><div className="orgao-grid cols-4">{dd("banco", "Banco", ["001 - Banco do Brasil", "104 - Caixa"], true)}{tx("agencia", "Agência", true)}{tx("conta", "Conta", true)}{tx("dv", "DV")}</div></CardSeplag></>}
    {etapa === 3 && <CardSeplag title="Integrações" cols="12"><p className="orgao-description">Os códigos são opcionais e podem ser informados posteriormente.</p><div className="orgao-grid cols-3">{tx("arh", "Código ARH")}{tx("seap", "Código SEAP")}{tx("codigoAplic", "UO Fiplan / Código APLIC TCE")}</div></CardSeplag>}
    {feedback && <div className="orgao-success"><i className="pi pi-check-circle" /> {feedback}</div>}<footer className="orgao-actions"><BotaoVoltarSeplag disabled={etapa === 0} onClick={() => go(etapa - 1)} /><div>{etapa === 3 && <BotaoSeplag label="Concluir sem integração" outlined onClick={() => setFeedback("Cadastro concluído sem integração.")} />}{etapa < 3 ? <BotaoSeplag label="Avançar" icon="pi pi-arrow-right" iconPos="right" onClick={() => go(etapa + 1)} /> : <BotaoSalvarSeplag label="Salvar cadastro" onClick={() => setFeedback("Cadastro salvo com sucesso.")} />}</div></footer>
  </div>;
}
