import { useMemo, useState } from "react";
import { CardSeplag } from "@componentes/Card";
import { ModalSeplag } from "@componentes/Modal";
import { BotaoSalvarSeplag, BotaoSeplag, BotaoVoltarSeplag } from "@componentes/Botao";
import "./organograma.css";

type Unidade = { id:number; codigo:string; nome:string; tipo:string; nivel:string; superior:number|null; vigencia:string };
const dados: Unidade[] = [
 [1,"DS001","Secretaria de Estado de Planejamento e Gestão","Secretaria de Estado","Direção Superior",null],
 [2,"DS002","Gabinete do Secretário de Estado","Gabinete","Direção Superior",1],
 [10,"DS010","Secretaria Adjunta de Planejamento e Governo Digital","Secretaria Adjunta","Direção Superior",2],
 [11,"DS011","Secretaria Adjunta de Gestão de Pessoas","Secretaria Adjunta","Direção Superior",2],
 [12,"DS012","Secretaria Adjunta de Aquisições Governamentais","Secretaria Adjunta","Direção Superior",2],
 [13,"DS013","Secretaria Adjunta de Administração Sistêmica","Secretaria Adjunta","Direção Superior",2],
 [20,"AE020","Unidade Setorial de Controle Interno - UNISECI","Unidade","Apoio Estratégico e Especializado",2],
 [21,"AE021","Ouvidoria Setorial","Ouvidoria","Apoio Estratégico e Especializado",2],
 [100,"EP100","Superintendência de Planejamento Estadual","Superintendência","Execução Programática",10],
 [104,"EP104","Superintendência de Governança Digital","Superintendência","Execução Programática",10],
 [108,"EP108","Superintendência de Modernização Organizacional","Superintendência","Execução Programática",10],
 [109,"EP109","Coordenadoria de Modelagem Organizacional","Coordenadoria","Execução Programática",108],
 [110,"EP110","Coordenadoria do Escritório Central de Processos de Negócios","Coordenadoria","Execução Programática",108],
 [200,"EP200","Superintendência de Provimento, Aplicação e Monitoramento","Superintendência","Execução Programática",11],
 [201,"EP201","Coordenadoria de Provimento","Coordenadoria","Execução Programática",200],
 [202,"EP202","Gerência de Recrutamento e Seleção","Gerência","Execução Programática",201],
].map(([id,codigo,nome,tipo,nivel,superior]) => ({ id, codigo, nome, tipo, nivel, superior, vigencia:"03/07/2026" } as Unidade));
const niveis=["Todos os níveis","Direção Superior","Apoio Estratégico e Especializado","Assessoramento Superior","Administração Sistêmica","Execução Programática"];

export function OrganogramaContent(){
 const [unidades,setUnidades]=useState(dados),[visao,setVisao]=useState<"org"|"lista">("org"),[busca,setBusca]=useState(""),[nivel,setNivel]=useState(niveis[0]);
 const [selecionada,setSelecionada]=useState<Unidade|null>(dados.find(x=>x.id===108)!),[modal,setModal]=useState<{unidade?:Unidade;superior:number}|null>(null),[nome,setNome]=useState("Unidade de Gestão de Risco"),[feedback,setFeedback]=useState(""),[expandido,setExpandido]=useState(false);
 const corresponde=(u:Unidade)=>{const q=busca.trim().toLocaleLowerCase("pt-BR");return(nivel===niveis[0]||u.nivel===nivel)&&(!q||`${u.codigo} ${u.nome} ${u.nivel}`.toLocaleLowerCase("pt-BR").includes(q))};
 const superior=(u:Unidade)=>unidades.find(x=>x.id===u.superior)?.nome??"Sem unidade superior";
 const lista=useMemo(()=>unidades.filter(corresponde),[unidades,busca,nivel]);
 const profundidade=(u:Unidade)=>{let d=0,p=u.superior;while(p){d++;p=unidades.find(x=>x.id===p)?.superior??null}return d};
 const salvarVinculo=()=>{if(!modal)return;if(modal.unidade){setUnidades(a=>a.map(x=>x.id===modal.unidade?.id?{...x,nome}:x));setFeedback("Nova vigência criada para o vínculo.")}else{const id=Math.max(...unidades.map(x=>x.id))+1;setUnidades(a=>[...a,{id,codigo:`NOV${id}`,nome,tipo:nome.split(" ")[0],nivel:"Execução Programática",superior:modal.superior,vigencia:"03/07/2026"}]);setFeedback("Unidade vinculada com sucesso.")}setModal(null)};
 const abrirEdicao=(u:Unidade)=>{setNome(u.nome);setModal({unidade:u,superior:u.superior??1})};
 const No=({u,raiz=false}:{u:Unidade;raiz?:boolean})=>{const filhos=unidades.filter(x=>x.superior===u.id&&corresponde(x));return <div className="org-chart-wrap"><button type="button" className={`org-chart-node ${raiz?"root":""} ${selecionada?.id===u.id?"selected":""}`} onClick={()=>setSelecionada(u)}><span>{u.codigo}</span><strong>{u.nome}</strong><small>{u.tipo}</small></button>{filhos.length>0&&<><div className="org-chart-line"/><div className="org-chart-children">{filhos.map(f=><div className="org-chart-branch" key={f.id}><No u={f}/></div>)}</div></>}</div>};
 const raiz=unidades.find(x=>x.superior===null)!;
 return <div className="organograma-page"><CardSeplag title="Cadastrar - Organograma" cols="12">
  <section className="organograma-section"><header><h2>Identificação da estrutura</h2><p>Exemplo preenchido com a Estrutura Organizacional da SEPLAG.</p></header><div className="organograma-form two"><label><span>Órgão/Entidade *</span><select><option>SEPLAG - Secretaria de Estado de Planejamento e Gestão</option></select></label><label><span>Nome do organograma *</span><input defaultValue="Estrutura Organizacional SEPLAG - 2026"/></label></div><div className="organograma-form three"><label><span>Início da vigência *</span><input type="date" defaultValue="2026-07-03"/></label><label><span>Fim da vigência</span><input type="date"/></label><label><span>Documento legal *</span><select><option>Decreto nº 2.185, de 03/07/2026</option></select></label></div></section>
  <section className={`organograma-section structure ${expandido?"expanded":""}`}><header className="organograma-toolbar"><div><h2>Estrutura da SEPLAG</h2><p>Cadastro baseado na estrutura definida no Decreto nº 2.185/2026.</p></div><div className="organograma-actions"><BotaoSeplag label="Organograma" icon="pi pi-sitemap" outlined={visao!=="org"} onClick={()=>setVisao("org")}/><BotaoSeplag label="Árvore / Lista" icon="pi pi-list" outlined={visao!=="lista"} onClick={()=>setVisao("lista")}/><BotaoSeplag label={expandido?"Fechar tela cheia":"Expandir"} icon={expandido?"pi pi-times":"pi pi-window-maximize"} outlined onClick={()=>setExpandido(!expandido)}/></div></header>
  <div className="organograma-form filters"><label><span>Pesquisar unidade</span><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Digite nome, código ou nível..."/></label><label><span>Filtrar por nível</span><select value={nivel} onChange={e=>setNivel(e.target.value)}>{niveis.map(x=><option key={x}>{x}</option>)}</select></label></div>
  {visao==="org"?<div className="organograma-canvas"><div className="org-chart"><No u={raiz} raiz/></div></div>:<div className="organograma-list">{lista.map(u=><article key={u.id} style={{paddingLeft:12+profundidade(u)*22}}><div><strong>{u.codigo} - {u.nome}</strong><small>{u.nivel} • Superior: {superior(u)}</small></div><span>{u.tipo}</span><BotaoSeplag label="Detalhes" outlined onClick={()=>setSelecionada(u)}/><BotaoSeplag label="Vincular abaixo" icon="pi pi-plus" outlined onClick={()=>setModal({superior:u.id})}/></article>)}</div>}
  {selecionada&&<aside className="organograma-details"><header><div><h3>{selecionada.nome}</h3><p>Detalhes da unidade selecionada.</p></div><div className="organograma-actions"><BotaoSeplag label="Vincular abaixo" icon="pi pi-plus" outlined onClick={()=>setModal({superior:selecionada.id})}/><BotaoSeplag label="Alterar vínculo" icon="pi pi-pencil" outlined onClick={()=>abrirEdicao(selecionada)}/><BotaoSeplag label="Fechar" outlined onClick={()=>setSelecionada(null)}/></div></header><dl><div><dt>Código</dt><dd>{selecionada.codigo}</dd></div><div><dt>Tipo</dt><dd>{selecionada.tipo}</dd></div><div><dt>Nível</dt><dd>{selecionada.nivel}</dd></div><div><dt>Unidade superior</dt><dd>{superior(selecionada)}</dd></div><div><dt>Vigência</dt><dd>{selecionada.vigencia}</dd></div></dl></aside>}</section>
  {feedback&&<div className="organograma-feedback" role="status"><i className="pi pi-check-circle"/> {feedback}</div>}<footer className="organograma-footer"><p>As unidades foram organizadas conforme os vínculos hierárquicos previstos no Decreto nº 2.185/2026.</p><div><BotaoVoltarSeplag onClick={()=>history.back()}/><BotaoSalvarSeplag onClick={()=>setFeedback("Organograma da SEPLAG salvo com sucesso.")}/></div></footer>
 </CardSeplag><ModalSeplag visible={Boolean(modal)} titulo={modal?.unidade?"Alterar vínculo":"Vincular unidade"} fechar={()=>setModal(null)} funcAcao={salvarVinculo} labelAcao={modal?.unidade?"Salvar nova vigência":"Vincular"} tamanho="800px"><div className="col-12 organograma-note"><i className="pi pi-info-circle"/> A unidade deve existir previamente no cadastro de unidades administrativas.</div><div className="col-12 md:col-6 organograma-modal-field"><label>Unidade *</label><select value={nome} onChange={e=>setNome(e.target.value)}><option>Unidade de Gestão de Risco</option><option>Gerência de Segurança da Informação</option><option>Gerência de Consignações</option><option>Coordenadoria de Serviços</option>{modal?.unidade&&<option>{modal.unidade.nome}</option>}</select></div><div className="col-12 md:col-6 organograma-modal-field"><label>Nível organizacional *</label><select defaultValue={modal?.unidade?.nivel??"Execução Programática"}>{niveis.slice(1).map(x=><option key={x}>{x}</option>)}</select></div><div className="col-12 md:col-6 organograma-modal-field"><label>Unidade superior *</label><select defaultValue={modal?.superior}>{unidades.filter(x=>x.id!==modal?.unidade?.id).map(x=><option value={x.id} key={x.id}>{x.nome}</option>)}</select></div><div className="col-12 md:col-6 organograma-modal-field"><label>Início da vigência *</label><input type="date" defaultValue="2026-07-03"/></div></ModalSeplag></div>
}
