import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { SplitButton } from "primereact/splitbutton";
import { BotaoLimparFiltroSeplag, BotaoSalvarSeplag, BotaoSeplag, BotaoVoltarSeplag } from "@componentes/Botao";
import { CardSeplag } from "@componentes/Card";
import { DateFieldSeplag, DropdownFieldSeplag, TextFieldSeplag } from "@componentes/Fields";
import { menuGestaoPessoas, PrototypeSystemPage } from "../PrototiposPage";
import "./unidades.css";

type Unidade={id:number;nome:string;sigla:string;codigo:string;tipo:string;nivel:string;superior:string;situacao:"Ativa"|"Inativa"};
type Filtros={busca:string;nivelFiltro:string;tipoFiltro:string;situacaoFiltro:string};
type Cadastro={superior:string;nivel:string;nome:string;sigla:string;codigo:string;inicio:string;fim:string;documento:string};
const noError=()=>null;
const opts=(values:string[])=>values.map(value=>({label:value,value}));
const niveis=["Direção Superior","Apoio Estratégico e Especializado","Assessoramento Superior","Administração Sistêmica","Execução Programática"];
const tiposPorNivel:Record<string,string[]>={
  "Direção Superior":["Gabinete","Secretaria Adjunta","Diretoria"],
  "Apoio Estratégico e Especializado":["Núcleo","Ouvidoria","Unidade"],
  "Assessoramento Superior":["Gabinete","Unidade de Assessoria"],
  "Administração Sistêmica":["Superintendência","Coordenadoria","Gerência","Núcleo","Unidade"],
  "Execução Programática":["Superintendência","Coordenadoria","Gerência","Núcleo","Unidade"]
};
const iniciais:Unidade[]=[
  {id:1,nome:"Gabinete do Secretário de Estado de Planejamento e Gestão",sigla:"GAB",codigo:"U0001",tipo:"Gabinete",nivel:"Direção Superior",superior:"SEPLAG",situacao:"Ativa"},
  {id:2,nome:"Secretaria Adjunta de Administração Sistêmica",sigla:"SAAS",codigo:"U0002",tipo:"Secretaria Adjunta",nivel:"Direção Superior",superior:"Gabinete do Secretário",situacao:"Ativa"},
  {id:3,nome:"Superintendência Administrativa",sigla:"SUAD",codigo:"U0003",tipo:"Superintendência",nivel:"Administração Sistêmica",superior:"Secretaria Adjunta de Administração Sistêmica",situacao:"Ativa"},
  {id:4,nome:"Coordenadoria de Aplicação e Desenvolvimento",sigla:"COAD",codigo:"U0004",tipo:"Coordenadoria",nivel:"Administração Sistêmica",superior:"Superintendência Administrativa",situacao:"Ativa"},
  {id:5,nome:"Gerência de Provimento e Monitoramento",sigla:"GEPM",codigo:"U0005",tipo:"Gerência",nivel:"Administração Sistêmica",superior:"Coordenadoria de Provimento, Manutenção e Monitoramento",situacao:"Ativa"},
  {id:6,nome:"Núcleo de Gestão Estratégica para Resultados",sigla:"NGER",codigo:"U0006",tipo:"Núcleo",nivel:"Apoio Estratégico e Especializado",superior:"Gabinete do Secretário",situacao:"Ativa"}
];
function Node({classe,nome,detalhe}:{classe:string;nome:string;detalhe:string}){return <div className={`unidades-node ${classe}`}>{nome}<small>{detalhe}</small></div>}

export function PrototiposUnidadesPage(){
  const [unidades,setUnidades]=useState(iniciais); const [form,setForm]=useState(false); const [tipo,setTipo]=useState(""); const [feedback,setFeedback]=useState("");
  const filtrosForm=useForm<Filtros>({defaultValues:{busca:"",nivelFiltro:"",tipoFiltro:"",situacaoFiltro:"Ativa"}});
  const cadastroForm=useForm<Cadastro>({defaultValues:{superior:"",nivel:"",nome:"",sigla:"",codigo:"",inicio:"",fim:"",documento:"Decreto nº 2.185, de 03/07/2026"}});
  const filtros=filtrosForm.watch(); const dados=cadastroForm.watch(); const tipos=tiposPorNivel[dados.nivel]||[];
  const lista=useMemo(()=>unidades.filter(u=>{const q=filtros.busca.trim().toLocaleLowerCase("pt-BR");return(!q||`${u.nome} ${u.sigla} ${u.codigo}`.toLocaleLowerCase("pt-BR").includes(q))&&(!filtros.nivelFiltro||u.nivel===filtros.nivelFiltro)&&(!filtros.tipoFiltro||u.tipo===filtros.tipoFiltro)&&(!filtros.situacaoFiltro||u.situacao===filtros.situacaoFiltro)}),[filtros,unidades]);
  const fechar=()=>{setForm(false);setTipo("");setFeedback("");cadastroForm.reset()};
  const salvar=()=>{if(!dados.superior||!dados.nivel||!tipo||!dados.nome.trim()||!dados.inicio||!dados.documento){setFeedback("Preencha os campos obrigatórios para salvar a unidade.");return}setUnidades(atual=>[...atual,{id:Date.now(),nome:dados.nome.trim(),sigla:dados.sigla.trim()||"—",codigo:`U${String(atual.length+1).padStart(4,"0")}`,tipo,nivel:dados.nivel,superior:dados.superior,situacao:"Ativa"}]);fechar();setFeedback("Unidade cadastrada com sucesso.")};
  return <PrototypeSystemPage nomeSistema="SIGEP" ambienteSistema="Protótipo" menuItems={menuGestaoPessoas}><div className="unidades-page prototype-page-content">
    {!form?<CardSeplag title="Unidades Organizacionais" cols="12" legenda={()=><p className="unidades-desc">Consulte e mantenha os setores, gabinetes, núcleos e demais unidades cadastradas para o órgão.</p>}>
      <div className="col-12 unidades-filtros"><div className="grid"><TextFieldSeplag name="busca" label="Pesquisar unidade" placeholder="Nome, sigla ou código" cols="12 6 4" control={filtrosForm.control} getFormErrorMessage={noError}/><DropdownFieldSeplag name="nivelFiltro" label="Nível organizacional" placeholder="Todos" cols="12 6 3" control={filtrosForm.control} options={opts(niveis)} optionLabel="label" optionValue="value" getFormErrorMessage={noError}/><DropdownFieldSeplag name="tipoFiltro" label="Tipo de unidade" placeholder="Todos" cols="12 6 2" control={filtrosForm.control} options={opts([...new Set(Object.values(tiposPorNivel).flat())])} optionLabel="label" optionValue="value" getFormErrorMessage={noError}/><DropdownFieldSeplag name="situacaoFiltro" label="Situação" cols="12 6 2" control={filtrosForm.control} options={opts(["Ativa","Inativa"])} optionLabel="label" optionValue="value" getFormErrorMessage={noError}/><div className="col-12 md:col-6 lg:col-1 unidades-clear"><BotaoLimparFiltroSeplag onClick={()=>filtrosForm.reset()}/></div></div></div>
      <div className="col-12 unidades-table-section"><div className="unidades-table-toolbar"><BotaoSeplag label="Adicionar" icon="pi pi-plus" onClick={()=>{setForm(true);setFeedback("")}}/></div><div className="unidades-table"><table><thead><tr><th>Unidade</th><th>Tipo</th><th>Nível</th><th>Unidade superior</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{lista.map(u=><tr key={u.id}><td><strong>{u.nome}</strong><small>{u.sigla} • {u.codigo}</small></td><td><span className="unidades-chip">{u.tipo}</span></td><td>{u.nivel}</td><td>{u.superior}</td><td><span className={`unidades-status ${u.situacao.toLowerCase()}`}>{u.situacao}</span></td><td><SplitButton aria-label={`Ações de ${u.nome}`} icon="pi pi-eye" onClick={()=>{}} model={[{label:"Editar",icon:"pi pi-pencil",command:()=>{}}]}/></td></tr>)}</tbody></table>{!lista.length&&<div className="unidades-empty">Nenhuma unidade encontrada.</div>}</div></div>
      <div className="col-12"><div className="unidades-rule"><i className="pi pi-info-circle"/><span><strong>Regra:</strong> a unidade é cadastrada uma única vez e depois utilizada na montagem do organograma. O tipo disponível depende do nível organizacional parametrizado.</span></div></div>
    </CardSeplag>:<><header className="unidades-header"><span>Estrutura Organizacional</span><h1>Cadastrar - Unidade Organizacional</h1><p>Cadastre a unidade que fará parte da estrutura organizacional do órgão.</p></header><div className="unidades-layout"><div>
      <CardSeplag title="Enquadramento na estrutura" cols="12" legenda={()=><p className="unidades-desc">Defina a vinculação hierárquica e o enquadramento da unidade.</p>}><div className="grid"><DropdownFieldSeplag name="superior" label="Unidade superior / pai" required cols="12 6 6" control={cadastroForm.control} options={opts(["Gabinete do Secretário","Secretaria Adjunta de Administração Sistêmica","Secretaria Adjunta de Gestão de Pessoas","Superintendência Administrativa"])} optionLabel="label" optionValue="value" getFormErrorMessage={noError}/><DropdownFieldSeplag name="nivel" label="Nível organizacional" required cols="12 6 6" control={cadastroForm.control} options={opts(niveis)} optionLabel="label" optionValue="value" getFormErrorMessage={noError}/></div><div className="unidades-tipos"><label>Tipo da unidade *</label><p>{dados.nivel?`Tipos permitidos para “${dados.nivel}”`:"Selecione o nível organizacional para visualizar os tipos disponíveis."}</p><div>{tipos.map(t=><button type="button" key={t} className={tipo===t?"active":""} onClick={()=>setTipo(t)}><strong>{t}</strong><small>Permitido neste nível</small></button>)}</div></div></CardSeplag>
      <CardSeplag title="Identificação da unidade" cols="12"><div className="grid"><TextFieldSeplag name="nome" label="Nome da unidade" required cols="12 6 6" control={cadastroForm.control} getFormErrorMessage={noError}/><TextFieldSeplag name="sigla" label="Sigla" cols="12 6 6" control={cadastroForm.control} getFormErrorMessage={noError}/><TextFieldSeplag name="codigo" label="Código" disabled placeholder="Gerado automaticamente" cols="12 4 4" control={cadastroForm.control} getFormErrorMessage={noError}/><DateFieldSeplag name="inicio" label="Data de início" required cols="12 4 4" control={cadastroForm.control} getFormErrorMessage={noError}/><DateFieldSeplag name="fim" label="Data de fim" cols="12 4 4" control={cadastroForm.control} getFormErrorMessage={noError}/></div></CardSeplag>
      <CardSeplag title="Fundamentação legal" cols="12"><DropdownFieldSeplag name="documento" label="Documento legal" required control={cadastroForm.control} options={opts(["Decreto nº 2.185, de 03/07/2026","Selecione outro documento..."])} optionLabel="label" optionValue="value" getFormErrorMessage={noError}/></CardSeplag>{feedback&&<div className="unidades-feedback"><i className="pi pi-exclamation-circle"/> {feedback}</div>}<footer className="unidades-actions"><BotaoVoltarSeplag label="Voltar para listagem" onClick={fechar}/><div><BotaoSeplag label="Cancelar" outlined onClick={fechar}/><BotaoSalvarSeplag label="Salvar unidade" onClick={salvar}/></div></footer>
    </div><aside className="unidades-preview"><h2>Posição no organograma</h2><p>Prévia da posição da nova unidade na árvore.</p><Node classe="root" nome="SEPLAG" detalhe="Secretaria de Estado"/><Node classe="l1" nome="Gabinete do Secretário" detalhe="Direção Superior"/><Node classe="l1" nome="Secretaria Adjunta de Administração Sistêmica" detalhe="Direção Superior"/><Node classe="l2" nome="Superintendência Administrativa" detalhe="Administração Sistêmica"/><Node classe="l2 selected" nome={dados.superior||"Nova posição"} detalhe={dados.nivel||"Selecione unidade superior e nível"}/><Node classe="l3 new" nome={dados.nome||"+ Nova unidade"} detalhe={tipo||"Tipo ainda não selecionado"}/><p><strong>Importante:</strong> o tipo é parametrizado previamente. Aqui o usuário cria a unidade concreta e define sua posição.</p></aside></div></>}
    {!form&&feedback&&<div className="unidades-toast"><i className="pi pi-check-circle"/> {feedback}</div>}
  </div></PrototypeSystemPage>
}
