import type { SpecificationMetadata } from "../../shared/visualizationModes";

const story = "US-XXX — Cadastro de Concurso Público e Processo Seletivo Simplificado";
const spec = (id:string, title:string, description:string, businessRule:string, source:string, dataType:string, component:string, behavior?:string):SpecificationMetadata => ({ id, title, description, businessRule, source, dataType, component, behavior, status:"CONFIRMADO", userStory:story });

export const certameFormScreenSpecification = spec(
 "PSS-CERT-FRM", "Cadastro/Edição de Certame", "Cadastrar ou editar um Concurso Público / PSS com base no edital publicado, replicando os campos hoje mantidos na tela 253 do CEAP.",
 "Cenário 1 (cadastro válido) exige tipo, nome/número do edital, número do certame, órgão responsável, lei, regime jurídico, tipo de vínculo, data de publicação e ao menos um cargo/vaga.",
 "Certame do controlePssStore.", "Certame", "Formulário React organizado em blocos/abas",
 "Salvar grava em controlePssStore.certames; o certame criado passa a status 'Aberto' (RN-15).",
);

export const certameFormTabSpecifications: Record<string, SpecificationMetadata> = {
 "Dados Gerais": spec("PSS-CERT-FRM-TAB-001", "Dados Gerais do Certame", "Identificação do certame: tipo, número do edital do órgão, número/ano, lei, regime, vínculo, órgão e objetivo.", "RN-01 (tipo único Conc/PSS — RN-06.2), RN-02 (padrão de nomenclatura do edital), RN-03 (número TCE-MT sequencial e editável), RN-04 (numeração própria por órgão), RN-05 (órgão mandante único) e RN-06.4 (rótulo \"(selecione)\" em Órgãos participantes). O campo \"Sigla\" foi unificado ao \"Número do edital do órgão\", eliminando a redundância entre os dois. Lei de contrato temporário e Lei de PSS ficam ocultas quando o tipo é Concurso (RN-06, seção 3).", "Certame (bloco 1).", "Certame", "formulário"),
 "Datas, Validades e Execução": spec("PSS-CERT-FRM-TAB-002", "Datas, Validades e Execução", "Datas do fluxo do certame e forma de execução (própria ou empresa contratada).", "RN-07 — a data de publicação do edital não pode ser posterior a nenhuma data subsequente do fluxo. Data de prorrogação e Data de cancelamento ficam ocultas para Processo Seletivo (RN-06, seção 3).", "Certame (bloco 2).", "Certame", "formulário"),
 "Prazos": spec("PSS-CERT-FRM-TAB-003", "Prazos", "Prazos, em dias, para exercício e posse — e suas prorrogações.", "Campos numéricos de apoio à contagem de prazos posteriores ao ingresso. Aba dispensada por completo para Processo Seletivo (RN-06, seção 3).", "Certame (bloco 3).", "Certame", "formulário"),
 "Isenção": spec("PSS-CERT-FRM-TAB-004", "Isenção de Taxa", "Período e base legal de isenção da taxa de inscrição.", "RN-13 — obrigatório quando o certame prevê cobrança de taxa e isenção. Aba dispensada por completo para Processo Seletivo (RN-06, seção 3).", "Certame (bloco 4).", "Certame", "formulário"),
 "Recursos e Contratos": spec("PSS-CERT-FRM-TAB-005", "Recursos e Contratos", "Contratação de banca/empresa organizadora e referências financeiras (empenho, contrato, UO/UG, aditivos).", "RN-12 — empenho, contrato, tipo de contratação e aditivos tornam-se obrigatórios quando há contratação de banca. Exibida tanto para Concurso Público quanto para Processo Seletivo (RN-06, seção 3).", "Certame (bloco 5).", "Certame", "formulário com campos condicionais"),
 "Cotas": spec("PSS-CERT-FRM-TAB-006", "Cotas", "Sub-grade 1:N de cotas cadastradas para o certame (tipo e lei vinculada).", "RN-08 — o sistema aceita múltiplas cotas por certame. RN-10 — a lei é buscada no catálogo já cadastrado no sistema.", "Certame.cotas.", "CotaCertame[]", "sub-grade"),
 "Cargos e Vagas": spec("PSS-CERT-FRM-TAB-007", "Cargo/Vagas e Fases", "Sub-grade de cargos/vagas do certame e lista editável das fases do fluxo.", "RN-09 (catálogo do TCE-MT como sugestão inicial; fases totalmente editáveis — renomear, reordenar, incluir e remover), RN-10 (código de referência fixo '001'), RN-14 (vaga existente ou nova) e RN-17 (vínculo automático e somente leitura com o Quadro de Vagas do Controle de Vagas > Quadro Autorizado, por cargo — rastreabilidade Edital → Quadro de Vagas → Gestão de Ingresso).", "Certame.cargos, Certame.fases.", "CargoVagaCertame[]", "sub-grade"),
 "Documentos": spec("PSS-CERT-FRM-TAB-008", "Documentos", "Anexos que compõem o pacote de prestação de contas da abertura do edital.", "Capítulo III, itens 1.1 (Concurso) e 3.1 (PSS) do Manual de Orientação para Remessa de Documentos ao TCE/MT — justificativa, edital integral, comprovante de publicação do edital, lei/ato de autorização, declaração do ordenador de despesa, designação da comissão, lotacionograma analítico, parecer do controle interno e declaração do responsável são obrigatórios; demonstrativo de impacto (LRF) condicionado a haver despesa e contrato social condicionado à execução por empresa contratada.", "Certame.documentos.", "DocumentoCertame[]", "tabela com anexo, visualização e remoção por linha"),
 "Situações": spec("PSS-CERT-FRM-TAB-009", "Situações do Certame", "Histórico de situações do certame e registro de uma nova situação.", "RN-15 (nove situações, prazo de 48h) e RN-16 (homologação é o marco do prazo, distinto da publicação do resultado).", "Certame.situacaoAtual, Certame.historicoSituacoes.", "SituacaoHistoricoCertame[]", "linha do tempo + formulário", "Disponível apenas para certames já salvos."),
};

export const certameFormBlockSpecifications = {
 seletorTipo: spec("PSS-CERT-FRM-BLC-004", "Seleção do tipo de certame (etapa 1)", "Exigir a escolha entre Concurso Público e Processo Seletivo antes de exibir os demais campos do cadastro.", "RN-06.1 e Cenário 1 — a definição do tipo é a primeira etapa do fluxo; os campos subsequentes só aparecem após a escolha.", "Certame.tipoCertame.", "TipoCertame", "seletor de duas opções, exibido apenas no cadastro de novo certame"),
 mandanteBloqueado: spec("PSS-CERT-FRM-BLC-001", "Órgão mandante travado após salvar", "Impedir a troca do órgão responsável de um certame já cadastrado.", "RN-05 e Cenário 6 — não é permitido que outro órgão passe a responder pela prestação de contas de um certame que não é seu.", "Certame.setor.", "string", "campo somente leitura após a primeira gravação"),
 fasesFixas: spec("PSS-CERT-FRM-BLC-003", "Fases do certame", "Lista de fases do certame, iniciada com o catálogo padrão do TCE-MT.", "RN-09 — o usuário pode reordenar (arrastar e soltar pelo mouse), remover e adicionar novas fases; o nome de cada fase não é editável após cadastrada.", "Certame.fases.", "FaseCertame[]", "tabela com reordenação por arraste"),
 quadroVagasVinculado: spec("PSS-CERT-FRM-BLC-005", "Quadro de Vagas vinculado ao cargo", "Buscar e exibir o Quadro de Vagas (código e versão) vinculado automaticamente ao cargo selecionado ou digitado.", "RN-17 — vínculo automático, somente leitura, sem escolha manual; garante rastreabilidade Edital → Quadro de Vagas → Gestão de Ingresso. Vínculo em Controle de Vagas > Quadro Autorizado.", "CARGOS_CADASTRADOS (quadroCodigo/quadroVersao) e CargoVagaCertame.", "string", "campo somente leitura, atualizado ao trocar o cargo/função"),
} satisfies Record<string, SpecificationMetadata>;

export const certameFormActionSpecifications: Record<string, SpecificationMetadata> = {
 "Salvar certame": spec("PSS-CERT-FRM-ACT-001", "Salvar certame", "Gravar o certame no controlePssStore.", "Cenário 1 — o certame criado é salvo com status 'Aberto' (RN-15) e disponibilizado para vínculo futuro de candidatos.", "Formulário completo.", "Certame", "botão de submit"),
 "Adicionar cota": spec("PSS-CERT-FRM-ACT-002", "Adicionar cota", "Incluir uma linha na sub-grade de cotas.", "RN-08.", "Formulário de inclusão de cota.", "CotaCertame", "botão + sub-grade"),
 "Adicionar cargo/vaga": spec("PSS-CERT-FRM-ACT-003", "Adicionar cargo/vaga", "Incluir uma linha na sub-grade de cargos/vagas.", "RN-10, RN-14.", "Formulário de inclusão de cargo.", "CargoVagaCertame", "botão + sub-grade"),
 "Registrar situação": spec("PSS-CERT-FRM-ACT-004", "Registrar nova situação", "Registrar uma mudança de situação do certame e calcular o prazo de prestação de contas.", "RN-15, RN-16 e Cenário 7.", "SituacaoHistoricoCertame.", "SituacaoHistoricoCertame", "formulário + linha do tempo"),
};

export const certameFormBusinessItems = [...Object.values(certameFormTabSpecifications), ...Object.values(certameFormBlockSpecifications), ...Object.values(certameFormActionSpecifications)];
