import type { SpecificationMetadata } from "../shared/visualizationModes";

const allFilters="Data de referência, órgão titular, órgão de distribuição, órgão de exercício, tipo de quadro, carreira, cargo, situação legal e somente cessões.";
const story="US Controle de Vagas — Dashboard Gerencial";
const spec=(id:string,title:string,description:string,businessRule:string,source:string,dataType:string,component:string,route?:string,behavior?:string,filters=allFilters):SpecificationMetadata=>({id,title,description,businessRule,source,dataType,component,filters,status:"CONFIRMADO",route,behavior,userStory:story});

export const dashboardScreenSpecification=spec("CV-DASH","Dashboard Gerencial","Consolidar a posição legal, distributiva, ocupacional, funcional e projetada das vagas para apoiar planejamento de provimento e análise do quadro.","Considerar somente vagas de cargos efetivos e comissionados válidas na data de referência; preservar a distinção entre órgão titular, órgão de distribuição e órgão de exercício; projeções são informativas e não autorizam concurso ou nomeação.","Quadro Autorizado, Vagas Individualizadas, Distribuição, ocupações ativas, Movimentações e Projeções.","DashboardViewModel","Página React + seletores derivados do store","/prototipos/sigep/backlog/dashboard","Recalcula a visão quando filtros, cenário, horizonte ou dados do store forem alterados.");

export const dashboardFilterSpecifications:Record<string,SpecificationMetadata>={
 "Data de referência":spec("CV-DASH-FLT-002","Data de referência","Reconstruir a posição do quadro na data escolhida.","Aplicar vigências legais, distribuições, ocupações e movimentos com data de efeito igual ou anterior à referência; não usar a data de registro como substituta da data de efeito.","Filtro informado pelo usuário e histórico temporal do Controle de Vagas.","string ISO date (YYYY-MM-DD)","input[type=date]",undefined,"Ao alterar, recalcula todos os indicadores, grupos e distribuições na posição temporal informada.","Não se aplica; é o filtro temporal principal."),
 "Órgão titular":spec("CV-DASH-FLT-003","Órgão titular","Exibir vagas cujo vínculo jurídico de titularidade pertence ao órgão selecionado.","Titularidade não é alterada por cessão, exercício ou distribuição administrativa, salvo alteração legal expressa.","Vaga.orgaoTitular.","string | vazio","select simples",undefined,"Vazio representa todos; as opções são derivadas das vagas existentes.","Data de referência e demais filtros do Dashboard."),
 "Órgão de distribuição":spec("CV-DASH-FLT-004","Órgão de distribuição","Restringir a visão às vagas administrativamente destinadas ao órgão selecionado.","A posição deve ser reconstruída pelo último movimento de distribuição com efeito até a data de referência; pendência de ato não é órgão.","Movimentos de Distribuição e posição temporal da Vaga.","string | PENDENTE_ATO | vazio","select simples",undefined,"Inclui a opção de posição pendente de ato de distribuição.","Data de referência, quadro, cargo e demais filtros."),
 "Órgão de exercício":spec("CV-DASH-FLT-005","Órgão de exercício","Exibir vagas ocupadas por vínculos que exercem suas atividades no órgão selecionado.","O exercício pode divergir da titularidade e da lotação em razão de cessão; vagas sem ocupante ativo não atendem a este filtro.","OcupacaoVaga.orgaoExercicio e cessões efetivadas.","string | vazio","select simples",undefined,"Filtra pela ocupação ativa na data de referência.","Data de referência, somente cessões e demais filtros."),
 "Tipo":spec("CV-DASH-FLT-006","Tipo de quadro","Separar cargos efetivos e comissionados.","Temporários e vínculos sem limite legal não integram este Dashboard.","Vaga.tipo e QuadroAutorizado.tipoQuadro.","'' | EFETIVO | COMISSIONADO","select simples",undefined,"A opção vazia consolida efetivos e comissionados.","Data de referência e demais filtros."),
 "Carreira":spec("CV-DASH-FLT-007","Carreira","Restringir a posição a uma carreira.","Usar a carreira registrada na vaga e em sua origem legal; não inferir por semelhança do nome do cargo.","Vaga.carreira.","string | vazio","select simples",undefined,"Opções distintas derivadas das vagas; vazio representa todas.","Tipo, cargo e demais filtros."),
 "Cargo":spec("CV-DASH-FLT-008","Cargo","Restringir indicadores e grupos ao cargo selecionado.","Quadros diferentes do mesmo cargo permanecem separados no quadro estratégico, ainda que compartilhem o nome.","Vaga.cargo.","string | vazio","select simples",undefined,"Opções distintas derivadas das vagas; vazio representa todos.","Tipo, carreira e demais filtros."),
 "Situação legal":spec("CV-DASH-FLT-009","Situação legal","Consultar vagas segundo sua condição jurídica na data de referência.","Regular, em extinção, extinta e em transformação são situações da vaga; extinta não compõe o limite vigente após sua data de efeito.","Vaga.situacaoLegal e histórico legal.","'' | REGULAR | EM_EXTINCAO | EXTINTA | EM_TRANSFORMACAO","select simples",undefined,"Vazio representa todas as situações.","Data de referência e demais filtros."),
 "Somente cessões":spec("CV-DASH-FLT-010","Somente cessões","Exibir somente vagas cuja ocupação ativa esteja vinculada a uma cessão vigente.","A cessão preserva vaga, ocupação e titularidade e altera o exercício; processos ainda não efetivados não atendem ao filtro.","MovimentacaoFuncional do tipo CESSAO e ocupações ativas.","boolean","checkbox",undefined,"Marcado restringe toda a visão; desmarcado não exclui cessões.","Data de referência, órgão de exercício e demais filtros."),
 "Indicadores exibidos":spec("CV-DASH-FLT-011","Indicadores exibidos","Permitir que o usuário escolha quais cartões gerenciais aparecem na tela ou exportação.","A ocultação é apenas visual e não altera cálculos, filtros, dados ou valores dos demais blocos.","Preferência local da sessão do usuário.","Record<IndicadorDashboardId, boolean>","grupo de switches",undefined,"Cada switch controla um KPI; todos iniciam visíveis.","Não altera filtros de negócio."),
 "Limpar":spec("CV-DASH-FLT-012","Limpar filtros","Restaurar os filtros de negócio para os valores iniciais.","Restaurar a data padrão e remover órgãos, tipo, carreira, cargo, situação e somente cessões; não modificar cenário, horizonte nem visibilidade dos KPIs.","Constante filtrosIniciais.","command","botão",undefined,"Executa uma atualização única do estado de filtros.","Não se aplica."),
};

export const dashboardBlockSpecifications={
 filters:spec("CV-DASH-FLT-001","Filtros da consulta","Abrir ou recolher os critérios que restringem toda a posição gerencial.","Todos os KPIs, composição, alertas, quadro estratégico e potencial devem usar a mesma instância de DashboardFiltros.","Estado local DashboardFiltros e listas derivadas do store.","DashboardFiltros","Accordion + formulário",undefined,"Inicia fechado; abrir não altera os resultados."),
 composition:spec("CV-DASH-BLC-001","Composição do quadro","Comparar o limite legal com ocupadas, disponíveis livres, disponíveis comprometidas e ocupadas em disponibilização.","Comprometimento não altera o estado definitivo antes do evento de conclusão; categorias auxiliares podem se sobrepor ao estado, portanto a legenda não deve ser somada como partição cega.","Vagas individualizadas, ocupações ativas e comprometimentos ativos.","ResumoDashboard","gráfico de rosca + legenda",undefined,"A rosca usa ocupadas sobre vagas legais; a legenda apresenta os saldos complementares."),
 alerts:spec("CV-DASH-BLC-002","Alertas gerenciais","Destacar situações operacionais ou jurídicas que exigem análise da gestão de vagas.","Cada alerta deve abrir os registros que formam seu número; alertas financeiros e divergências técnicas não pertencem a esta visão gerencial.","Quadros sem saldo livre, exceções judiciais, vagas em extinção e cessões ativas.","AlertaGerencial[]","lista de links",undefined,"Os valores respeitam os filtros gerais e cada linha navega para a consulta correspondente."),
 projection:spec("CV-DASH-BLC-003","Projeção estratégica","Apresentar uma síntese do potencial de vagas para provimento por cenário e horizonte.","Potencial é a soma de vagas livres e novas disponibilizações estimadas pela metodologia vigente; não equivale a autorização, orçamento ou quantitativo de concurso.","Saldos atuais, fatores por vínculo, taxas de evasão e MetodologiaProjecao vigente.","ResultadoProjecao agregado","seletor de cenário + horizonte + resumo","/prototipos/sigep/backlog/projecoes","Cenário ou horizonte recalculam a projeção sem alterar o saldo real."),
 table:spec("CV-DASH-TBL-001","Quadro estratégico por autorização, cargo e órgão","Apresentar a memória consolidada utilizada para priorizar análises de provimento.","Agrupar pela origem legal, cargo e órgão titular; não combinar Quadros Autorizados distintos nem confundir titularidade, distribuição e exercício.","Quadro Autorizado, vagas, ocupações, comprometimentos, exceções judiciais, cessões, distribuição e projeções.","DashboardGrupo[]","tabela gerencial",undefined,"A seta abre a memória do grupo; Ver vagas abre a consulta detalhada."),
 potential:spec("CV-DASH-BLC-004","Potencial de vagas para provimento","Comparar os grupos com maior quantidade potencial de vagas no cenário e horizonte selecionados.","Ordenar por potencial decrescente; potencial = disponíveis livres + compulsórias + requeridas + exonerações conhecidas + elegibilidade ponderada + evasão estimada.","Motor de Projeções e saldo disponível livre atual.","Array<{cargo, orgao, potencial}>","barras horizontais",undefined,"Exibe até seis grupos; o comprimento é relativo ao maior valor e o clique abre a memória do grupo."),
 recent:spec("CV-DASH-BLC-005","Distribuições recentes","Exibir os últimos movimentos administrativos de distribuição e redistribuição.","Ordenar pela data/hora de registro, limitar aos cinco mais recentes e sinalizar movimento retroativo; não misturar evolução legal do quadro.","MovimentoVagaIndividual do tipo DISTRIBUICAO ou REDISTRIBUICAO.","MovimentoVagaIndividual[]","lista temporal","/prototipos/sigep/backlog/distribuicao","Ver todas abre Distribuição; cada registro mostra vaga, data de efeito e ato."),
} satisfies Record<string,SpecificationMetadata>;

export const dashboardAlertSpecifications:Record<string,SpecificationMetadata>={
 "Quadros sem saldo livre":spec("CV-DASH-ALT-001","Quadros sem saldo livre","Identificar grupos legais sem vaga disponível livre para provimento imediato.","Contar grupos com disponíveisLivres igual a zero; vagas comprometidas não são saldo livre.","DashboardGrupo.disponiveisLivres.","integer","alerta navegável","/prototipos/sigep/backlog/quadro-autorizado","Abre a consulta dos quadros de origem."),
 "Ocupações judiciais extraquadro":spec("CV-DASH-ALT-002","Ocupações judiciais extraquadro","Evidenciar ocupações excepcionais determinadas judicialmente que não ampliam automaticamente o limite legal.","Contabilizar exceções judiciais ativas separadamente das vagas legais regulares.","ExcecaoJudicialVaga e ocupações relacionadas.","integer","alerta navegável","/prototipos/sigep/backlog/vagas?legal=DECISAO_JUDICIAL","Abre as vagas e ocupações atingidas pela decisão."),
 "Vagas em extinção":spec("CV-DASH-ALT-003","Vagas em extinção","Indicar vagas que permanecem no histórico ou ocupadas, mas não podem receber nova ocupação.","Contar situação EM_EXTINCAO na data; quando ocorrer vacância definitiva, aplicar a extinção conforme o ato legal.","Vaga.situacaoLegal e histórico legal.","integer","alerta navegável","/prototipos/sigep/backlog/vagas?legal=EM_EXTINCAO","Abre Vagas Individualizadas já filtrada."),
 "Cessões ativas":spec("CV-DASH-ALT-004","Cessões ativas","Indicar vínculos que exercem atividades fora da unidade ou órgão de origem por cessão vigente.","Contar somente cessões efetivadas com situação operacional ATIVA; a vaga de origem continua ocupada.","Movimentações Funcionais — Cessões e ocupações ativas.","integer","alerta navegável","/prototipos/sigep/backlog/movimentacoes?aba=CESSAO","Abre a aba Cessões."),
};

export const dashboardKpiSpecifications:Record<string,SpecificationMetadata>={
 "Cargos legais":spec("CV-DASH-KPI-001","Cargos legais","Quantidade de cargos distintos com vagas legais válidas na posição.","Contar nomes de cargo distintos entre vagas não extintas após aplicação dos filtros.","Vaga.cargo vinculada ao Quadro Autorizado.","integer","KPI navegável","/prototipos/sigep/backlog/quadro-autorizado","Abre Quadro Autorizado."),
 "Quadros vigentes":spec("CV-DASH-KPI-002","Quadros vigentes","Quantidade de origens legais distintas presentes na posição filtrada.","Contar códigos de Quadro Autorizado distintos com ao menos uma vaga legal válida na data.","Vaga.quadroCodigo e vigência do Quadro Autorizado.","integer","KPI navegável","/prototipos/sigep/backlog/quadro-autorizado","Abre Quadro Autorizado."),
 "Vagas legais":spec("CV-DASH-KPI-003","Vagas legais","Total de vagas que compõem o limite legal vigente.","Contar vagas individualizadas válidas e excluir as extintas na data de referência; exceção judicial extraquadro não amplia este total.","Vagas Individualizadas e histórico da situação legal.","integer","KPI navegável","/prototipos/sigep/backlog/vagas","Abre Vagas Individualizadas."),
 "Ocupadas":spec("CV-DASH-KPI-004","Ocupadas","Vagas com ocupação nominal ativa na data de referência.","Cada vínculo ativo ocupa uma única vaga; cessão e processo de saída não desocupam a vaga antes do evento definitivo.","Vaga.estado e OcupacaoVaga ativa.","integer + percentual","KPI navegável","/prototipos/sigep/backlog/vagas?estado=OCUPADA","Percentual = ocupadas / vagas legais, com proteção para divisor zero."),
 "Disponíveis":spec("CV-DASH-KPI-005","Disponíveis","Vagas sem ocupação ativa na posição consultada.","Inclui disponíveis livres e comprometidas para ocupação; extintas não entram. O texto auxiliar informa apenas as livres.","Vaga.estado e comprometimentos ativos.","integer + subtotal","KPI navegável","/prototipos/sigep/backlog/vagas?estado=DISPONIVEL","Abre a lista filtrada por estado disponível."),
 "Comprometidas":spec("CV-DASH-KPI-006","Comprometidas para ocupação","Vagas disponíveis reservadas por processo de ingresso ainda não concluído.","Não alterar o estado para ocupada até posse/exercício ou evento definitivo; impedir dupla reserva incompatível.","ComprometimentoVaga de natureza OCUPACAO, futuramente recebido do Ingresso.","integer","KPI navegável","/prototipos/sigep/backlog/vagas?comprometimento=OCUPACAO","Abre a lista das vagas comprometidas."),
 "Em disponibilização":spec("CV-DASH-KPI-007","Em disponibilização","Vagas ainda ocupadas vinculadas a processo que poderá liberá-las.","Permanecem ocupadas até aposentadoria, exoneração ou encerramento definitivo; não são saldo disponível atual.","ComprometimentoVaga de natureza DISPONIBILIZACAO, futuramente recebido da Vida Funcional.","integer","KPI navegável","/prototipos/sigep/backlog/vagas?comprometimento=DISPONIBILIZACAO","Abre a lista correspondente."),
 "Pendente de ato de distribuição":spec("CV-DASH-KPI-008","Pendente de ato de distribuição","Vagas cuja origem legal deixou a destinação para ato administrativo posterior.","Pendência de ato é condição distributiva, não órgão nem banco central; o subtotal informa quantas também estão disponíveis.","Quadro Autorizado, Vaga e posição reconstruída pelos movimentos de Distribuição.","integer + subtotal","KPI navegável","/prototipos/sigep/backlog/distribuicao","Abre Distribuição."),
 "Situações legais especiais":spec("CV-DASH-KPI-009","Situações legais especiais","Vagas com situação diferente de Regular.","Contar em extinção, extintas na posição histórica aplicável e em transformação; decisões judiciais extraquadro são exibidas separadamente nos alertas.","Vaga.situacaoLegal e histórico legal.","integer","KPI navegável","/prototipos/sigep/backlog/vagas?legal=ESPECIAL","Abre Vagas Individualizadas filtrada."),
 "Cessões ativas":spec("CV-DASH-KPI-010","Cessões ativas","Vínculos com cessão vigente na data de referência.","A cessão altera exercício, preservando vaga, ocupação e titularidade; o texto auxiliar conta términos nos próximos 90 dias.","MovimentacaoFuncional CESSAO com detalhesCessao.situacaoOperacional ATIVA.","integer + subtotal","KPI navegável","/prototipos/sigep/backlog/movimentacoes?aba=CESSAO","Abre Cessões."),
 "Cessões externas":spec("CV-DASH-KPI-011","Cessões externas","Subconjunto das cessões ativas cujo destino não é uma cessão interna.","Não somar ao total de cessões como categoria adicional; considerar somente cessões ativas de modalidades externas.","Movimentações Funcionais — Cessões.","integer","KPI navegável","/prototipos/sigep/backlog/movimentacoes?aba=CESSAO","Abre Cessões."),
 "Remoções em andamento":spec("CV-DASH-KPI-013","Remoções em andamento","Processos de remoção ainda não concluídos.","Excluir efetivadas, devolvidas, rejeitadas, canceladas e encerradas; até a efetivação, preservar a posição vigente da ocupação e da vaga.","MovimentacaoFuncional do tipo REMOCAO.","integer","KPI navegável","/prototipos/sigep/backlog/movimentacoes?aba=REMOCAO","Abre Remoções."),
 "Aguardando publicação":spec("CV-DASH-KPI-015","Aguardando publicação","Movimentações autorizadas sem publicação registrada.","Contar situação AUTORIZADA; não efetivar efeitos funcionais antes da publicação quando ela for exigida.","Movimentações Funcionais.","integer","KPI navegável","/prototipos/sigep/backlog/movimentacoes?aba=HISTORICO","Abre Histórico."),
 "Aguardando efetivação":spec("CV-DASH-KPI-016","Aguardando efetivação","Movimentações publicadas ou agendadas que ainda não produziram seus efeitos.","Contar PUBLICADA e AGENDADA_EFETIVACAO; aplicar alteração somente na data/evento definitivo.","Movimentações Funcionais.","integer","KPI navegável","/prototipos/sigep/backlog/movimentacoes?aba=HISTORICO","Abre Histórico."),
};

export const dashboardBusinessItems=[...Object.values(dashboardFilterSpecifications),...Object.values(dashboardBlockSpecifications),...Object.values(dashboardAlertSpecifications),...Object.values(dashboardKpiSpecifications)];
