import type { SpecificationMetadata } from "../shared/visualizationModes";

const filters="Data de referência, órgão titular, órgão de distribuição, órgão de exercício, tipo, carreira, cargo, situação legal e somente cessões.";
const spec=(id:string,title:string,description:string,businessRule:string,source:string,dataType:string,component:string,route?:string):SpecificationMetadata=>({id,title,description,businessRule,source,dataType,component,filters,status:"CONFIRMADO",route,userStory:"US Quadro de Pessoal — Dashboard Gerencial"});

export const dashboardScreenSpecification:SpecificationMetadata=spec("CV-DASH","Dashboard Gerencial","Apresentar a posição legal, ocupacional, distributiva e projetada para apoiar decisões de provimento.","Consolidar somente cargos efetivos e comissionados, respeitando a data de referência e mantendo separados órgão titular, distribuição e órgão de exercício.","Quadro Autorizado, Vagas Individualizadas, Cessões, Distribuição e Projeções.","Visão gerencial consolidada","Página / Dashboard","/prototipos/sigep/quadro-pessoal/dashboard");

export const dashboardBlockSpecifications={
 filters:spec("CV-DASH-FLT-001","Filtros da consulta","Restringir toda a posição gerencial do Dashboard.","Todos os indicadores, gráficos, alertas e grupos devem ser recalculados com os mesmos filtros.","Parâmetros do usuário e listas derivadas do store do Quadro de Pessoal.","DashboardFiltros","Accordion + formulário"),
 composition:spec("CV-DASH-BLC-001","Composição do quadro","Comparar vagas legais, ocupadas, disponíveis livres, comprometidas e em disponibilização.","Comprometimentos não alteram o estado definitivo da vaga antes do evento de conclusão.","Vagas Individualizadas, ocupações nominais e comprometimentos ativos.","Agregação numérica","Gráfico de rosca + legenda"),
 alerts:spec("CV-DASH-BLC-002","Alertas gerenciais","Destacar situações que exigem análise da gestão.","Cada alerta deve direcionar para os registros que compõem seu valor.","Quadro legal, integridade, exceções judiciais, situações legais e cessões.","Lista de alertas","Lista de ações"),
 projection:spec("CV-DASH-BLC-003","Projeção estratégica","Apresentar o potencial de vagas por horizonte e cenário.","Somar vagas livres às saídas previstas segundo a metodologia vigente; não representa autorização automática de concurso.","Fatores por vínculo, taxas históricas, metodologia e saldo atual.","ResultadoProjetado","Controles + resumo calculado","/prototipos/sigep/quadro-pessoal/projecoes"),
 table:spec("CV-DASH-TBL-001","Quadro estratégico","Detalhar a posição por Quadro Autorizado, cargo e órgão titular.","Quadros diferentes do mesmo cargo não podem ser combinados; distribuição, titularidade e exercício são conceitos distintos.","Quadro Autorizado, vagas, ocupações, comprometimentos, cessões, distribuição e projeções.","DashboardGrupo[]","Tabela gerencial"),
 potential:spec("CV-DASH-BLC-004","Necessidade potencial","Comparar os grupos com maior potencial de vagas no cenário selecionado.","Ordenar os grupos pelo potencial projetado no horizonte atual.","Motor de Projeções e saldo disponível atual.","Série numérica ordenada","Gráfico de barras"),
 recent:spec("CV-DASH-BLC-005","Distribuições recentes","Exibir as últimas distribuições iniciais e redistribuições de vagas.","Não misturar evoluções legais do quadro com movimentos administrativos de distribuição.","Histórico individual de movimentos das vagas.","MovimentoVagaIndividual[]","Lista temporal","/prototipos/sigep/quadro-pessoal/distribuicao"),
} satisfies Record<string,SpecificationMetadata>;

export const dashboardKpiSpecifications:Record<string,SpecificationMetadata>={
 "Cargos legais":spec("CV-DASH-KPI-001","Cargos legais","Quantidade de cargos legais distintos.","Contar cargos distintos entre vagas legais não extintas.","Vagas Individualizadas vinculadas aos Quadros Autorizados.","integer","KPI","Quadro Autorizado"),
 "Quadros vigentes":spec("CV-DASH-KPI-002","Quadros vigentes","Quantidade de origens legais presentes na posição.","Contar códigos distintos de Quadro Autorizado com vagas legais.","Quadro Autorizado e Vagas Individualizadas.","integer","KPI","Quadro Autorizado"),
 "Vagas legais":spec("CV-DASH-KPI-003","Vagas legais","Total de vagas que compõem o limite legal vigente.","Excluir vagas legalmente extintas.","Vagas Individualizadas e situação legal.","integer","KPI","Vagas Individualizadas"),
 "Ocupadas":spec("CV-DASH-KPI-004","Vagas ocupadas","Total de vagas com ocupação ativa.","Cada vínculo ativo ocupa uma vaga; processo de saída não muda o estado antes do evento definitivo.","Vagas Individualizadas e ocupações nominais.","integer + percentual","KPI","Vagas ocupadas"),
 "Disponíveis":spec("CV-DASH-KPI-005","Vagas disponíveis","Total de vagas com estado definitivo Disponível.","Inclui vagas livres e comprometidas para ocupação, exceto vagas extintas.","Vagas Individualizadas e comprometimentos.","integer","KPI","Vagas disponíveis"),
 "Comprometidas":spec("CV-DASH-KPI-006","Disponíveis comprometidas","Vagas disponíveis vinculadas a processo de ocupação.","O comprometimento não altera o estado antes da conclusão do ingresso.","Eventos automáticos de Ingresso do Servidor.","integer","KPI","Vagas comprometidas"),
 "Em disponibilização":spec("CV-DASH-KPI-007","Ocupadas em disponibilização","Vagas ocupadas em processo de liberação.","A vaga permanece ocupada até o encerramento definitivo do vínculo.","Eventos automáticos de Vida Funcional.","integer","KPI","Vagas em disponibilização"),
 "Pendente de ato de distribuição":spec("CV-DASH-KPI-008","Vagas pendentes de ato","Vagas cuja lei exige ato posterior para definir a destinação.","Ausência de distribuição não altera titularidade nem estado da vaga.","Quadro Autorizado e histórico de Distribuição.","integer","KPI","Distribuição"),
 "Situações legais especiais":spec("CV-DASH-KPI-009","Situações legais especiais","Vagas com situação legal diferente de Regular.","Contar extinção e transformação; decisões judiciais extraquadro são separadas.","Situação legal da Vaga Individualizada.","integer","KPI","Vagas com situação especial"),
 "Cessões ativas":spec("CV-DASH-KPI-010","Cessões ativas","Vínculos com cessão funcional vigente.","A cessão altera o exercício, mas preserva vaga, ocupação e titularidade.","Movimentações Funcionais — Cessões.","integer","KPI","Movimentações / Cessões"),
 "Cessões externas":spec("CV-DASH-KPI-011","Cessões externas","Cessões ativas para destino externo ao órgão de origem.","Considerar as modalidades externas vigentes.","Movimentações Funcionais — Cessões.","integer","KPI","Movimentações / Cessões"),
 "Ressarcimentos pendentes":spec("CV-DASH-KPI-012","Ressarcimentos pendentes","Cessões ativas com ressarcimento pendente ou inadimplente.","Exibir somente cessões que exigem ressarcimento.","Movimentações Funcionais — Cessões.","integer","KPI","Movimentações / Cessões"),
 "Remoções em andamento":spec("CV-DASH-KPI-013","Remoções em andamento","Processos de remoção ainda não efetivados ou encerrados.","A remoção mantém a vaga e altera lotação ou exercício após efetivação.","Movimentações Funcionais — Remoções.","integer","KPI","Movimentações / Remoções"),
 "Aguardando publicação":spec("CV-DASH-KPI-015","Aguardando publicação","Movimentações autorizadas sem publicação registrada.","A efetivação depende da publicação do ato.","Movimentações Funcionais.","integer","KPI","Movimentações / Histórico"),
 "Aguardando efetivação":spec("CV-DASH-KPI-016","Aguardando efetivação","Movimentações publicadas ou agendadas que ainda não produziram efeito.","O estado da vaga só muda no evento definitivo.","Movimentações Funcionais.","integer","KPI","Movimentações / Histórico"),
};
export const dashboardBusinessItems=[...Object.values(dashboardBlockSpecifications),...Object.values(dashboardKpiSpecifications)];


