import { useMemo, useState } from "react";
import { Paginator, type PaginatorPageChangeEvent } from "primereact/paginator";
import { useAutorizacoesPessoalStore } from "./autorizacoesPessoalStore";
import type { PosicaoPessoal } from "./autorizacoesPessoalTypes";
import "./vagasIndividualizadas.css";

const situacaoLabel={DISPONIVEL:"Disponível",OCUPADA:"Ocupada",RESERVADA:"Reservada para ingresso",SUSPENSA:"Suspensa",ENCERRADA:"Encerrada"} as const;

export function PosicoesPessoalContent(){
 const {posicoes,autorizacoes}=useAutorizacoesPessoalStore();const [busca,setBusca]=useState("");const [vinculo,setVinculo]=useState("");const [orgao,setOrgao]=useState("");const [situacao,setSituacao]=useState("");const [pagina,setPagina]=useState(0);const [linhas,setLinhas]=useState(10);const [detalhe,setDetalhe]=useState<PosicaoPessoal|null>(null);
 const filtradas=useMemo(()=>posicoes.filter((item)=>(!busca||`${item.id} ${item.programaProjeto} ${item.objetoFinalidade} ${item.ocupanteAtual??""}`.toLowerCase().includes(busca.toLowerCase()))&&(!vinculo||item.tipoVinculo===vinculo)&&(!orgao||item.orgao===orgao)&&(!situacao||item.situacao===situacao)),[posicoes,busca,vinculo,orgao,situacao]);
 const exibidas=filtradas.slice(pagina*linhas,pagina*linhas+linhas);const op=(valores:string[])=>[...new Set(valores.filter(Boolean))].sort();
 const limpar=()=>{setBusca("");setVinculo("");setOrgao("");setSituacao("");setPagina(0)};
 return <div className="prototype-quadro-pessoal-vaga-page"><header className="prototype-quadro-pessoal-vaga-header"><div><h1>Posições Individualizadas</h1><p>Posições administrativas de bolsas, residências, estágios e situações semelhantes.</p></div></header>
  <section className="prototype-quadro-pessoal-vaga-kpis"><article><span>Posições</span><strong>{posicoes.length}</strong></article><article><span>Disponíveis</span><strong>{posicoes.filter((i)=>i.situacao==="DISPONIVEL").length}</strong></article><article><span>Ocupadas</span><strong>{posicoes.filter((i)=>i.situacao==="OCUPADA").length}</strong></article><article><span>Reservadas</span><strong>{posicoes.filter((i)=>i.situacao==="RESERVADA").length}</strong></article><article><span>Suspensas ou encerradas</span><strong>{posicoes.filter((i)=>["SUSPENSA","ENCERRADA"].includes(i.situacao)).length}</strong></article></section>
  <section className="prototype-quadro-pessoal-vaga-card"><div className="prototype-quadro-pessoal-vaga-filters">
   <label className="search"><span>Posição, programa, perfil ou ocupante</span><div><i className="pi pi-search"/><input value={busca} onChange={(e)=>{setBusca(e.target.value);setPagina(0)}} placeholder="Pesquisar posição"/></div></label>
   <label><span>Tipo de vínculo</span><select value={vinculo} onChange={(e)=>{setVinculo(e.target.value);setPagina(0)}}><option value="">Todos</option>{op(posicoes.map((i)=>i.tipoVinculo)).map((i)=><option key={i}>{i}</option>)}</select></label>
   <label><span>Órgão</span><select value={orgao} onChange={(e)=>{setOrgao(e.target.value);setPagina(0)}}><option value="">Todos</option>{op(posicoes.map((i)=>i.orgao)).map((i)=><option key={i}>{i}</option>)}</select></label>
   <label><span>Situação</span><select value={situacao} onChange={(e)=>{setSituacao(e.target.value);setPagina(0)}}><option value="">Todas</option>{Object.entries(situacaoLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
   <button onClick={limpar}><i className="pi pi-filter-slash"/> Limpar</button>
  </div><div className="prototype-quadro-pessoal-vaga-table"><table><thead><tr><th>Posição</th><th>Autorização</th><th>Vínculo</th><th>Programa / finalidade</th><th>Órgão / unidade</th><th>Situação</th><th>Ocupante atual</th><th>Período</th><th>Ações</th></tr></thead><tbody>{exibidas.map((item)=>{const autorizacao=autorizacoes.find((a)=>a.id===item.autorizacaoId);return <tr key={item.id}><td><button className="prototype-quadro-pessoal-vaga-link" onClick={()=>setDetalhe(item)}>{item.id}</button><small>sequencial {item.sequencial}</small></td><td><strong>{item.autorizacaoCodigo}</strong><small>{autorizacao?.tipoInstrumento}</small></td><td>{item.tipoVinculo}</td><td><strong>{item.programaProjeto||"—"}</strong><small>{item.objetoFinalidade}</small></td><td>{item.orgao}<small>{item.unidade}</small></td><td><span className={`prototype-quadro-pessoal-vaga-state ${item.situacao.toLowerCase()}`}>{situacaoLabel[item.situacao]}</span></td><td>{item.ocupanteAtual||"Sem ocupante"}</td><td>{item.inicioOcupacao||"—"}<small>{item.fimPrevisto?`até ${item.fimPrevisto}`:""}</small></td><td><button className="prototype-quadro-pessoal-vaga-detail-button" onClick={()=>setDetalhe(item)} title="Visualizar posição"><i className="pi pi-eye"/></button></td></tr>})}{!exibidas.length&&<tr><td colSpan={9}><div className="prototype-quadro-pessoal-authorization-empty"><i className="pi pi-inbox"/><strong>Nenhuma posição individualizada</strong><span>As posições serão criadas por autorizações configuradas nesse modo de controle.</span></div></td></tr>}</tbody></table></div>
  <footer className="prototype-quadro-pessoal-vaga-pagination"><Paginator first={pagina*linhas} rows={linhas} totalRecords={filtradas.length} rowsPerPageOptions={[10,20,50]} onPageChange={(e:PaginatorPageChangeEvent)=>{setPagina(e.page);setLinhas(e.rows)}} template="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown"/></footer></section>
  {detalhe&&<div className="prototype-quadro-pessoal-vaga-backdrop" onMouseDown={()=>setDetalhe(null)}><section className="prototype-quadro-pessoal-vaga-modal detail" onMouseDown={(e)=>e.stopPropagation()}><header><div><span>Posição individual</span><h2>{detalhe.id}</h2><p>{detalhe.autorizacaoCodigo} • {detalhe.tipoVinculo}</p></div><button onClick={()=>setDetalhe(null)}><i className="pi pi-times"/></button></header><div className="prototype-quadro-pessoal-vaga-detail-grid"><section><h3>Identificação administrativa</h3><dl><div><dt>Programa/projeto</dt><dd>{detalhe.programaProjeto||"Não informado"}</dd></div><div><dt>Objeto ou finalidade</dt><dd>{detalhe.objetoFinalidade||"Não informado"}</dd></div><div><dt>Órgão</dt><dd>{detalhe.orgao}</dd></div><div><dt>Unidade</dt><dd>{detalhe.unidade||"Não definida"}</dd></div><div><dt>Situação</dt><dd>{situacaoLabel[detalhe.situacao]}</dd></div><div><dt>Criada em</dt><dd>{detalhe.criadaEm}</dd></div></dl></section></div><section className="prototype-quadro-pessoal-vaga-history"><header><div><h3>Histórico de ocupação</h3><p>O identificador não é excluído ou reutilizado por outra posição.</p></div></header>{detalhe.historicoOcupacoes.length?<table><thead><tr><th>Pessoa</th><th>Matrícula / vínculo</th><th>Início</th><th>Fim</th></tr></thead><tbody>{detalhe.historicoOcupacoes.map((h)=><tr key={h.id}><td>{h.pessoa}</td><td>{h.matricula}<small>{h.vinculo}</small></td><td>{h.inicio}</td><td>{h.fim||"Atual"}</td></tr>)}</tbody></table>:<p>Sem ocupações registradas.</p>}</section><footer><button onClick={()=>setDetalhe(null)}>Fechar</button></footer></section></div>}
 </div>;
}

