import type {QuadroPessoalState} from "./quadroPessoalStore";
import type {MovimentacaoFuncional,OcupacaoVaga,Vaga} from "./types";
export function efetivarRemocaoExterna(state:QuadroPessoalState,movimentacaoId:string):{state:QuadroPessoalState;erro?:string}{
 const mov=state.movimentacoesFuncionais.find(m=>m.id===movimentacaoId),d=mov?.detalhesRemocao;if(!mov||mov.tipo!=="REMOCAO"||d?.abrangencia!=="EXTERNA"||!mov.vagaDestinoId)return{state,erro:"Remoção externa incompleta."};
 const origem=state.vagas.find(v=>v.id===mov.vagaOrigemId),destino=state.vagas.find(v=>v.id===mov.vagaDestinoId),ocupacao=state.ocupacoes.find(o=>o.id===mov.ocupacaoOrigemId&&o.situacao==="ATIVA");if(!origem||!destino||!ocupacao)return{state,erro:"Vaga de origem, vaga de destino ou ocupação não foi encontrada."};
 const destinoOcupado=state.ocupacoes.some(o=>o.vagaId===destino.id&&o.situacao==="ATIVA"),destinoComprometido=state.comprometimentos.some(c=>c.vagaId===destino.id&&c.situacao==="ATIVO");if(origem.estado!=="OCUPADA")return{state,erro:"A vaga de origem não está ocupada."};if(destino.estado!=="DISPONIVEL"||destinoOcupado||destinoComprometido)return{state,erro:"A vaga de destino não está mais disponível."};if(origem.tipo!==destino.tipo||origem.cargo!==destino.cargo||origem.carreira!==destino.carreira)return{state,erro:"A vaga de destino não é compatível com cargo, carreira ou vínculo."};if(destino.situacaoLegal!=="REGULAR")return{state,erro:"A vaga de destino possui situação legal impeditiva."};
 const data=mov.dataEfeito??"2026-07-27",agora="2026-07-27 10:30",novaId=`OCU-${destino.id}-${ocupacao.vinculoId}`;
 const encerrada:OcupacaoVaga={...ocupacao,situacao:"ENCERRADA",encerradaEm:data,motivoEncerramento:"Remoção externa",eventos:[...ocupacao.eventos,{id:`EVT-${ocupacao.id}-${ocupacao.eventos.length+1}`,tipo:"ENCERRAMENTO",data,registradoEm:agora,descricao:`Ocupação encerrada por remoção externa para ${destino.id}.`,origem:"Movimentações Funcionais",processo:mov.processo,usuario:"Sistema"}]};
 const nova:OcupacaoVaga={...ocupacao,id:novaId,vagaId:destino.id,orgaoLotacao:mov.orgaoDestino,unidadeLotacao:mov.unidadeDestino,orgaoExercicio:mov.orgaoDestino,unidadeExercicio:mov.unidadeDestino,efetivoExercicioEm:data,situacao:"ATIVA",encerradaEm:undefined,motivoEncerramento:undefined,eventos:[{id:`EVT-${novaId}-001`,tipo:"REGISTRO",data,registradoEm:agora,descricao:`Ocupação criada por remoção externa da vaga ${origem.id}.`,origem:"Movimentações Funcionais",processo:mov.processo,usuario:"Sistema"}]};
 const hist=(vaga:Vaga,titulo:string,descricao:string,anterior:"OCUPADA"|"DISPONIVEL",posterior:"OCUPADA"|"DISPONIVEL")=>({id:`HIS-${vaga.id}-${vaga.historico.length+1}`,vagaId:vaga.id,ocorridoEm:agora,dataEfeito:data,tipo:"ALTERACAO_ESTADO" as const,titulo,descricao,estadoAnterior:anterior,estadoPosterior:posterior,origem:"Movimentações Funcionais",usuario:"Sistema",processo:mov.processo});
 const evento={id:`${mov.id}-H${mov.historico.length+1}`,data,registradoEm:agora,tipo:"EFETIVACAO_REMOCAO_EXTERNA",descricao:`Remoção externa efetivada de ${origem.id} para ${destino.id}.`,origem:"Movimentações Funcionais",usuario:"Sistema",situacaoAnterior:mov.situacao,situacaoPosterior:"EFETIVADA" as const};const atualizado:MovimentacaoFuncional={...mov,situacao:"EFETIVADA",detalhesRemocao:{...d,situacaoOperacional:"EFETIVADA",efetivadaEm:agora},atualizadoEm:agora,fases:mov.fases.map(f=>({...f,situacao:"CONCLUIDA",concluidaEm:agora})),historico:[...mov.historico,evento]};
 return{state:{...state,vagas:state.vagas.map(v=>v.id===origem.id?{...v,estado:"DISPONIVEL",historico:[...v.historico,hist(v,"Vaga liberada por remoção externa",`O vínculo ${ocupacao.vinculoId} passou para ${destino.id}.`,"OCUPADA","DISPONIVEL")]}:v.id===destino.id?{...v,estado:"OCUPADA",historico:[...v.historico,hist(v,"Vaga ocupada por remoção externa",`Recebeu o vínculo ${ocupacao.vinculoId}, proveniente de ${origem.id}.`,"DISPONIVEL","OCUPADA")]}:v),ocupacoes:[...state.ocupacoes.map(o=>o.id===ocupacao.id?encerrada:o),nova],movimentacoesFuncionais:state.movimentacoesFuncionais.map(m=>m.id===mov.id?atualizado:m)}};
}

