export type SituacaoLegalBase = "REGULAR" | "EM_EXTINCAO";
export interface ItemBaseTemporaria { id: string; nome: string; nomesOriginais: string[]; homologacao: "PENDENTE"; origem: "PLANILHA_JUNHO_2026"; situacaoLegal: SituacaoLegalBase; }
const criarCatalogo = (prefixo: string, nomes: string[], originais: Record<string, string[]> = {}, emExtincao = new Set<string>()): ItemBaseTemporaria[] => nomes.map((nome, indice) => ({ id: `${prefixo}-${String(indice + 1).padStart(3, "0")}`, nome, nomesOriginais: originais[nome] ?? [nome], homologacao: "PENDENTE", origem: "PLANILHA_JUNHO_2026", situacaoLegal: emExtincao.has(nome) ? "EM_EXTINCAO" : "REGULAR" }));

const nomesCarreiras = [
"Carreira da Polícia Judiciária Civil","Carreira de Analista Regulador","Carreira de Gestor Governamental","Carreira de Inspetor Regulador","Carreira de Procurador do Estado","Carreira dos Agentes de Administração Fazendária - AAF","Carreira dos Auditores da Auditoria Geral do Estado de Mato Grosso","Carreira dos Docentes da Educação Superior","Carreira dos Profissionais da Área da Metrologia Legal e Avaliação da Conformidade","Carreira dos Profissionais da Área Meio","Carreira dos Profissionais da Atividade Fundiária","Carreira dos Profissionais da Educação Básica","Carreira dos Profissionais da Educação Profissional e Tecnológica","Carreira dos Profissionais da Perícia Oficial e Identificação Técnica","Carreira dos Profissionais de Defesa Agropecuária e Florestal","Carreira dos Profissionais de Proteção ao Consumidor","Carreira dos Profissionais do Desenvolvimento Econômico e Social","Carreira dos Profissionais do Meio Ambiente","Carreira dos Profissionais do Serviço de Trânsito","Carreira dos Profissionais do Sistema Penitenciário","Carreira dos Profissionais do Sistema Socioeducativo","Carreira dos Profissionais do Sistema Único de Saúde - SUS","Efetivo da Polícia Militar do Estado de Mato Grosso","Efetivo do Corpo de Bombeiros Militar do Estado de Mato Grosso","Grupo Ocupacional TAF - Tributação, Arrecadação e Fiscalização","Profissionais da POLITEC","Profissionais da SEDUC","Profissionais Técnicos da Educação Superior","Quadro Administrativo da Procuradoria-Geral do Estado"
];
export const carreirasBaseTemporaria = criarCatalogo("CAR", nomesCarreiras, {
"Carreira dos Profissionais da Área da Metrologia Legal e Avaliação da Conformidade": ["Carreira dos Profissionais da Área da Metrologia Legal e Avaliação d a Conformidade"],
"Profissionais da POLITEC": ["Profissionais da POLITEC (Em Extinção)"],
"Profissionais da SEDUC": ["Profissionais da SEDUC (Em Extinção)"]
}, new Set(["Profissionais da POLITEC","Profissionais da SEDUC"]));
const nomesCargos = [
"Advogado do DETRAN-MT","Agente Arrecadador de Tributos Estaduais - AATE","Agente de Administração Fazendária - AAF","Agente de Fiscalização e Arrecadação de Tributos Estaduais - AFATE","Agente de Segurança Socioeducativo","Agente do Serviço de Trânsito","Agente Fiscal Estadual de Defesa Agropecuária e Florestal I","Agente Fiscal Estadual de Defesa Agropecuária e Florestal II","Agente Fiscal Metrológico","Agente Fundiário","Agente Universitário","Aluno Oficial","Aluno Soldado","Analista Administrativo","Analista Administrativo Estadual de Defesa Agropecuária e Florestal","Analista da Procuradoria-Geral","Analista de Meio Ambiente","Analista do Desenvolvimento Econômico e Social","Analista do Serviço de Trânsito","Analista do Sistema Socioeducativo","Analista Fiscal Metrológico","Analista Fundiário","Analista Regulador","Apoio Administrativo","Apoio Administrativo Educacional","Apoio da Procuradoria-Geral","Apoio do Desenvolvimento Econômico e Social","Aspirante","Assistente de Meio Ambiente","Assistente do Sistema Penitenciário","Assistente do Sistema Socioeducativo","Auditor do Estado","Auxiliar do Serviço de Trânsito","Auxiliar do Sistema Penitenciário","Auxiliar do Sistema Socioeducativo","Auxiliar Estadual de Defesa Agropecuária e Florestal","Auxiliar Fundiário","Auxiliar Universitário","Cabos e Soldados","Capitão","Conciliador de Defesa do Consumidor","Coronel","Delegado de Polícia","Escrivão de Polícia","Especialista da Educação","Fiscal de Defesa do Consumidor","Fiscal de Tributos Estaduais","Fiscal Estadual de Defesa Agropecuária e Florestal","Gestor Governamental","Inspetor Regulador","Investigador de Polícia","Papiloscopista","Perito Criminal II","Perito Oficial Criminal","Perito Oficial Médico-Legista","Perito Oficial Odonto-Legista","Policial Penal","Primeiro-Tenente e Segundo-Tenente","Primeiros, Segundos e Terceiros Sargentos","Procurador do Estado - Categoria 1","Procurador do Estado - Categoria 2","Procurador do Estado - Categoria 3","Procurador do Estado - Categoria Especial","Professor","Professor da Educação Profissional e Tecnológica","Professor da Educação Superior","Professor de Educação Básica","Profissional de Apoio em Serviços de Saúde do SUS","Profissional de Nível Superior do Sistema Penitenciário","Profissional Técnico de Nível Médio em Serviços de Saúde do SUS","Profissional Técnico de Nível Superior em Serviços de Saúde do SUS","Subtenente","Técnico Administrativo","Técnico Administrativo Educacional","Técnico da Procuradoria-Geral","Técnico de Apoio Educacional","Técnico de Meio Ambiente","Técnico de Necropsia","Técnico do Desenvolvimento Econômico e Social","Técnico Fiscal Metrológico","Técnico Universitário","Tenente-Coronel e Major"
];
const cargosEmExtincao = new Set(["Agente de Administração Fazendária - AAF","Agente Fiscal Estadual de Defesa Agropecuária e Florestal II","Apoio Administrativo","Apoio da Procuradoria-Geral","Apoio do Desenvolvimento Econômico e Social","Auxiliar Estadual de Defesa Agropecuária e Florestal","Especialista da Educação","Perito Criminal II","Professor"]);
const cargosOriginais: Record<string, string[]> = {
"Analista do Sistema Socioeducativo": ["Analista do Sistema Socieducativo"],
"Primeiro-Tenente e Segundo-Tenente": ["Primeiro e Segundo Tenente","Primeiro-Tenente e Segundo-Tenente"],
"Primeiros, Segundos e Terceiros Sargentos": ["Primeiro, Segundo e Terceiro Sargento","Primeiros, Segundos e Terceiros Sargentos"],
"Subtenente": ["Subtenente","Subtenentes"],
"Tenente-Coronel e Major": ["Tenente Coronel e Major","Tenente-Coronel e Major"]
};
for (const nome of cargosEmExtincao) cargosOriginais[nome] = [`${nome} (Em Extinção)`];
export const cargosBaseTemporaria = criarCatalogo("CGO", nomesCargos, cargosOriginais, cargosEmExtincao);

const nomesOrgaos = ["AGER","CASA CIVIL","CASA MILITAR","CBM","CGE","DETRAN","FAPEMAT","FUNAC","GCOM","GOVERNADORIA","INDEA","INTERMAT","IPEM","JUCEMAT","MT SAÚDE","MTPREV","PGE","PJC","PM","POLITEC","SEAF","SECEL","SECID","SECITECI","SECOM","SEDEC","SEDUC","SEFAZ","SEJUDH","SEJUS","SEMA","SEPLAG","SEPLAN","SES","SESP","SETASC","SINFRA","UNEMAT","VICE-GOVERNADORIA"];
export const orgaosBaseTemporaria = criarCatalogo("ORG", nomesOrgaos);
export const especialidadesBaseTemporaria: ItemBaseTemporaria[] = [];