import { useMemo, useState, type FormEvent } from "react";
import { avancarFase, cancelarComprometimento, concluirEventoDefinitivo, criarFasesComprometimento } from "./comprometimentos";
import { comprometimentosVagasMock } from "./comprometimentosMock";
import { vagasIndividualizadasMock } from "./mockData";
import type { ComprometimentoVaga, NaturezaComprometimento, Vaga } from "./types";
import "./comprometimentosVagas.css";

const naturezaLabel = { OCUPACAO: "Processo de ocupação", DISPONIBILIZACAO: "Processo de disponibilização" } as const;
const estadoLabel = { DISPONIVEL: "Disponível", OCUPADA: "Ocupada" } as const;

export function ComprometimentosVagasContent() {
  const [vagas, setVagas] = useState(vagasIndividualizadasMock);
  const [processos, setProcessos] = useState(comprometimentosVagasMock);
  const [selecionado, setSelecionado] = useState<ComprometimentoVaga | null>(null);
  const [novo, setNovo] = useState(false);
  const [filtro, setFiltro] = useState("");
  const exibidos = useMemo(() => processos.filter((item) => !filtro || item.natureza === filtro || item.situacao === filtro), [processos, filtro]);
  const ativos = processos.filter((item) => item.situacao === "ATIVO");
  const atualizar = (processo: ComprometimentoVaga) => { setProcessos((itens) => itens.map((item) => item.id === processo.id ? processo : item)); setSelecionado(processo); };
  const concluir = (processo: ComprometimentoVaga) => { const vaga = vagas.find((item) => item.id === processo.vagaId)!; const resultado = concluirEventoDefinitivo(vaga, processo); setVagas((itens) => itens.map((item) => item.id === vaga.id ? resultado.vaga : item)); atualizar(resultado.comprometimento); };
  const criar = (processo: ComprometimentoVaga) => { setProcessos((itens) => [processo, ...itens]); setNovo(false); setSelecionado(processo); };
  return <div className="prototype-commit-page"><header className="prototype-commit-header"><div><span>Controle de Vagas</span><h1>Comprometimentos e Flags</h1><p>Processos em andamento sobre vagas, sem antecipar a ocupação ou a disponibilização.</p></div><button onClick={() => setNovo(true)}><i className="pi pi-plus" /> Novo processo</button></header>
    <div className="prototype-commit-rule"><i className="pi pi-shield" /><div><strong>O comprometimento não é um terceiro estado da vaga</strong><span>A vaga mantém seu estado atual. A mudança ocorre apenas quando o evento definitivo for confirmado.</span></div></div>
    <section className="prototype-commit-kpis"><article><span>Processos ativos</span><strong>{ativos.length}</strong></article><article className="occupation"><span>Para ocupação</span><strong>{ativos.filter((item) => item.natureza === "OCUPACAO").length}</strong></article><article className="release"><span>Para disponibilização</span><strong>{ativos.filter((item) => item.natureza === "DISPONIBILIZACAO").length}</strong></article><article><span>Fases em andamento</span><strong>{ativos.flatMap((item) => item.fases).filter((fase) => fase.situacao === "EM_ANDAMENTO").length}</strong></article></section>
    <section className="prototype-commit-card"><header><div><h2>Processos sobre vagas</h2><p>Origem, processo administrativo, datas e progresso de cada comprometimento.</p></div><select value={filtro} onChange={(e) => setFiltro(e.target.value)}><option value="">Todos</option><option value="OCUPACAO">Ocupação</option><option value="DISPONIBILIZACAO">Disponibilização</option><option value="ATIVO">Ativos</option><option value="CONCLUIDO">Concluídos</option><option value="CANCELADO">Cancelados</option></select></header><div className="prototype-commit-table"><table><thead><tr><th>Processo</th><th>Vaga</th><th>Natureza</th><th>Estado preservado</th><th>Fase atual</th><th>Progresso</th><th>Previsão</th><th /></tr></thead><tbody>{exibidos.map((processo) => { const vaga = vagas.find((item) => item.id === processo.vagaId)!; const atual = processo.fases.find((fase) => fase.situacao === "EM_ANDAMENTO"); const concluidas = processo.fases.filter((fase) => fase.situacao === "CONCLUIDA").length; return <tr key={processo.id}><td><strong>{processo.id}</strong><small>{processo.processo}</small></td><td><strong>{vaga.id}</strong><small>{vaga.cargo} • {vaga.orgaoTitular}</small></td><td><span className={`prototype-commit-nature ${processo.natureza.toLowerCase()}`}>{naturezaLabel[processo.natureza]}</span></td><td><span className={`prototype-commit-state ${vaga.estado.toLowerCase()}`}>{estadoLabel[vaga.estado]}</span><small>não alterado</small></td><td>{atual?.nome ?? processo.eventoDefinitivo ?? processo.situacao}</td><td><div className="prototype-commit-progress"><span><i style={{ width: `${(concluidas / processo.fases.length) * 100}%` }} /></span><small>{concluidas}/{processo.fases.length}</small></div></td><td>{processo.dataEfeitoPrevista ?? "Não informada"}</td><td><button onClick={() => setSelecionado(processo)}><i className="pi pi-eye" /></button></td></tr>; })}</tbody></table></div></section>
    {selecionado && <Detalhe processo={selecionado} vaga={vagas.find((item) => item.id === selecionado.vagaId)!} onClose={() => setSelecionado(null)} onAdvance={() => atualizar(avancarFase(selecionado))} onFinish={() => concluir(selecionado)} onCancel={() => atualizar(cancelarComprometimento(selecionado))} />}
    {novo && <NovoProcesso vagas={vagas} onClose={() => setNovo(false)} onCreate={criar} />}
  </div>;
}

function Detalhe({ processo, vaga, onClose, onAdvance, onFinish, onCancel }: { processo:ComprometimentoVaga; vaga:Vaga; onClose:()=>void; onAdvance:()=>void; onFinish:()=>void; onCancel:()=>void }) {
 const todasConcluidas = processo.fases.every((fase) => fase.situacao === "CONCLUIDA");
 return <div className="prototype-commit-backdrop" onMouseDown={onClose}><section className="prototype-commit-modal" onMouseDown={(e) => e.stopPropagation()}><header><div><span>{naturezaLabel[processo.natureza]}</span><h2>{processo.id}</h2><p>{processo.processo} • origem: {processo.origem}</p></div><button onClick={onClose}><i className="pi pi-times" /></button></header><div className="prototype-commit-preserved"><i className="pi pi-lock" /><div><strong>{vaga.id} permanece {estadoLabel[vaga.estado].toLowerCase()}</strong><span>O estado só será alterado pela confirmação do evento definitivo.</span></div></div><dl><div><dt>Motivo</dt><dd>{processo.motivo}</dd></div><div><dt>Criado em</dt><dd>{processo.criadoEm}</dd></div><div><dt>Data prevista</dt><dd>{processo.dataEfeitoPrevista ?? "Não informada"}</dd></div><div><dt>Situação</dt><dd>{processo.situacao}</dd></div></dl><section className="prototype-commit-timeline"><h3>Histórico das fases</h3><ol>{processo.fases.map((fase) => <li key={fase.id} className={fase.situacao.toLowerCase()}><i className={fase.situacao === "CONCLUIDA" ? "pi pi-check" : fase.situacao === "EM_ANDAMENTO" ? "pi pi-clock" : fase.situacao === "CANCELADA" ? "pi pi-times" : ""} /><div><strong>{fase.ordem}. {fase.nome}</strong><span>{fase.situacao.replaceAll("_", " ")}</span><small>{fase.iniciadaEm ? `Início: ${fase.iniciadaEm}` : "Ainda não iniciada"}{fase.concluidaEm ? ` • Conclusão: ${fase.concluidaEm}` : ""}</small><small>{fase.origem} • {fase.processo}</small></div></li>)}</ol></section><footer>{processo.situacao === "ATIVO" && <><button className="cancel" onClick={onCancel}>Cancelar processo</button><button onClick={onAdvance} disabled={todasConcluidas}>Concluir fase atual</button><button className="finish" onClick={onFinish} disabled={!todasConcluidas} title={!todasConcluidas ? "Conclua todas as fases antes do evento definitivo" : "Confirmar evento definitivo"}><i className="pi pi-check-circle" /> Confirmar evento definitivo</button></>} {processo.situacao !== "ATIVO" && <button onClick={onClose}>Fechar</button>}</footer></section></div>;
}

function NovoProcesso({ vagas, onClose, onCreate }: { vagas:Vaga[]; onClose:()=>void; onCreate:(processo:ComprometimentoVaga)=>void }) {
 const [natureza,setNatureza]=useState<NaturezaComprometimento>("OCUPACAO"); const [vagaId,setVagaId]=useState(""); const [origem,setOrigem]=useState("Ingresso do Servidor"); const [processo,setProcesso]=useState(""); const [previsao,setPrevisao]=useState(""); const [motivo,setMotivo]=useState(""); const candidatas=vagas.filter((vaga)=>natureza==="OCUPACAO"?vaga.estado==="DISPONIVEL":vaga.estado==="OCUPADA");
 const submit=(e:FormEvent)=>{e.preventDefault();if(!vagaId||!processo||!motivo)return;const id=`CPR-2026-${String(Date.now()).slice(-5)}`;onCreate({id,vagaId,natureza,situacao:"ATIVO",origem,processo,criadoEm:"16/07/2026 10:00",dataEfeitoPrevista:previsao||undefined,motivo,fases:criarFasesComprometimento(natureza,processo,origem,0)})};
 return <div className="prototype-commit-backdrop" onMouseDown={onClose}><form className="prototype-commit-modal new" onSubmit={submit} onMouseDown={(e)=>e.stopPropagation()}><header><div><span>Novo comprometimento</span><h2>Criar processo sobre vaga</h2></div><button type="button" onClick={onClose}><i className="pi pi-times" /></button></header><div className="prototype-commit-form"><label><span>Natureza *</span><select value={natureza} onChange={(e)=>{setNatureza(e.target.value as NaturezaComprometimento);setVagaId("")}}><option value="OCUPACAO">Processo de ocupação</option><option value="DISPONIBILIZACAO">Processo de disponibilização</option></select></label><label><span>Vaga compatível *</span><select value={vagaId} onChange={(e)=>setVagaId(e.target.value)}><option value="">Selecione</option>{candidatas.slice(0,80).map((vaga)=><option key={vaga.id} value={vaga.id}>{vaga.id} — {vaga.cargo}</option>)}</select><small>{natureza==="OCUPACAO"?"Somente vagas disponíveis":"Somente vagas ocupadas"}</small></label><label><span>Origem *</span><select value={origem} onChange={(e)=>setOrigem(e.target.value)}><option>Ingresso do Servidor</option><option>Vida Funcional</option><option>Controle de Vagas</option><option>Decisão Judicial</option></select></label><label><span>Processo administrativo *</span><input value={processo} onChange={(e)=>setProcesso(e.target.value)} placeholder="ÓRGÃO-PRO-AAAA/NNNNN" /></label><label><span>Data prevista do evento</span><input type="date" value={previsao} onChange={(e)=>setPrevisao(e.target.value)} /></label><label className="full"><span>Motivo *</span><textarea rows={3} value={motivo} onChange={(e)=>setMotivo(e.target.value)} /></label></div><div className="prototype-commit-phase-preview"><strong>Fases criadas automaticamente</strong><span>{criarFasesComprometimento(natureza,"PROCESSO",origem).map((fase)=>fase.nome).join(" → ")}</span></div><footer><button type="button" className="cancel" onClick={onClose}>Cancelar</button><button className="finish" type="submit">Criar processo</button></footer></form></div>;
}
