import { useSyncExternalStore } from "react";
import { cessoesMock } from "./cessoesMock";
import { comprometimentosVagasMock } from "./comprometimentosMock";
import { movimentosVagasIndividuaisMock } from "./distribuicaoIndividualMock";
import { movimentacoesFuncionaisMock } from "./movimentacoesFuncionaisMock";
import { excecoesJudiciaisMock } from "./excecoesJudiciaisMock";
import { construirHistoricoTemporal } from "./historicoTemporal";
import { pendenciasRegrasMock, quadrosAutorizadosMock, regrasControleVagasMock, vagasIndividualizadasMock } from "./mockData";
import { ocupacoesVagasMock } from "./ocupacoesMock";
import { fatoresProjecaoMock, metodologiasProjecaoMock, taxasEvasaoMock } from "./projecoesMock";
import { encerrarOcupacao as encerrarOcupacaoEntidades } from "./ocupacoes";
import { reconciliarQuadroAposVacanciaEmExtincao } from "./quadroLegalUtils";
import type { CessaoFuncional, ComprometimentoVaga, ExcecaoJudicialVaga, FatorProjecaoVagas, MetodologiaProjecao, MovimentacaoFuncional, MovimentoVagaIndividual, OcupacaoVaga, QuadroAutorizadoRow, RegraEvento, TaxaEvasaoHistorica, Vaga } from "./types";
export interface ControleVagasState{quadros:QuadroAutorizadoRow[];vagas:Vaga[];comprometimentos:ComprometimentoVaga[];ocupacoes:OcupacaoVaga[];cessoes:CessaoFuncional[];movimentacoesFuncionais:MovimentacaoFuncional[];movimentos:MovimentoVagaIndividual[];excecoesJudiciais:ExcecaoJudicialVaga[];regras:RegraEvento[];pendenciasRegras:string[];fatoresProjecao:FatorProjecaoVagas[];metodologias:MetodologiaProjecao[];taxasEvasao:TaxaEvasaoHistorica[]}
const ocupacoesIniciais=ocupacoesVagasMock.map((ocupacao)=>{const cessao=cessoesMock.find((item)=>item.ocupacaoId===ocupacao.id&&item.situacao==="ATIVA");return cessao?{...ocupacao,orgaoExercicio:cessao.orgaoCessionario}:ocupacao});
let state:ControleVagasState={quadros:[...quadrosAutorizadosMock],vagas:[...vagasIndividualizadasMock],comprometimentos:[...comprometimentosVagasMock],ocupacoes:[...ocupacoesIniciais],cessoes:[...cessoesMock],movimentacoesFuncionais:[...movimentacoesFuncionaisMock],movimentos:[...movimentosVagasIndividuaisMock],excecoesJudiciais:[...excecoesJudiciaisMock],regras:[...regrasControleVagasMock],pendenciasRegras:[...pendenciasRegrasMock],fatoresProjecao:[...fatoresProjecaoMock],metodologias:[...metodologiasProjecaoMock],taxasEvasao:[...taxasEvasaoMock]};const listeners=new Set<()=>void>();const emitir=()=>listeners.forEach((l)=>l());
export const controleVagasStore={getState:()=>state,subscribe:(listener:()=>void)=>{listeners.add(listener);return()=>listeners.delete(listener)},update:(updater:(atual:ControleVagasState)=>ControleVagasState)=>{state=updater(state);emitir()},set<K extends keyof ControleVagasState>(campo:K,valor:ControleVagasState[K]|((atual:ControleVagasState[K])=>ControleVagasState[K])){state={...state,[campo]:typeof valor==="function"?(valor as (a:ControleVagasState[K])=>ControleVagasState[K])(state[campo]):valor};emitir()},encerrarOcupacao(vagaId:string,ocupacaoId:string,data:string,motivo:string,processo?:string){const vaga=state.vagas.find((item)=>item.id===vagaId);const ocupacao=state.ocupacoes.find((item)=>item.id===ocupacaoId&&item.vagaId===vagaId&&item.situacao==="ATIVA");if(!vaga||!ocupacao)return false;const encerramento=encerrarOcupacaoEntidades(vaga,ocupacao,data,motivo,processo);const vagasAtualizadas=state.vagas.map((item)=>item.id===vagaId?encerramento.vaga:item);state={...state,vagas:vagasAtualizadas,ocupacoes:state.ocupacoes.map((item)=>item.id===ocupacaoId?encerramento.ocupacao:item),quadros:state.quadros.map((quadro)=>reconciliarQuadroAposVacanciaEmExtincao(quadro,vagasAtualizadas,data))};emitir();return true},historico:()=>construirHistoricoTemporal(state)};
export const useControleVagasStore=()=>useSyncExternalStore(controleVagasStore.subscribe,controleVagasStore.getState,controleVagasStore.getState);
