import type { SpecificationMetadata } from "../shared/visualizationModes";

const allFilters =
  "Orgao titular, orgao de distribuicao, tipo de quadro, carreira, cargo e situacao legal.";
const story = "US Controle de Vagas - Dashboard Gerencial";
const spec = (
  id: string,
  title: string,
  description: string,
  businessRule: string,
  source: string,
  dataType: string,
  component: string,
  route?: string,
  behavior?: string,
  filters = allFilters,
): SpecificationMetadata => ({
  id,
  title,
  description,
  businessRule,
  source,
  dataType,
  component,
  filters,
  status: "CONFIRMADO",
  route,
  behavior,
  userStory: story,
});

export const dashboardScreenSpecification = spec(
  "CV-DASH",
  "Dashboard Gerencial",
  "Consolidar a posicao legal, distributiva e ocupacional das vagas para apoiar a gestao do quadro.",
  "Considerar somente as fontes do MVP: Quadro Autorizado, Distribuicao e Vagas Individualizadas.",
  "Quadro Autorizado, Vagas Individualizadas, Distribuicao, ocupacoes ativas e comprometimentos.",
  "DashboardViewModel",
  "Pagina React + seletores derivados do store",
  "/prototipos/sigep/controle-vagas/dashboard",
  "Recalcula a visao quando filtros ou dados do store forem alterados.",
);

export const dashboardFilterSpecifications: Record<string, SpecificationMetadata> = {
  "Orgao titular": spec(
    "CV-DASH-FLT-003",
    "Orgao titular",
    "Exibir vagas cujo vinculo juridico de titularidade pertence ao orgao selecionado.",
    "Titularidade nao e alterada pela distribuicao administrativa, salvo alteracao legal expressa.",
    "Vaga.orgaoTitular.",
    "string | vazio",
    "select simples",
  ),
  "Orgao de distribuicao": spec(
    "CV-DASH-FLT-004",
    "Orgao de distribuicao",
    "Restringir a visao as vagas administrativamente destinadas ao orgao selecionado.",
    "A posicao deve ser reconstruida pelo ultimo movimento de distribuicao com efeito ate a data de referencia.",
    "Movimentos de Distribuicao e posicao temporal da Vaga.",
    "string | PENDENTE_ATO | vazio",
    "select simples",
  ),
  Tipo: spec(
    "CV-DASH-FLT-006",
    "Tipo de quadro",
    "Separar cargos efetivos e comissionados.",
    "Temporarios e vinculos sem limite legal nao integram este Dashboard.",
    "Vaga.tipo e QuadroAutorizado.tipoQuadro.",
    "'' | EFETIVO | COMISSIONADO",
    "select simples",
  ),
  Carreira: spec(
    "CV-DASH-FLT-007",
    "Carreira",
    "Restringir a posicao a uma carreira.",
    "Usar a carreira registrada na vaga e em sua origem legal.",
    "Vaga.carreira.",
    "string | vazio",
    "select simples",
  ),
  Cargo: spec(
    "CV-DASH-FLT-008",
    "Cargo",
    "Restringir indicadores e grupos ao cargo selecionado.",
    "Quadros diferentes do mesmo cargo permanecem separados no quadro estrategico.",
    "Vaga.cargo.",
    "string | vazio",
    "select simples",
  ),
  "Situacao legal": spec(
    "CV-DASH-FLT-009",
    "Situacao legal",
    "Consultar vagas segundo sua condicao juridica na data de referencia.",
    "Regular, em extincao, extinta e em transformacao sao situacoes da vaga.",
    "Vaga.situacaoLegal e historico legal.",
    "'' | REGULAR | EM_EXTINCAO | EXTINTA | EM_TRANSFORMACAO",
    "select simples",
  ),
  "Indicadores exibidos": spec(
    "CV-DASH-FLT-011",
    "Indicadores exibidos",
    "Permitir que o usuario escolha quais cartoes gerenciais aparecem na tela ou exportacao.",
    "A ocultacao e apenas visual e nao altera calculos, filtros, dados ou valores dos demais blocos.",
    "Preferencia local da sessao do usuario.",
    "Record<IndicadorDashboardId, boolean>",
    "grupo de switches",
  ),
  Limpar: spec(
    "CV-DASH-FLT-012",
    "Limpar filtros",
    "Restaurar os filtros de negocio para os valores iniciais.",
    "Restaurar a data padrao e remover orgaos, tipo, carreira, cargo e situacao legal.",
    "Constante filtrosIniciais.",
    "command",
    "botao",
  ),
};

export const dashboardBlockSpecifications = {
  filters: spec(
    "CV-DASH-FLT-001",
    "Filtros da consulta",
    "Abrir ou recolher os criterios que restringem toda a posicao gerencial.",
    "Todos os KPIs, composicao, alertas, quadro estrategico e distribuicoes recentes devem usar a mesma instancia de DashboardFiltros.",
    "Estado local DashboardFiltros e listas derivadas do store.",
    "DashboardFiltros",
    "Accordion + formulario",
  ),
  composition: spec(
    "CV-DASH-BLC-001",
    "Composicao do quadro",
    "Comparar o limite legal com ocupadas, disponiveis livres, disponiveis comprometidas e ocupadas em disponibilizacao.",
    "Comprometimento nao altera o estado definitivo antes do evento de conclusao.",
    "Vagas individualizadas, ocupacoes ativas e comprometimentos ativos.",
    "ResumoDashboard",
    "grafico de rosca + legenda",
  ),
  alerts: spec(
    "CV-DASH-BLC-002",
    "Alertas gerenciais",
    "Destacar situacoes operacionais ou juridicas que exigem analise da gestao de vagas.",
    "Cada alerta deve abrir os registros que formam seu numero.",
    "Quadros sem saldo livre, excecoes judiciais e vagas em extincao.",
    "AlertaGerencial[]",
    "lista de links",
  ),
  table: spec(
    "CV-DASH-TBL-001",
    "Quadro estrategico por autorizacao, cargo e orgao",
    "Apresentar a memoria consolidada utilizada para priorizar analises do quadro.",
    "Agrupar pela origem legal, cargo e orgao titular; nao combinar Quadros Autorizados distintos.",
    "Quadro Autorizado, vagas, ocupacoes, comprometimentos, excecoes judiciais e distribuicao.",
    "DashboardGrupo[]",
    "tabela gerencial",
  ),
  recent: spec(
    "CV-DASH-BLC-005",
    "Distribuicoes recentes",
    "Exibir os ultimos movimentos administrativos de distribuicao e redistribuicao.",
    "Ordenar pela data/hora de registro, limitar aos cinco mais recentes e sinalizar movimento retroativo.",
    "MovimentoVagaIndividual do tipo DISTRIBUICAO ou REDISTRIBUICAO.",
    "MovimentoVagaIndividual[]",
    "lista temporal",
    "/prototipos/sigep/controle-vagas/distribuicao",
  ),
} satisfies Record<string, SpecificationMetadata>;

export const dashboardAlertSpecifications: Record<string, SpecificationMetadata> = {
  "Quadros sem saldo livre": spec(
    "CV-DASH-ALT-001",
    "Quadros sem saldo livre",
    "Identificar grupos legais sem vaga disponivel livre para provimento imediato.",
    "Contar grupos com disponiveisLivres igual a zero; vagas comprometidas nao sao saldo livre.",
    "DashboardGrupo.disponiveisLivres.",
    "integer",
    "alerta navegavel",
    "/prototipos/sigep/controle-vagas/quadro-autorizado",
  ),
  "Ocupacoes judiciais extraquadro": spec(
    "CV-DASH-ALT-002",
    "Ocupacoes judiciais extraquadro",
    "Evidenciar ocupacoes excepcionais determinadas judicialmente que nao ampliam automaticamente o limite legal.",
    "Contabilizar excecoes judiciais ativas separadamente das vagas legais regulares.",
    "ExcecaoJudicialVaga e ocupacoes relacionadas.",
    "integer",
    "alerta navegavel",
    "/prototipos/sigep/controle-vagas/vagas?legal=DECISAO_JUDICIAL",
  ),
  "Vagas em extincao": spec(
    "CV-DASH-ALT-003",
    "Vagas em extincao",
    "Indicar vagas que permanecem no historico ou ocupadas, mas nao podem receber nova ocupacao.",
    "Contar situacao EM_EXTINCAO na data; quando ocorrer vacancia definitiva, aplicar a extincao conforme o ato legal.",
    "Vaga.situacaoLegal e historico legal.",
    "integer",
    "alerta navegavel",
    "/prototipos/sigep/controle-vagas/vagas?legal=EM_EXTINCAO",
  ),
};

export const dashboardKpiSpecifications: Record<string, SpecificationMetadata> = {
  "Cargos legais": spec(
    "CV-DASH-KPI-001",
    "Cargos legais",
    "Quantidade de cargos distintos com vagas legais validas na posicao.",
    "Contar nomes de cargo distintos entre vagas nao extintas apos aplicacao dos filtros.",
    "Vaga.cargo vinculada ao Quadro Autorizado.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/quadro-autorizado",
  ),
  "Quadros vigentes": spec(
    "CV-DASH-KPI-002",
    "Quadros vigentes",
    "Quantidade de origens legais distintas presentes na posicao filtrada.",
    "Contar codigos de Quadro Autorizado distintos com ao menos uma vaga legal valida na data.",
    "Vaga.quadroCodigo e vigencia do Quadro Autorizado.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/quadro-autorizado",
  ),
  "Vagas legais": spec(
    "CV-DASH-KPI-003",
    "Vagas legais",
    "Total de vagas que compoem o limite legal vigente.",
    "Contar vagas individualizadas validas e excluir as extintas na data de referencia.",
    "Vagas Individualizadas e historico da situacao legal.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas",
  ),
  Ocupadas: spec(
    "CV-DASH-KPI-004",
    "Ocupadas",
    "Vagas com ocupacao nominal ativa na data de referencia.",
    "Cada vinculo ativo ocupa uma unica vaga.",
    "Vaga.estado e OcupacaoVaga ativa.",
    "integer + percentual",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?estado=OCUPADA",
  ),
  Disponiveis: spec(
    "CV-DASH-KPI-005",
    "Disponiveis",
    "Vagas sem ocupacao ativa na posicao consultada.",
    "Inclui disponiveis livres e comprometidas para ocupacao; extintas nao entram.",
    "Vaga.estado e comprometimentos ativos.",
    "integer + subtotal",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?estado=DISPONIVEL",
  ),
  Comprometidas: spec(
    "CV-DASH-KPI-006",
    "Comprometidas para ocupacao",
    "Vagas disponiveis reservadas por processo de ingresso ainda nao concluido.",
    "Nao alterar o estado para ocupada ate posse/exercicio ou evento definitivo.",
    "ComprometimentoVaga de natureza OCUPACAO.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?comprometimento=OCUPACAO",
  ),
  "Em disponibilizacao": spec(
    "CV-DASH-KPI-007",
    "Em disponibilizacao",
    "Vagas ainda ocupadas vinculadas a processo que podera libera-las.",
    "Permanecem ocupadas ate evento definitivo; nao sao saldo disponivel atual.",
    "ComprometimentoVaga de natureza DISPONIBILIZACAO.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?comprometimento=DISPONIBILIZACAO",
  ),
  "Pendente de ato de distribuicao": spec(
    "CV-DASH-KPI-008",
    "Pendente de ato de distribuicao",
    "Vagas cuja origem legal deixou a destinacao para ato administrativo posterior.",
    "Pendencia de ato e condicao distributiva, nao orgao nem banco central.",
    "Quadro Autorizado, Vaga e posicao reconstruida pelos movimentos de Distribuicao.",
    "integer + subtotal",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/distribuicao",
  ),
  "Situacoes legais especiais": spec(
    "CV-DASH-KPI-009",
    "Situacoes legais especiais",
    "Vagas com situacao diferente de Regular.",
    "Contar em extincao, extintas na posicao historica aplicavel e em transformacao.",
    "Vaga.situacaoLegal e historico legal.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?legal=ESPECIAL",
  ),
};

export const dashboardBusinessItems = [
  ...Object.values(dashboardFilterSpecifications),
  ...Object.values(dashboardBlockSpecifications),
  ...Object.values(dashboardAlertSpecifications),
  ...Object.values(dashboardKpiSpecifications),
];
