import type { SpecificationMetadata } from "../shared/visualizationModes";

const allFilters =
  "Órgão, tipo de quadro, carreira, cargo e situação legal.";
const story = "US Controle de Vagas - Dashboard Gerencial";
const spec = (
  id: string,
  title: string,
  description: string,
  businessRule: string,
  source: string,
  dataType: string,
  component: string,
  route?: string,
  behavior?: string,
  filters = allFilters,
): SpecificationMetadata => ({
  id,
  title,
  description,
  businessRule,
  source,
  dataType,
  component,
  filters,
  status: "CONFIRMADO",
  route,
  behavior,
  userStory: story,
});

export const dashboardScreenSpecification = spec(
  "CV-DASH",
  "Dashboard Gerencial",
  "Consolidar a posicao legal, distributiva e ocupacional das vagas para apoiar a gestao do quadro.",
  "Considerar somente as fontes do MVP: Quadro Autorizado, Distribuicao e Vagas Individualizadas.",
  "Quadro Autorizado, Vagas Individualizadas, Distribuicao, ocupacoes ativas e comprometimentos.",
  "DashboardViewModel",
  "Pagina React + seletores derivados do store",
  "/prototipos/sigep/controle-vagas/dashboard",
  "Recalcula a visao quando filtros ou dados do store forem alterados.",
);

export const dashboardFilterSpecifications: Record<string, SpecificationMetadata> = {
  "Órgão": spec(
    "CV-DASH-FLT-003",
    "Órgão",
    "Exibir as vagas atualmente distribuídas ao órgão selecionado.",
    "Considerar o último ato de distribuição ou redistribuição vigente; vagas pendentes de ato não pertencem a um órgão até sua distribuição formal.",
    "Base temporária de órgãos e posição atual reconstruída pelos movimentos de distribuição da vaga.",
    "string[]",
    "MultiSelect pesquisável",
  ),  Tipo: spec(
    "CV-DASH-FLT-006",
    "Tipo de quadro",
    "Separar cargos efetivos e comissionados.",
    "Temporarios e vinculos sem limite legal nao integram este Dashboard.",
    "Vaga.tipo e QuadroAutorizado.tipoQuadro.",
    "TipoVagaLegal[]",
    "MultiSelect",
  ),
  Carreira: spec(
    "CV-DASH-FLT-007",
    "Carreira",
    "Restringir a posicao a uma carreira.",
    "Usar a carreira registrada na vaga e em sua origem legal.",
    "Vaga.carreira.",
    "string[]",
    "MultiSelect pesquisável",
  ),
  Cargo: spec(
    "CV-DASH-FLT-008",
    "Cargo",
    "Restringir indicadores e grupos ao cargo selecionado.",
    "Quadros diferentes do mesmo cargo permanecem separados na situação das vagas por quadro e órgão.",
    "Vaga.cargo.",
    "string[]",
    "MultiSelect pesquisável",
  ),
  "Situacao legal": spec(
    "CV-DASH-FLT-009",
    "Situacao legal",
    "Consultar vagas segundo sua condicao juridica na data de referencia.",
    "Regular, em extincao, extinta e em transformacao sao situacoes da vaga.",
    "Vaga.situacaoLegal e historico legal.",
    "SituacaoLegalVaga[]",
    "MultiSelect",
  ),
  "Indicadores exibidos": spec(
    "CV-DASH-FLT-011",
    "Indicadores exibidos",
    "Permitir que o usuario escolha quais cartoes gerenciais aparecem na tela ou exportacao.",
    "A ocultacao e apenas visual e nao altera calculos, filtros, dados ou valores dos demais blocos.",
    "Preferencia local da sessao do usuario.",
    "Record<IndicadorDashboardId, boolean>",
    "grupo de switches",
  ),
  Limpar: spec(
    "CV-DASH-FLT-012",
    "Limpar filtros",
    "Restaurar os filtros de negocio para os valores iniciais.",
    "Restaurar a data padrao e remover orgaos, tipo, carreira, cargo e situacao legal.",
    "Constante filtrosIniciais.",
    "command",
    "botao",
  ),
};

export const dashboardBlockSpecifications = {
  filters: spec(
    "CV-DASH-FLT-001",
    "Filtros da consulta",
    "Abrir ou recolher os criterios que restringem toda a posicao gerencial.",
    "Todos os KPIs, composição, alertas, situação das vagas e distribuições recentes devem usar a mesma instância de DashboardFiltros.",
    "Estado local DashboardFiltros e listas derivadas do store.",
    "DashboardFiltros",
    "Accordion + formulario",
  ),
  composition: spec(
    "CV-DASH-BLC-001",
    "Composicao do quadro",
    "Comparar o limite legal com ocupadas, disponiveis livres, disponiveis comprometidas e ocupadas em disponibilizacao.",
    "Comprometimento nao altera o estado definitivo antes do evento de conclusao.",
    "Vagas individualizadas, ocupacoes ativas e comprometimentos ativos.",
    "ResumoDashboard",
    "grafico de rosca + legenda",
  ),
  alerts: spec(
    "CV-DASH-BLC-002",
    "Alertas gerenciais",
    "Destacar situacoes operacionais ou juridicas que exigem analise da gestao de vagas.",
    "Cada alerta deve abrir os registros que formam seu numero.",
    "Quadros sem saldo livre, excecoes judiciais e vagas em extincao.",
    "AlertaGerencial[]",
    "lista de links",
  ),
  table: spec(
    "CV-DASH-TBL-001",
    "Situação das vagas por quadro e órgão",
    "Apresentar ocupação e saldo disponível por Quadro Autorizado, cargo e órgão.",
    "Agrupar por Quadro Autorizado, cargo e órgão; ordenar primeiro os grupos sem vagas livres.",
    "Quadro Autorizado, vagas, ocupações, comprometimentos e distribuição.",
    "DashboardGrupo[]",
    "tabela gerencial",
  ),
  recent: spec(
    "CV-DASH-BLC-005",
    "Distribuicoes recentes",
    "Exibir os ultimos movimentos administrativos de distribuicao e redistribuicao.",
    "Ordenar pela data/hora de registro, limitar aos cinco mais recentes e sinalizar movimento retroativo.",
    "MovimentoVagaIndividual do tipo DISTRIBUICAO ou REDISTRIBUICAO.",
    "MovimentoVagaIndividual[]",
    "lista temporal",
  ),
} satisfies Record<string, SpecificationMetadata>;

export const dashboardAlertSpecifications: Record<string, SpecificationMetadata> = {
  "Quadros sem vagas livres": spec(
    "CV-DASH-ALT-001",
    "Quadros sem vagas livres",
    "Identificar Quadros Autorizados sem vaga livre para novo ingresso.",
    "Consolidar os órgãos de cada quadro e contar o quadro uma única vez quando a soma de vagas livres for zero.",
    "DashboardGrupo agrupado por quadroCodigo.",
    "integer",
    "alerta navegável",
    "/prototipos/sigep/controle-vagas/quadro-autorizado?saldo=SEM_VAGAS_LIVRES",
  ),
  "Pendentes de ato de distribuição": spec(
    "CV-DASH-ALT-002",
    "Pendentes de ato de distribuição",
    "Evidenciar vagas autorizadas que ainda aguardam distribuição formal.",
    "Contar vagas cuja posição de distribuição esteja PENDENTE_ATO, respeitando os filtros do Dashboard.",
    "Vaga e posição temporal de distribuição.",
    "integer",
    "alerta navegável",
    "/prototipos/sigep/controle-vagas/quadro-autorizado",
  ),
  "Quadros em encerramento": spec(
    "CV-DASH-ALT-003",
    "Quadros em encerramento",
    "Indicar quadros em extinção progressiva que ainda possuem ocupações remanescentes.",
    "Contar cada Quadro Autorizado encerrado uma única vez e exigir ao menos uma ocupação remanescente.",
    "QuadroAutorizado e ocupações consolidadas por quadro.",
    "integer",
    "alerta navegável",
    "/prototipos/sigep/controle-vagas/quadro-autorizado?situacao=ENCERRADO",
  ),
};

export const dashboardKpiSpecifications: Record<string, SpecificationMetadata> = {
  "Cargos legais": spec(
    "CV-DASH-KPI-001",
    "Cargos legais",
    "Quantidade de cargos distintos com vagas legais validas na posicao.",
    "Contar nomes de cargo distintos entre vagas nao extintas apos aplicacao dos filtros.",
    "Vaga.cargo vinculada ao Quadro Autorizado.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/quadro-autorizado",
  ),
  "Quadros vigentes": spec(
    "CV-DASH-KPI-002",
    "Quadros vigentes",
    "Quantidade de origens legais distintas presentes na posicao filtrada.",
    "Contar codigos de Quadro Autorizado distintos com ao menos uma vaga legal valida na data.",
    "Vaga.quadroCodigo e vigencia do Quadro Autorizado.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/quadro-autorizado",
  ),
  "Vagas legais": spec(
    "CV-DASH-KPI-003",
    "Vagas legais",
    "Total de vagas que compoem o limite legal vigente.",
    "Contar vagas individualizadas validas e excluir as extintas na data de referencia.",
    "Vagas Individualizadas e historico da situacao legal.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas",
  ),
  Ocupadas: spec(
    "CV-DASH-KPI-004",
    "Ocupadas",
    "Vagas com ocupacao nominal ativa na data de referencia.",
    "Cada vinculo ativo ocupa uma unica vaga.",
    "Vaga.estado e OcupacaoVaga ativa.",
    "integer + percentual",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?estado=OCUPADA",
  ),
  Disponiveis: spec(
    "CV-DASH-KPI-005",
    "Disponiveis",
    "Vagas sem ocupacao ativa na posicao consultada.",
    "Inclui disponiveis livres e comprometidas para ocupacao; extintas nao entram.",
    "Vaga.estado e comprometimentos ativos.",
    "integer + subtotal",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?estado=DISPONIVEL",
  ),
  "Em ocupação": spec(
    "CV-DASH-KPI-006",
    "Em ocupação",
    "Vagas disponiveis vinculadas a processo de ingresso ainda nao concluido.",
    "Nao alterar o estado para ocupada ate posse/exercicio ou evento definitivo.",
    "ComprometimentoVaga ativo de natureza OCUPACAO, recebido do Ingresso do Servidor.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?comprometimento=OCUPACAO",
  ),
  "Pendente de ato de distribuicao": spec(
    "CV-DASH-KPI-008",
    "Pendente de ato de distribuicao",
    "Vagas cuja origem legal deixou a destinacao para ato administrativo posterior.",
    "Pendencia de ato e condicao distributiva, nao orgao nem banco central.",
    "Quadro Autorizado, Vaga e posicao reconstruida pelos movimentos de Distribuicao.",
    "integer + subtotal",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/quadro-autorizado",
  ),
  "Situacoes legais especiais": spec(
    "CV-DASH-KPI-009",
    "Situacoes legais especiais",
    "Vagas com situacao diferente de Regular.",
    "Contar em extincao, extintas na posicao historica aplicavel e em transformacao.",
    "Vaga.situacaoLegal e historico legal.",
    "integer",
    "KPI navegavel",
    "/prototipos/sigep/controle-vagas/vagas?legal=ESPECIAL",
  ),
};

export const dashboardBusinessItems = [
  ...Object.values(dashboardFilterSpecifications),
  ...Object.values(dashboardBlockSpecifications),
  ...Object.values(dashboardAlertSpecifications),
  ...Object.values(dashboardKpiSpecifications),
];
