import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./dashboardControleVagas.css";

import type { DashboardRow, SituacaoDashboard as Situacao } from "./types";
import { CONTROLE_VAGAS_BASE_PATH as BASE } from "./constants";

const disponivel=(r:DashboardRow)=>Math.max(0,r.distribuido-r.ocupado-r.comprometido-r.bloqueado);
const excedente=(r:DashboardRow)=>Math.max(0,r.ocupado+r.comprometido+r.bloqueado-r.distribuido);
const ocupacao=(r:DashboardRow)=>r.distribuido?Math.round(((r.ocupado+r.comprometido+r.bloqueado)/r.distribuido)*100):0;
const situacaoClass:Record<Situacao,string>={Regular:"regular",Atenção:"attention",Crítica:"critical","Sem saldo":"full",Excedente:"excess",Divergente:"divergent"};

export function DashboardControleVagasContent(){ const {dashboardLegado:dashboardControleVagasMock}=useControleVagasStore();
 const navigate=useNavigate(); const [orgao,setOrgao]=useState("");const [vinculo,setVinculo]=useState("");const [cargo,setCargo]=useState("");const [situacao,setSituacao]=useState("");const [periodo,setPeriodo]=useState("Hoje");const [detalhe,setDetalhe]=useState<DashboardRow|null>(null);
 const filtrados=useMemo(()=>dashboardControleVagasMock.filter(r=>(!orgao||r.orgao===orgao)&&(!vinculo||r.vinculo===vinculo)&&(!cargo||r.cargo===cargo)&&(!situacao||r.situacao===situacao)),[orgao,vinculo,cargo,situacao]);
 const totais=filtrados.reduce((a,r)=>({aut:a.aut+r.autorizado,dist:a.dist+r.distribuido,ocup:a.ocup+r.ocupado,comp:a.comp+r.comprometido,bloq:a.bloq+r.bloqueado,disp:a.disp+disponivel(r),exc:a.exc+excedente(r)}),{aut:0,dist:0,ocup:0,comp:0,bloq:0,disp:0,exc:0});
 const situacoes=(Object.keys(situacaoClass) as Situacao[]).map(s=>({nome:s,quantidade:filtrados.filter(r=>r.situacao===s).length}));
 const orgaos=[...new Set(filtrados.map(r=>r.orgao))].map(o=>{const rows=filtrados.filter(r=>r.orgao===o);const dist=rows.reduce((s,r)=>s+r.distribuido,0);const usado=rows.reduce((s,r)=>s+r.ocupado+r.comprometido+r.bloqueado,0);return {nome:o,dist,usado,percentual:dist?Math.round(usado/dist*100):0}}).sort((a,b)=>b.percentual-a.percentual);
 const prioritarios=[...filtrados].sort((a,b)=>(excedente(b)-excedente(a))||(ocupacao(b)-ocupacao(a))).slice(0,6);
 const limpar=()=>{setOrgao("");setVinculo("");setCargo("");setSituacao("")};
 return <div className="prototype-dash-page"><header className="prototype-dash-header"><div><span>Controle de Vagas</span><h1>Dashboard Gerencial</h1><p>Visão consolidada para acompanhamento e tomada de decisão.</p></div><div className="prototype-dash-header-actions"><small><i className="pi pi-clock"/> Atualizado em 15/07/2026 às 11:42</small><button><i className="pi pi-refresh"/> Atualizar</button><button><i className="pi pi-download"/> Exportar</button></div></header>
 <section className="prototype-dash-filters"><label><span>Órgão</span><select value={orgao} onChange={e=>setOrgao(e.target.value)}><option value="">Todos</option>{[...new Set(dashboardControleVagasMock.map(r=>r.orgao))].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Tipo de vínculo</span><select value={vinculo} onChange={e=>setVinculo(e.target.value)}><option value="">Todos</option>{[...new Set(dashboardControleVagasMock.map(r=>r.vinculo))].map(v=><option key={v}>{v}</option>)}</select></label><label className="wide"><span>Cargo ou função</span><select value={cargo} onChange={e=>setCargo(e.target.value)}><option value="">Todos</option>{dashboardControleVagasMock.map(r=><option key={r.id}>{r.cargo}</option>)}</select></label><label><span>Situação</span><select value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="">Todas</option>{Object.keys(situacaoClass).map(v=><option key={v}>{v}</option>)}</select></label><label><span>Período</span><select value={periodo} onChange={e=>setPeriodo(e.target.value)}><option>Hoje</option><option>Últimos 30 dias</option><option>Últimos 3 meses</option><option>Últimos 12 meses</option></select></label><button onClick={limpar}><i className="pi pi-filter-slash"/> Limpar</button></section>
 <section className="prototype-dash-kpis"><DashKpi label="Quadro autorizado" value={totais.aut} icon="pi pi-file-check" color="blue" hint="Limite vigente" onClick={()=>navigate(`${BASE}/quadro-autorizado`)}/><DashKpi label="Ocupadas" value={totais.ocup} icon="pi pi-users" color="green" hint={`${totais.dist?Math.round(totais.ocup/totais.dist*100):0}% do distribuído`} onClick={()=>navigate(`${BASE}/consulta-saldo`)}/><DashKpi label="Comprometidas" value={totais.comp} icon="pi pi-clock" color="purple" hint="Processos em andamento" onClick={()=>navigate(`${BASE}/distribuicao`)}/><DashKpi label="Disponíveis" value={totais.disp} icon="pi pi-check-circle" color="cyan" hint="Saldo utilizável" onClick={()=>navigate(`${BASE}/consulta-saldo`)}/><DashKpi label="Bloqueadas" value={totais.bloq} icon="pi pi-lock" color="orange" hint="Uso temporariamente impedido" onClick={()=>navigate(`${BASE}/distribuicao`)}/><DashKpi label="Excedentes" value={totais.exc} icon="pi pi-exclamation-triangle" color="red" hint={totais.exc?"Requer regularização":"Nenhuma ocorrência"} onClick={()=>navigate(`${BASE}/consulta-saldo`)}/></section>
 <div className="prototype-dash-grid top"><section className="prototype-dash-card situation"><CardHeader title="Situação geral do quadro" subtitle={`${filtrados.length} combinações analisadas`}/><div className="prototype-dash-situation-body"><div className="prototype-dash-donut" style={{"--regular":`${(situacoes[0].quantidade/Math.max(1,filtrados.length))*100}%`} as React.CSSProperties}><div><strong>{filtrados.length}</strong><span>Total</span></div></div><ul>{situacoes.map(s=><li key={s.nome} onClick={()=>setSituacao(s.nome)}><i className={situacaoClass[s.nome]}/><span>{s.nome}</span><strong>{s.quantidade}</strong><small>{Math.round(s.quantidade/Math.max(1,filtrados.length)*100)}%</small></li>)}</ul></div></section>
 <section className="prototype-dash-card organs"><CardHeader title="Ocupação por órgão" subtitle="Ocupado + comprometido + bloqueado"/><div className="prototype-dash-bars">{orgaos.slice(0,7).map(o=><button key={o.nome} onClick={()=>setOrgao(o.nome)}><span>{o.nome}</span><div><i style={{width:`${Math.min(100,o.percentual)}%`}} className={o.percentual>=100?"red":o.percentual>=95?"orange":"blue"}/></div><strong>{o.percentual}%</strong></button>)}</div></section>
 <section className="prototype-dash-card alerts"><CardHeader title="Alertas gerenciais" subtitle="Situações que exigem acompanhamento"/><div className="prototype-dash-alert-list"><Alert level="critical" icon="pi pi-exclamation-triangle" title="Ocupação excedente" text="Engenheiro Civil • SINFRA" value="1 vaga" onClick={()=>setDetalhe(dashboardControleVagasMock[6])}/><Alert level="critical" icon="pi pi-times-circle" title="Cargo sem saldo" text="DGA-6 • SEFAZ" value="100%" onClick={()=>setDetalhe(dashboardControleVagasMock[4])}/><Alert level="warning" icon="pi pi-inbox" title="Eventos não processados" text="Pendências de integração" value="4" onClick={()=>navigate(`${BASE}/distribuicao`)}/><Alert level="warning" icon="pi pi-history" title="Operações retroativas" text="Últimos 30 dias" value="2" onClick={()=>navigate(`${BASE}/distribuicao`)}/><Alert level="info" icon="pi pi-sitemap" title="Saldo não distribuído" text="Quadros com alocação pendente" value="47" onClick={()=>navigate(`${BASE}/distribuicao`)}/></div></section></div>
 <section className="prototype-dash-card priority"><CardHeader title="Painel de atenção gerencial" subtitle="Necessidades potenciais para análise — não representa decisão automática"><button onClick={()=>navigate(`${BASE}/consulta-saldo`)}>Ver todos os saldos <i className="pi pi-arrow-right"/></button></CardHeader><div className="prototype-dash-table"><table><thead><tr><th>Prioridade</th><th>Cargo e órgão</th><th className="num">Autorizado</th><th className="num">Ocupado</th><th className="num">Comprometido</th><th className="num">Disponível</th><th className="num">Saídas previstas</th><th>Indicação</th><th/></tr></thead><tbody>{prioritarios.map((r,index)=>{const indication=r.situacao==="Excedente"?"Regularizar excedente":r.situacao==="Divergente"?"Corrigir divergência":disponivel(r)===0?"Análise prioritária":ocupacao(r)>=95?"Monitorar com prioridade":"Monitorar";return <tr key={r.id}><td><span className={`prototype-dash-rank ${index<3?"high":""}`}>{String(index+1).padStart(2,"0")}</span></td><td><strong>{r.cargo}</strong><small>{r.orgao} • {r.unidade}</small></td><td className="num">{r.autorizado}</td><td className="num">{r.ocupado}</td><td className="num">{r.comprometido}</td><td className={`num ${disponivel(r)===0?"danger":"positive"}`}><strong>{disponivel(r)}</strong></td><td className="num simulated">{r.saidas}<small>projeção</small></td><td><span className={`prototype-dash-indication ${situacaoClass[r.situacao]}`}>{indication}</span></td><td><button onClick={()=>setDetalhe(r)}><i className="pi pi-chevron-right"/></button></td></tr>})}</tbody></table></div></section>
 <div className="prototype-dash-grid bottom"><section className="prototype-dash-card evolution"><CardHeader title="Evolução do saldo" subtitle={periodo}/><div className="prototype-dash-chart"><div className="prototype-dash-chart-y"><span>80</span><span>60</span><span>40</span><span>20</span><span>0</span></div><div className="prototype-dash-chart-area"><svg viewBox="0 0 600 180" preserveAspectRatio="none"><defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1986d2" stopOpacity=".28"/><stop offset="1" stopColor="#1986d2" stopOpacity=".02"/></linearGradient></defs><path d="M0,70 L100,82 L200,66 L300,95 L400,105 L500,118 L600,110 L600,180 L0,180 Z" fill="url(#areaFill)"/><polyline points="0,70 100,82 200,66 300,95 400,105 500,118 600,110" fill="none" stroke="#147cc3" strokeWidth="3"/><polyline points="0,132 100,124 200,138 300,126 400,144 500,136 600,150" fill="none" stroke="#8055c7" strokeWidth="2" strokeDasharray="5 4"/></svg><div className="prototype-dash-chart-x"><span>Jan</span><span>Fev</span><span>Mar</span><span>Abr</span><span>Mai</span><span>Jun</span><span>Jul</span></div></div></div><div className="prototype-dash-chart-legend"><span><i className="available"/>Disponíveis</span><span><i className="committed"/>Comprometidas</span></div></section>
 <section className="prototype-dash-card recent"><CardHeader title="Movimentações recentes" subtitle="Últimas alterações processadas"><button onClick={()=>navigate(`${BASE}/distribuicao`)}>Ver todas</button></CardHeader><div className="prototype-dash-recent-list">{[{icon:"pi pi-user-plus",type:"Ocupação",text:"Analista Administrativo",meta:"SEPLAG • Hoje, 09:42",value:"−1",kind:"red"},{icon:"pi pi-sign-out",type:"Liberação",text:"Técnico em Enfermagem",meta:"SES • Ontem, 16:18",value:"+1",kind:"green"},{icon:"pi pi-lock",type:"Bloqueio",text:"DGA-6",meta:"SEFAZ • 12/07/2026",value:"−1",kind:"orange"},{icon:"pi pi-arrow-right-arrow-left",type:"Transferência",text:"Analista Administrativo",meta:"SEPLAG • 10/07/2026",value:"2",kind:"blue"}].map((m,i)=><article key={i}><i className={`${m.icon} ${m.kind}`}/><div><span>{m.type}</span><strong>{m.text}</strong><small>{m.meta}</small></div><b className={m.kind}>{m.value}</b></article>)}</div></section></div>
 {detalhe&&<DashboardDetail item={detalhe} onClose={()=>setDetalhe(null)} onNavigate={path=>{setDetalhe(null);navigate(path)}}/>}</div>
}
function DashKpi({label,value,icon,color,hint,onClick}:{label:string;value:number;icon:string;color:string;hint:string;onClick:()=>void}){return <button className={`prototype-dash-kpi ${color}`} onClick={onClick}><i className={icon}/><div><span>{label}</span><strong>{value.toLocaleString("pt-BR")}</strong><small>{hint}</small></div><i className="pi pi-chevron-right arrow"/></button>}
function CardHeader({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <header><div><h2>{title}</h2><p>{subtitle}</p></div>{children}</header>}
function Alert({level,icon,title,text,value,onClick}:{level:string;icon:string;title:string;text:string;value:string;onClick:()=>void}){return <button className={level} onClick={onClick}><i className={icon}/><div><strong>{title}</strong><span>{text}</span></div><b>{value}</b><i className="pi pi-chevron-right"/></button>}
function DashboardDetail({item,onClose,onNavigate}:{item:DashboardRow;onClose:()=>void;onNavigate:(p:string)=>void}){const disp=disponivel(item);return <div className="prototype-dash-backdrop" onMouseDown={onClose}><section className="prototype-dash-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span>Visão consolidada</span><h2>{item.cargo}</h2><p>{item.orgao} • {item.unidade}</p></div><button onClick={onClose}><i className="pi pi-times"/></button></header><div className="prototype-dash-detail-status"><span className={situacaoClass[item.situacao]}>{item.situacao}</span><div><strong>{ocupacao(item)}%</strong><small>utilização do distribuído</small></div></div><div className="prototype-dash-detail-numbers"><div><span>Autorizado</span><strong>{item.autorizado}</strong></div><div><span>Distribuído</span><strong>{item.distribuido}</strong></div><div><span>Ocupado</span><strong>{item.ocupado}</strong></div><div><span>Comprometido</span><strong>{item.comprometido}</strong></div><div><span>Bloqueado</span><strong>{item.bloqueado}</strong></div><div className={disp?"available":"danger"}><span>Disponível</span><strong>{disp}</strong></div></div><div className="prototype-dash-projection"><i className="pi pi-chart-line"/><div><strong>Projeção informativa</strong><p>{item.saidas} possíveis saídas e {item.processos} processos em andamento. Estes dashboardControleVagasMock são simulados no protótipo.</p></div></div><div className="prototype-dash-detail-actions"><button onClick={()=>onNavigate(`${BASE}/quadro-autorizado`)}><i className="pi pi-file-check"/> Quadro autorizado</button><button onClick={()=>onNavigate(`${BASE}/distribuicao`)}><i className="pi pi-sitemap"/> Distribuições</button><button onClick={()=>onNavigate(`${BASE}/consulta-saldo`)}><i className="pi pi-calculator"/> Memória do saldo</button><button onClick={()=>onNavigate(`${BASE}/distribuicao`)}><i className="pi pi-list"/> Movimentações</button></div><footer><button onClick={onClose}>Fechar</button></footer></section></div>}