import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { CONTROLE_VAGAS_BASE_PATH as BASE } from "./constants";
import { useControleVagasStore } from "./controleVagasStore";
import { construirDashboard, situacoesLegais, type DashboardFiltros, type DashboardGrupo } from "./dashboardSelectors";
import type { CenarioProjecao, HorizonteProjecao } from "./types";
import "./dashboardControleVagas.css";
import "./dashboardGerencial.css";

const hoje="2026-07-17";
const prioridadeLabel={REGULAR:"Regular",ATENCAO:"Atenção",CRITICA:"Crítica",DIVERGENTE:"Divergente"} as const;
const legalLabel={REGULAR:"Regular",EM_EXTINCAO:"Em extinção",EXTINTA:"Extinta",EM_TRANSFORMACAO:"Em transformação",DIVERGENTE:"Divergente"} as const;
const cenarioLabel={CONSERVADOR:"Conservador",PROVAVEL:"Provável",AMPLIADO:"Ampliado"} as const;
const filtrosIniciais:DashboardFiltros={dataReferencia:hoje,orgaoTitular:"",orgaoExercicio:"",tipo:"",carreira:"",cargo:"",situacaoLegal:"",somenteCessoes:false};

export function DashboardGerencialContent(){
 const state=useControleVagasStore();const navigate=useNavigate();
 const [filtros,setFiltros]=useState(filtrosIniciais);const [filtrosAbertos,setFiltrosAbertos]=useState(false);const [cenario,setCenario]=useState<CenarioProjecao>("PROVAVEL");const [horizonte,setHorizonte]=useState<HorizonteProjecao>(24);const [detalhe,setDetalhe]=useState<DashboardGrupo|null>(null);
 const dados=useMemo(()=>construirDashboard(state,filtros,cenario,horizonte),[state,filtros,cenario,horizonte]);
 const orgaos=[...new Set(state.vagas.map((v)=>v.orgaoTitular))].sort();const exercicios=[...new Set(state.ocupacoes.map((o)=>o.orgaoExercicio))].sort();const carreiras=[...new Set(state.vagas.map((v)=>v.carreira))].sort();const cargos=[...new Set(state.vagas.map((v)=>v.cargo))].sort();
 const eventos=[...state.movimentos].sort((a,b)=>b.registradoEm.localeCompare(a.registradoEm)).slice(0,5);
 const alertas=[
  {icon:"pi pi-exclamation-triangle",kind:"critical",titulo:"Cargos sem saldo livre",valor:dados.grupos.filter((g)=>g.disponiveisLivres===0).length,rota:"consulta-saldo"},
  {icon:"pi pi-link",kind:"critical",titulo:"Divergências de conciliação",valor:dados.resumo.divergentes,rota:"consulta-saldo"},
  {icon:"pi pi-gavel",kind:"warning",titulo:"Ocupações judiciais extraquadro",valor:dados.resumo.judiciais,rota:"consulta-saldo"},
  {icon:"pi pi-hourglass",kind:"warning",titulo:"Vagas em extinção",valor:dados.resumo.emExtincao,rota:"vagas"},
  {icon:"pi pi-send",kind:"info",titulo:"Cessões ativas",valor:dados.resumo.cessoes,rota:"cessoes"},
 ];
 return <div className="prototype-dash-page prototype-management-dashboard">
  <header className="prototype-dash-header"><div><h1>Dashboard Gerencial</h1></div><div className="prototype-dash-header-actions"><small>Dados consolidados em<br/><strong>17/07/2026 08:15</strong></small><button onClick={()=>window.print()}><i className="pi pi-download"/> Exportar visão</button></div></header>
  <section className="prototype-management-filter-accordion"><button className="prototype-management-filter-trigger" onClick={()=>setFiltrosAbertos((aberto)=>!aberto)} aria-expanded={filtrosAbertos}><span><i className="pi pi-filter"/><strong>Filtros da consulta</strong><small>Data, órgãos, carreira, cargo e situação legal</small></span><i className={`pi ${filtrosAbertos?"pi-chevron-up":"pi-chevron-down"}`}/></button>{filtrosAbertos&&<div className="prototype-dash-filters management">
   <Filtro label="Data de referência"><input type="date" value={filtros.dataReferencia} onChange={(e)=>setFiltros({...filtros,dataReferencia:e.target.value})}/></Filtro>
   <Filtro label="Órgão titular"><select value={filtros.orgaoTitular} onChange={(e)=>setFiltros({...filtros,orgaoTitular:e.target.value})}><option value="">Todos</option>{orgaos.map((v)=><option key={v}>{v}</option>)}</select></Filtro>
   <Filtro label="Órgão de exercício"><select value={filtros.orgaoExercicio} onChange={(e)=>setFiltros({...filtros,orgaoExercicio:e.target.value})}><option value="">Todos</option>{exercicios.map((v)=><option key={v}>{v}</option>)}</select></Filtro>
   <Filtro label="Tipo"><select value={filtros.tipo} onChange={(e)=>setFiltros({...filtros,tipo:e.target.value})}><option value="">Efetivos e comissionados</option><option value="EFETIVO">Efetivo</option><option value="COMISSIONADO">Comissionado</option></select></Filtro>
   <Filtro label="Carreira"><select value={filtros.carreira} onChange={(e)=>setFiltros({...filtros,carreira:e.target.value})}><option value="">Todas</option>{carreiras.map((v)=><option key={v}>{v}</option>)}</select></Filtro>
   <Filtro label="Cargo"><select value={filtros.cargo} onChange={(e)=>setFiltros({...filtros,cargo:e.target.value})}><option value="">Todos</option>{cargos.map((v)=><option key={v}>{v}</option>)}</select></Filtro>
   <Filtro label="Situação legal"><select value={filtros.situacaoLegal} onChange={(e)=>setFiltros({...filtros,situacaoLegal:e.target.value})}><option value="">Todas</option>{situacoesLegais.map((v)=><option key={v} value={v}>{legalLabel[v]}</option>)}</select></Filtro>
   <div className="prototype-management-filter-actions"><label className="prototype-dash-check" title="Exibe somente vagas com ocupante em cessão ativa"><input type="checkbox" checked={filtros.somenteCessoes} onChange={(e)=>setFiltros({...filtros,somenteCessoes:e.target.checked})}/><span>Somente cessões<small>Ocupantes em exercício em outro órgão</small></span></label><button className="prototype-management-clear-filter" onClick={()=>setFiltros(filtrosIniciais)}><i className="pi pi-filter-slash"/> Limpar</button></div>
  </div>}</section>
  <section className="prototype-dash-kpis management">
   <Kpi label="Cargos legais" valor={dados.resumo.cargos} hint="Cargo e órgão" icon="pi pi-briefcase" cor="blue" onClick={()=>navigate(`${BASE}/quadro-autorizado`)}/>
   <Kpi label="Vagas legais" valor={dados.resumo.vagasLegais} hint="Limite vigente" icon="pi pi-balance-scale" cor="blue" onClick={()=>navigate(`${BASE}/vagas`)}/>
   <Kpi label="Ocupadas" valor={dados.resumo.ocupadas} hint={`${dados.resumo.vagasLegais?Math.round(dados.resumo.ocupadas/dados.resumo.vagasLegais*100):0}% do quadro`} icon="pi pi-users" cor="green" onClick={()=>navigate(`${BASE}/ocupacoes`)}/>
   <Kpi label="Disponíveis" valor={dados.resumo.disponiveis} hint={`${dados.resumo.livres} livres`} icon="pi pi-check-circle" cor="cyan" onClick={()=>navigate(`${BASE}/consulta-saldo`)}/>
   <Kpi label="Comprometidas" valor={dados.resumo.comprometidas} hint="Para ocupação" icon="pi pi-flag" cor="purple" onClick={()=>navigate(`${BASE}/comprometimentos`)}/>
   <Kpi label="Em disponibilização" valor={dados.resumo.emDisponibilizacao} hint="Ainda ocupadas" icon="pi pi-sign-out" cor="orange" onClick={()=>navigate(`${BASE}/comprometimentos`)}/>
   <Kpi label="Situações especiais" valor={dados.resumo.emExtincao+dados.resumo.judiciais+dados.resumo.divergentes} hint="Legal e conciliação" icon="pi pi-exclamation-triangle" cor="red" onClick={()=>navigate(`${BASE}/consulta-saldo`)}/>
  </section>
  <div className="prototype-dash-grid management-top">
   <section className="prototype-dash-card management-status"><CardHeader titulo="Composição do quadro" subtitulo={`Posição em ${filtros.dataReferencia.split("-").reverse().join("/")}`}/><div className="prototype-management-composition"><div className="ring" style={{background:`conic-gradient(#278bc4 0 ${dados.resumo.vagasLegais?dados.resumo.ocupadas/dados.resumo.vagasLegais*100:0}%,#31a565 0)`}}><span><strong>{dados.resumo.vagasLegais}</strong><small>vagas legais</small></span></div><ul><li><i className="occupied"/><span>Ocupadas</span><strong>{dados.resumo.ocupadas}</strong></li><li><i className="available"/><span>Disponíveis livres</span><strong>{dados.resumo.livres}</strong></li><li><i className="committed"/><span>Disponíveis comprometidas</span><strong>{dados.resumo.comprometidas}</strong></li><li><i className="release"/><span>Em disponibilização</span><strong>{dados.resumo.emDisponibilizacao}</strong></li></ul></div></section>
   <section className="prototype-dash-card alerts"><CardHeader titulo="Alertas gerenciais" subtitulo="Situações que exigem análise"/><div className="prototype-dash-alert-list">{alertas.map((a)=><button key={a.titulo} className={a.kind} onClick={()=>navigate(`${BASE}/${a.rota}`)}><i className={a.icon}/><div><strong>{a.titulo}</strong><span>Abrir memória e registros de origem</span></div><b>{a.valor}</b><i className="pi pi-chevron-right"/></button>)}</div></section>
   <section className="prototype-dash-card"><CardHeader titulo="Projeção estratégica" subtitulo="Não representa decisão automática"/><div className="prototype-management-projection-controls"><div>{(["CONSERVADOR","PROVAVEL","AMPLIADO"] as CenarioProjecao[]).map((v)=><button key={v} className={cenario===v?"active":""} onClick={()=>setCenario(v)}>{cenarioLabel[v]}</button>)}</div><select value={horizonte} onChange={(e)=>setHorizonte(Number(e.target.value) as HorizonteProjecao)}>{([12,24,36,48] as HorizonteProjecao[]).map((v)=><option key={v} value={v}>{v} meses</option>)}</select></div><div className="prototype-management-projection"><article><span>Disponíveis livres hoje</span><strong>{dados.resumo.livres}</strong></article><i className="pi pi-plus"/><article><span>Aposentadorias previstas</span><strong>{dados.resumo.aposentadorias}</strong></article><i className="pi pi-arrow-right"/><article className="total"><span>Potencial em {horizonte} meses</span><strong>{dados.resumo.potencial}</strong></article></div><button className="prototype-management-link" onClick={()=>navigate(`${BASE}/projecoes`)}>Ver metodologia e cenários <i className="pi pi-arrow-right"/></button></section>
  </div>
  <section className="prototype-dash-card priority management-table"><CardHeader titulo="Quadro estratégico por cargo e órgão" subtitulo="Origem rastreável: quadro legal, vagas, ocupações, comprometimentos e projeções"><button onClick={()=>navigate(`${BASE}/consulta-saldo`)}>Abrir saldos <i className="pi pi-arrow-right"/></button></CardHeader><div className="prototype-dash-table"><table><thead><tr><th>Prioridade</th><th>Cargo, carreira e lei</th><th>Órgão</th><th className="num">Legais</th><th className="num">Ocupadas</th><th className="num">Livres</th><th className="num">Comprometidas</th><th className="num">Em saída</th><th className="num">Cessões</th><th className="num">Aposentadorias</th><th className="num">Potencial {horizonte}m</th><th/></tr></thead><tbody>{dados.grupos.map((g)=><tr key={g.chave}><td><span className={`prototype-management-priority ${g.prioridade.toLowerCase()}`}>{prioridadeLabel[g.prioridade]}</span></td><td><strong>{g.cargo}</strong><small>{g.carreira} • {g.lei}</small></td><td><strong>{g.orgao}</strong><small>{g.tipo==="EFETIVO"?"Efetivo":"Comissionado"}</small></td><td className="num">{g.vagasLegais}</td><td className="num">{g.ocupadas}<small>{g.percentualOcupacao}%</small></td><td className={`num ${g.disponiveisLivres===0?"danger":"positive"}`}><strong>{g.disponiveisLivres}</strong></td><td className="num">{g.disponiveisComprometidas}</td><td className="num">{g.ocupadasEmDisponibilizacao}</td><td className="num">{g.cessoes}</td><td className="num simulated">{g.aposentadorias}</td><td className="num"><strong>{g.potencial}</strong></td><td><button onClick={()=>setDetalhe(g)}><i className="pi pi-chevron-right"/></button></td></tr>)}</tbody></table></div></section>
  <div className="prototype-dash-grid management-bottom"><section className="prototype-dash-card"><CardHeader titulo="Necessidade potencial" subtitulo={`Maiores potenciais no cenário ${cenarioLabel[cenario].toLowerCase()}`}/><div className="prototype-management-bars">{[...dados.grupos].sort((a,b)=>b.potencial-a.potencial).slice(0,6).map((g)=><button key={g.chave} onClick={()=>setDetalhe(g)}><span>{g.cargo}<small>{g.orgao}</small></span><div><i style={{width:`${dados.resumo.potencial?g.potencial/Math.max(...dados.grupos.map((i)=>i.potencial),1)*100:0}%`}}/></div><strong>{g.potencial}</strong></button>)}</div></section><section className="prototype-dash-card"><CardHeader titulo="Movimentações recentes" subtitulo="Livro temporal unificado"><button onClick={()=>navigate(`${BASE}/distribuicao`)}>Ver todas</button></CardHeader><div className="prototype-dash-recent-list">{eventos.map((m)=><article key={m.id}><i className="pi pi-history blue"/><div><span>{m.tipo.replaceAll("_"," ")}</span><strong>{m.vagaId}</strong><small>{m.dataEfeito} • {m.ato}</small></div>{m.retroativo&&<b className="orange">Retroativo</b>}</article>)}</div></section></div>
  {detalhe&&<DetalheGrupo grupo={detalhe} horizonte={horizonte} onClose={()=>setDetalhe(null)} onNavigate={(rota)=>navigate(`${BASE}/${rota}`)}/>} 
 </div>
}

function Filtro({label,children}:{label:string;children:React.ReactNode}){return <label><span>{label}</span>{children}</label>}
function Kpi({label,valor,hint,icon,cor,onClick}:{label:string;valor:number;hint:string;icon:string;cor:string;onClick:()=>void}){return <button className={`prototype-dash-kpi ${cor}`} onClick={onClick}><i className={icon}/><div><span>{label}</span><strong>{valor.toLocaleString("pt-BR")}</strong><small>{hint}</small></div><i className="pi pi-arrow-right arrow"/></button>}
function CardHeader({titulo,subtitulo,children}:{titulo:string;subtitulo:string;children?:React.ReactNode}){return <header><div><h2>{titulo}</h2><p>{subtitulo}</p></div>{children}</header>}
function DetalheGrupo({grupo,horizonte,onClose,onNavigate}:{grupo:DashboardGrupo;horizonte:number;onClose:()=>void;onNavigate:(rota:string)=>void}){return <div className="prototype-dash-backdrop" onMouseDown={onClose}><section className="prototype-dash-modal management-detail" onMouseDown={(e)=>e.stopPropagation()}><header><div><span>Memória gerencial</span><h2>{grupo.cargo}</h2><p>{grupo.carreira} • {grupo.orgao} • {grupo.lei}</p></div><button onClick={onClose}><i className="pi pi-times"/></button></header><div className="prototype-dash-detail-status"><span className={grupo.prioridade.toLowerCase()}>{prioridadeLabel[grupo.prioridade]}</span><div><strong>{grupo.percentualOcupacao}%</strong><small>ocupação do quadro legal</small></div></div><div className="prototype-dash-detail-numbers"><div><span>Vagas legais</span><strong>{grupo.vagasLegais}</strong></div><div><span>Ocupadas</span><strong>{grupo.ocupadas}</strong></div><div className="available"><span>Disponíveis livres</span><strong>{grupo.disponiveisLivres}</strong></div><div><span>Comprometidas</span><strong>{grupo.disponiveisComprometidas}</strong></div><div><span>Em saída</span><strong>{grupo.ocupadasEmDisponibilizacao}</strong></div><div><span>Em extinção</span><strong>{grupo.emExtincao}</strong></div></div><div className="prototype-dash-projection"><i className="pi pi-chart-line"/><div><strong>Potencial para análise: {grupo.potencial} vagas em {horizonte} meses</strong><p>{grupo.aposentadorias} aposentadorias, {grupo.outrasSaidas} exonerações conhecidas e {grupo.evasao} saídas por evasão estimada. É uma projeção informativa, não uma autorização de concurso.</p></div></div><section className="prototype-management-occupants"><h3>Quem compõe as ocupações</h3><div><table><thead><tr><th>Pessoa</th><th>Matrícula / vínculo</th><th>Vaga</th><th>Órgão de exercício</th><th>Efetivo exercício</th></tr></thead><tbody>{grupo.ocupacoes.slice(0,8).map((o)=><tr key={o.id}><td>{o.pessoaNome}</td><td>{o.matricula}<small>{o.vinculoId}</small></td><td>{o.vagaId}</td><td>{o.orgaoExercicio}</td><td>{o.efetivoExercicioEm}</td></tr>)}</tbody></table></div>{grupo.ocupacoes.length>8&&<small>Exibindo 8 de {grupo.ocupacoes.length} ocupações.</small>}</section><div className="prototype-dash-detail-actions"><button onClick={()=>onNavigate("vagas")}><i className="pi pi-list"/> Vagas</button><button onClick={()=>onNavigate("ocupacoes")}><i className="pi pi-users"/> Ocupações</button><button onClick={()=>onNavigate("cessoes")}><i className="pi pi-send"/> Cessões</button><button onClick={()=>onNavigate("projecoes")}><i className="pi pi-chart-line"/> Projeções</button></div><footer><button onClick={onClose}>Fechar</button></footer></section></div>}
