import { useMemo, useState, type FormEvent } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import "./distribuicaoSaldo.css";

interface DistribuicaoRow {
  id: number; quadro: string; cargo: string; especialidade: string; vinculo: string; orgao: string; unidade: string;
  autorizado: number; distribuido: number; ocupado: number; comprometido: number; bloqueado: number; vigencia: string; situacao: "Regular" | "Atenção" | "Crítica" | "Sem saldo" | "Excedente";
}

const BASE = "/prototipos/sigep/controle-vagas";
const dadosIniciais: DistribuicaoRow[] = [
  { id: 1, quadro: "QA-0001", cargo: "Analista Administrativo", especialidade: "Administração", vinculo: "Efetivo", orgao: "SEPLAG", unidade: "Administração Sistêmica", autorizado: 120, distribuido: 52, ocupado: 46, comprometido: 2, bloqueado: 0, vigencia: "01/01/2025", situacao: "Atenção" },
  { id: 2, quadro: "QA-0001", cargo: "Analista Administrativo", especialidade: "Administração", vinculo: "Efetivo", orgao: "SEPLAG", unidade: "Gestão de Pessoas", autorizado: 120, distribuido: 38, ocupado: 36, comprometido: 1, bloqueado: 0, vigencia: "01/01/2025", situacao: "Crítica" },
  { id: 3, quadro: "QA-0001", cargo: "Analista Administrativo", especialidade: "Administração", vinculo: "Efetivo", orgao: "SEPLAG", unidade: "Tecnologia da Informação", autorizado: 120, distribuido: 20, ocupado: 18, comprometido: 1, bloqueado: 0, vigencia: "01/01/2025", situacao: "Crítica" },
  { id: 4, quadro: "QA-0002", cargo: "Técnico em Enfermagem", especialidade: "", vinculo: "Efetivo", orgao: "SES", unidade: "Hospital Metropolitano", autorizado: 500, distribuido: 210, ocupado: 202, comprometido: 5, bloqueado: 2, vigencia: "01/03/2025", situacao: "Crítica" },
  { id: 5, quadro: "QA-0002", cargo: "Técnico em Enfermagem", especialidade: "", vinculo: "Efetivo", orgao: "SES", unidade: "Hospital Regional de Rondonópolis", autorizado: 500, distribuido: 160, ocupado: 158, comprometido: 3, bloqueado: 0, vigencia: "01/03/2025", situacao: "Excedente" },
  { id: 6, quadro: "QA-0003", cargo: "DGA-6", especialidade: "", vinculo: "Comissionado", orgao: "SEFAZ", unidade: "Gabinete", autorizado: 42, distribuido: 18, ocupado: 17, comprometido: 1, bloqueado: 0, vigencia: "01/01/2026", situacao: "Sem saldo" },
  { id: 7, quadro: "QA-0004", cargo: "Professor da Educação Básica", especialidade: "Matemática", vinculo: "Temporário", orgao: "SEDUC", unidade: "Diretoria Regional Metropolitana", autorizado: 300, distribuido: 185, ocupado: 162, comprometido: 8, bloqueado: 0, vigencia: "01/08/2026", situacao: "Regular" },
];

const disponivel = (r: DistribuicaoRow) => r.distribuido - r.ocupado - r.comprometido - r.bloqueado;
const statusClass: Record<DistribuicaoRow["situacao"], string> = { Regular: "is-regular", Atenção: "is-attention", Crítica: "is-critical", "Sem saldo": "is-full", Excedente: "is-excess" };

export function DistribuicaoSaldoContent() {
  const location = useLocation();
  return location.pathname.includes("consulta-saldo") ? <ConsultaSaldo /> : <DistribuicaoVagas />;
}

function DistribuicaoVagas() {
  const navigate = useNavigate();
  const [dados, setDados] = useState(dadosIniciais);
  const [busca, setBusca] = useState(""); const [orgao, setOrgao] = useState(""); const [quadro, setQuadro] = useState("");
  const [modal, setModal] = useState<{ tipo: "distribuir" | "transferir" | "recolher"; item?: DistribuicaoRow } | null>(null);
  const filtrados = useMemo(() => { const t = busca.trim().toLowerCase(); return dados.filter(r => (!t || `${r.cargo} ${r.unidade} ${r.especialidade}`.toLowerCase().includes(t)) && (!orgao || r.orgao === orgao) && (!quadro || r.quadro === quadro)); }, [busca, orgao, quadro, dados]);
  const quadros = useMemo(() => [...new Set(dados.map(r => r.quadro))], [dados]);
  const resumo = quadros.reduce((acc, codigo) => { const linhas = dados.filter(r => r.quadro === codigo); const autorizado = linhas[0]?.autorizado ?? 0; return { autorizado: acc.autorizado + autorizado, distribuido: acc.distribuido + linhas.reduce((s,r)=>s+r.distribuido,0) }; }, { autorizado: 0, distribuido: 0 });
  return <div className="prototype-distrib-page"><PageHeader title="Distribuição de Vagas" description="Alocação do quadro autorizado entre órgãos e unidades."><button className="prototype-distrib-primary" onClick={() => setModal({ tipo: "distribuir" })}><i className="pi pi-plus" /> Nova distribuição</button></PageHeader>
    <div className="prototype-distrib-notice"><i className="pi pi-info-circle" /><span>A distribuição não altera o quadro autorizado. Ela apenas define onde o quantitativo poderá ser utilizado.</span></div>
    <section className="prototype-distrib-kpis"><Kpi label="Quadro autorizado" value={resumo.autorizado} icon="pi pi-file-check"/><Kpi label="Total distribuído" value={resumo.distribuido} icon="pi pi-sitemap"/><Kpi label="Não distribuído" value={Math.max(0,resumo.autorizado-resumo.distribuido)} icon="pi pi-inbox" kind="available"/><Kpi label="Distribuições ativas" value={dados.length} icon="pi pi-building"/></section>
    <section className="prototype-distrib-card"><header><div><h2>Distribuições vigentes</h2><p>Quantitativos alocados na data de referência.</p></div><button onClick={() => navigate(`${BASE}/consulta-saldo`)}>Consultar saldos <i className="pi pi-arrow-right" /></button></header>
      <div className="prototype-distrib-filters"><label className="is-wide"><span>Cargo, especialidade ou unidade</span><div><i className="pi pi-search"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Pesquisar distribuição"/></div></label><label><span>Quadro autorizado</span><select value={quadro} onChange={e=>setQuadro(e.target.value)}><option value="">Todos</option>{quadros.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Órgão</span><select value={orgao} onChange={e=>setOrgao(e.target.value)}><option value="">Todos</option>{[...new Set(dados.map(r=>r.orgao))].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Data de referência</span><input type="date" defaultValue="2026-07-15"/></label><button onClick={()=>{setBusca("");setQuadro("");setOrgao("")}}><i className="pi pi-filter-slash"/> Limpar</button></div>
      <div className="prototype-distrib-table"><table><thead><tr><th>Quadro/Cargo</th><th>Destino</th><th className="num">Distribuído</th><th className="num">Ocupado</th><th className="num">Disponível</th><th>Vigência</th><th>Situação</th><th/></tr></thead><tbody>{filtrados.map(r=><tr key={r.id}><td><strong>{r.cargo}</strong><small>{r.quadro} • {r.vinculo}{r.especialidade ? ` • ${r.especialidade}`:""}</small></td><td><strong>{r.orgao}</strong><small>{r.unidade}</small></td><td className="num">{r.distribuido}</td><td className="num">{r.ocupado}</td><td className={`num ${disponivel(r)<=0?"danger":"positive"}`}><strong>{Math.max(0,disponivel(r))}</strong></td><td>{r.vigencia}</td><td><span className={`prototype-distrib-status ${statusClass[r.situacao]}`}>{r.situacao}</span></td><td><div className="prototype-distrib-actions"><button title="Transferir" onClick={()=>setModal({tipo:"transferir",item:r})}><i className="pi pi-arrow-right-arrow-left"/></button><button title="Recolher" onClick={()=>setModal({tipo:"recolher",item:r})}><i className="pi pi-undo"/></button></div></td></tr>)}</tbody></table></div><footer>{filtrados.length} distribuições encontradas</footer>
    </section>{modal&&<DistribuicaoModal modal={modal} dados={dados} onClose={()=>setModal(null)} onSave={registro=>{setDados(atual=>registro.id?atual.map(r=>r.id===registro.id?registro:r):[...atual,{...registro,id:Math.max(...atual.map(r=>r.id))+1}]);setModal(null)}}/>}
  </div>;
}

function ConsultaSaldo() {
  const navigate = useNavigate(); const [busca,setBusca]=useState(""); const [orgao,setOrgao]=useState(""); const [situacao,setSituacao]=useState(""); const [detalhe,setDetalhe]=useState<DistribuicaoRow|null>(null);
  const filtrados=useMemo(()=>{const t=busca.trim().toLowerCase();return dadosIniciais.filter(r=>(!t||`${r.cargo} ${r.unidade} ${r.quadro}`.toLowerCase().includes(t))&&(!orgao||r.orgao===orgao)&&(!situacao||r.situacao===situacao))},[busca,orgao,situacao]);
  const totaisOperacionais=filtrados.reduce((a,r)=>({dist:a.dist+r.distribuido,ocup:a.ocup+r.ocupado,comp:a.comp+r.comprometido,bloq:a.bloq+r.bloqueado,disp:a.disp+Math.max(0,disponivel(r)),exc:a.exc+Math.max(0,-disponivel(r))}),{dist:0,ocup:0,comp:0,bloq:0,disp:0,exc:0});
  const autorizadoUnico=[...new Set(filtrados.map(r=>r.quadro))].reduce((total,codigo)=>total+(filtrados.find(r=>r.quadro===codigo)?.autorizado??0),0);
  const totais={aut:autorizadoUnico,...totaisOperacionais};
  return <div className="prototype-distrib-page"><PageHeader title="Consulta de Saldo" description="Posição consolidada das vagas por data de referência."><button className="prototype-distrib-secondary" onClick={()=>navigate(`${BASE}/distribuicao`)}><i className="pi pi-sitemap"/> Ver distribuições</button></PageHeader>
    <div className="prototype-distrib-notice is-warning"><i className="pi pi-database"/><span>Ocupações e comprometimentos são simulados nesta etapa. A composição já segue a fórmula definida em Regras e Parâmetros.</span></div>
    <section className="prototype-saldo-kpis"><Kpi label="Autorizado" value={totais.aut} icon="pi pi-file-check"/><Kpi label="Distribuído" value={totais.dist} icon="pi pi-sitemap"/><Kpi label="Ocupado" value={totais.ocup} icon="pi pi-users"/><Kpi label="Comprometido" value={totais.comp} icon="pi pi-clock"/><Kpi label="Bloqueado" value={totais.bloq} icon="pi pi-lock"/><Kpi label="Disponível" value={totais.disp} icon="pi pi-check-circle" kind="available"/><Kpi label="Excedente" value={totais.exc} icon="pi pi-exclamation-triangle" kind="danger"/></section>
    <section className="prototype-distrib-card"><header><div><h2>Composição do saldo</h2><p>Clique em um registro para visualizar a memória do cálculo.</p></div><button><i className="pi pi-download"/> Exportar</button></header><div className="prototype-distrib-filters saldo"><label className="is-wide"><span>Cargo, quadro ou unidade</span><div><i className="pi pi-search"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Pesquisar no saldo"/></div></label><label><span>Órgão</span><select value={orgao} onChange={e=>setOrgao(e.target.value)}><option value="">Todos</option>{[...new Set(dadosIniciais.map(r=>r.orgao))].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Situação</span><select value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="">Todas</option>{Object.keys(statusClass).map(v=><option key={v}>{v}</option>)}</select></label><label><span>Data de referência</span><input type="date" defaultValue="2026-07-15"/></label><button onClick={()=>{setBusca("");setOrgao("");setSituacao("")}}><i className="pi pi-filter-slash"/> Limpar</button></div>
      <div className="prototype-distrib-table saldo"><table><thead><tr><th>Cargo e destino</th><th className="num">Autorizado</th><th className="num">Distribuído</th><th className="num">Ocupado</th><th className="num">Comprometido</th><th className="num">Bloqueado</th><th className="num">Disponível</th><th className="num">Excedente</th><th>Situação</th></tr></thead><tbody>{filtrados.map(r=><tr key={r.id} onClick={()=>setDetalhe(r)} tabIndex={0}><td><strong>{r.cargo}</strong><small>{r.orgao} • {r.unidade}</small></td><td className="num">{r.autorizado}</td><td className="num">{r.distribuido}</td><td className="num">{r.ocupado}</td><td className="num">{r.comprometido}</td><td className="num">{r.bloqueado}</td><td className="num positive"><strong>{Math.max(0,disponivel(r))}</strong></td><td className="num danger"><strong>{Math.max(0,-disponivel(r))||"—"}</strong></td><td><span className={`prototype-distrib-status ${statusClass[r.situacao]}`}>{r.situacao}</span></td></tr>)}</tbody></table></div><footer><span>{filtrados.length} saldos encontrados</span><span>Posição em 15/07/2026</span></footer></section>{detalhe&&<MemoriaSaldo item={detalhe} onClose={()=>setDetalhe(null)}/>}</div>;
}

function PageHeader({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <header className="prototype-distrib-header"><div><span>Controle de Vagas</span><h1>{title}</h1><p>{description}</p></div>{children}</header>}
function Kpi({label,value,icon,kind=""}:{label:string;value:number;icon:string;kind?:string}){return <article className={kind}><i className={icon}/><div><span>{label}</span><strong>{value.toLocaleString("pt-BR")}</strong></div></article>}

function DistribuicaoModal({modal,dados,onClose,onSave}:{modal:{tipo:"distribuir"|"transferir"|"recolher";item?:DistribuicaoRow};dados:DistribuicaoRow[];onClose:()=>void;onSave:(r:DistribuicaoRow)=>void}){
  const item=modal.item; const [quantidade,setQuantidade]=useState(""); const [destino,setDestino]=useState(""); const [justificativa,setJustificativa]=useState(""); const [erro,setErro]=useState(""); const quadros=[...new Set(dados.map(r=>r.quadro))]; const [quadro,setQuadro]=useState(item?.quadro??quadros[0]);
  const salvar=(e:FormEvent)=>{e.preventDefault();const q=Number(quantidade);if(!q||q<=0){setErro("Informe uma quantidade maior que zero.");return}if(modal.tipo!=="recolher"&&!destino){setErro("Informe a unidade de destino.");return}if(!justificativa){setErro("Informe a justificativa.");return}const base=item??dados.find(r=>r.quadro===quadro)!;if((modal.tipo==="transferir"||modal.tipo==="recolher")&&q>base.distribuido){setErro("A quantidade não pode ultrapassar o total distribuído.");return}if(modal.tipo==="recolher")onSave({...base,distribuido:base.distribuido-q});else if(modal.tipo==="transferir")onSave({...base,unidade:destino,distribuido:q,ocupado:0,comprometido:0,bloqueado:0,id:0,situacao:"Regular"});else onSave({...base,id:0,unidade:destino,distribuido:q,ocupado:0,comprometido:0,bloqueado:0,situacao:"Regular"})};
  const titulo=modal.tipo==="distribuir"?"Nova distribuição":modal.tipo==="transferir"?"Transferir vagas":"Recolher vagas";
  return <div className="prototype-distrib-backdrop" onMouseDown={onClose}><form className="prototype-distrib-modal" onSubmit={salvar} onMouseDown={e=>e.stopPropagation()}><header><div><span>Quadro Autorizado</span><h2>{titulo}</h2></div><button type="button" onClick={onClose}><i className="pi pi-times"/></button></header>{erro&&<div className="prototype-distrib-modal-error"><i className="pi pi-exclamation-circle"/>{erro}</div>}<div className="prototype-distrib-modal-body"><label><span>Quadro autorizado *</span><select value={quadro} disabled={Boolean(item)} onChange={e=>setQuadro(e.target.value)}>{quadros.map(v=><option key={v}>{v}</option>)}</select></label>{item&&<div className="prototype-distrib-origin"><span>Origem</span><strong>{item.orgao} • {item.unidade}</strong><small>{item.distribuido} vagas distribuídas</small></div>}{modal.tipo!=="recolher"&&<label><span>Unidade de destino *</span><select value={destino} onChange={e=>setDestino(e.target.value)}><option value="">Selecione</option><option>Administração Sistêmica</option><option>Gestão de Pessoas</option><option>Tecnologia da Informação</option><option>Gabinete</option><option>Unidade Regional</option></select></label>}<label><span>Quantidade *</span><input type="number" min="1" value={quantidade} onChange={e=>setQuantidade(e.target.value)}/></label><label className="full"><span>Justificativa *</span><textarea rows={3} value={justificativa} onChange={e=>setJustificativa(e.target.value)}/></label><label className="full"><span>Processo administrativo</span><input placeholder="ÓRGÃO-PRO-AAAA/NNNNN"/></label></div><footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" type="submit"><i className="pi pi-check"/> Confirmar</button></footer></form></div>
}

function MemoriaSaldo({item,onClose}:{item:DistribuicaoRow;onClose:()=>void}){const disp=disponivel(item);return <div className="prototype-distrib-backdrop" onMouseDown={onClose}><section className="prototype-distrib-modal memoria" onMouseDown={e=>e.stopPropagation()}><header><div><span>Memória de cálculo</span><h2>{item.cargo}</h2><p>{item.orgao} • {item.unidade}</p></div><button onClick={onClose}><i className="pi pi-times"/></button></header><div className="prototype-saldo-formula"><div><span>Distribuído</span><strong>{item.distribuido}</strong></div><i className="pi pi-minus"/><div><span>Ocupado</span><strong>{item.ocupado}</strong></div><i className="pi pi-minus"/><div><span>Comprometido</span><strong>{item.comprometido}</strong></div><i className="pi pi-minus"/><div><span>Bloqueado</span><strong>{item.bloqueado}</strong></div><i className="pi pi-equals"/><div className={disp<0?"danger":"result"}><span>{disp<0?"Excedente":"Disponível"}</span><strong>{Math.abs(disp)}</strong></div></div><div className="prototype-saldo-details"><dl><div><dt>Quadro autorizado</dt><dd>{item.quadro}</dd></div><div><dt>Autorizado total</dt><dd>{item.autorizado}</dd></div><div><dt>Vigência</dt><dd>{item.vigencia}</dd></div><div><dt>Data de referência</dt><dd>15/07/2026</dd></div></dl><div className="prototype-distrib-notice"><i className="pi pi-info-circle"/><span>Na Etapa 4, cada parcela poderá ser aberta nas movimentações que formaram este saldo.</span></div></div><footer><button className="primary" onClick={onClose}>Fechar</button></footer></section></div>}
