import type { CessaoFuncional, ComprometimentoVaga, EventoTemporalControleVagas, ExcecaoJudicialVaga, MovimentacaoFuncional, MovimentoVagaIndividual, OcupacaoVaga, QuadroAutorizadoRow, Vaga } from "./types";
const dataIso=(valor:string)=>{if(/^\d{4}-\d{2}-\d{2}/.test(valor))return valor.slice(0,10);const p=valor.slice(0,10).split("/");return p.length===3?`${p[2]}-${p[1]}-${p[0]}`:valor};
export function construirHistoricoTemporal(dados:{quadros:readonly QuadroAutorizadoRow[];vagas:readonly Vaga[];comprometimentos:readonly ComprometimentoVaga[];ocupacoes:readonly OcupacaoVaga[];cessoes:readonly CessaoFuncional[];movimentacoesFuncionais:readonly MovimentacaoFuncional[];movimentos:readonly MovimentoVagaIndividual[];excecoesJudiciais:readonly ExcecaoJudicialVaga[]}):EventoTemporalControleVagas[]{const eventos:EventoTemporalControleVagas[]=[];
 dados.quadros.forEach((q)=>eventos.push({id:`TMP-Q-${q.id}-${q.versao}`,dominio:"QUADRO_LEGAL",entidadeId:String(q.id),dataEfeito:dataIso(q.inicioVigencia||q.atualizadoEm),registradoEm:q.atualizadoEm,tipo:"VERSAO_QUADRO",descricao:`${q.codigo} v${q.versao}: ${q.autorizadas} vagas autorizadas.`,origem:"Quadro Legal",processo:q.processo}));
 dados.vagas.forEach((v)=>v.historico.forEach((h)=>eventos.push({id:`TMP-${h.id}`,dominio:"VAGA",entidadeId:v.id,vagaId:v.id,dataEfeito:dataIso(h.dataEfeito),registradoEm:h.ocorridoEm,tipo:h.tipo,descricao:h.descricao,origem:h.origem,processo:h.processo})));
 dados.comprometimentos.forEach((c)=>c.fases.forEach((f)=>{if(f.iniciadaEm)eventos.push({id:`TMP-${f.id}-I`,dominio:"COMPROMETIMENTO",entidadeId:c.id,vagaId:c.vagaId,dataEfeito:dataIso(f.iniciadaEm),registradoEm:f.iniciadaEm,tipo:"FASE_INICIADA",descricao:f.nome,origem:f.origem,processo:f.processo});if(f.concluidaEm)eventos.push({id:`TMP-${f.id}-C`,dominio:"COMPROMETIMENTO",entidadeId:c.id,vagaId:c.vagaId,dataEfeito:dataIso(f.concluidaEm),registradoEm:f.concluidaEm,tipo:"FASE_CONCLUIDA",descricao:f.nome,origem:f.origem,processo:f.processo})}));
 dados.ocupacoes.forEach((o)=>o.eventos.forEach((e)=>eventos.push({id:`TMP-${e.id}`,dominio:"OCUPACAO",entidadeId:o.id,vagaId:o.vagaId,dataEfeito:dataIso(e.data),registradoEm:e.registradoEm,tipo:e.tipo,descricao:e.descricao,origem:e.origem,processo:e.processo})));
 dados.cessoes.forEach((c)=>{eventos.push({id:`TMP-${c.id}-I`,dominio:"CESSAO",entidadeId:c.id,vagaId:c.vagaId,dataEfeito:dataIso(c.inicio),registradoEm:c.inicio,tipo:"CESSAO_INICIADA",descricao:`Exercício em ${c.orgaoCessionario}; vaga mantida em ${c.orgaoCedente}.`,origem:"Vida Funcional",processo:c.processo});if(c.encerradaEm)eventos.push({id:`TMP-${c.id}-F`,dominio:"CESSAO",entidadeId:c.id,vagaId:c.vagaId,dataEfeito:dataIso(c.encerradaEm),registradoEm:c.encerradaEm,tipo:"CESSAO_ENCERRADA",descricao:c.motivoEncerramento??"Cessão encerrada.",origem:"Vida Funcional",processo:c.processo})});
 dados.movimentacoesFuncionais.forEach((m)=>m.historico.forEach((h)=>eventos.push({id:`TMP-${m.id}-${h.id}`,dominio:"MOVIMENTACAO_FUNCIONAL",entidadeId:m.id,vagaId:m.vagaOrigemId,dataEfeito:dataIso(h.data),registradoEm:h.registradoEm,tipo:`${m.tipo}_${h.tipo}`,descricao:h.descricao,origem:h.origem,processo:m.processo})));
 dados.movimentos.forEach((m)=>eventos.push({id:`TMP-${m.id}`,dominio:"DISTRIBUICAO",entidadeId:m.id,vagaId:m.vagaId,dataEfeito:m.dataEfeito,registradoEm:m.registradoEm,tipo:m.tipo,descricao:m.justificativa,origem:"Distribuição de Vagas",processo:m.processo}));
 dados.excecoesJudiciais.forEach((e)=>eventos.push({id:`TMP-${e.id}`,dominio:"EXCECAO_JUDICIAL",entidadeId:e.id,dataEfeito:dataIso(e.inicio),registradoEm:e.inicio,tipo:"DECISAO_JUDICIAL",descricao:`${e.cargo} • ${e.pessoaNome}`,origem:"Assessoria Jurídica",processo:e.processo}));return eventos.sort((a,b)=>a.dataEfeito.localeCompare(b.dataEfeito)||a.registradoEm.localeCompare(b.registradoEm));}
export const eventosAte=(eventos:readonly EventoTemporalControleVagas[],data:string)=>eventos.filter((e)=>e.dataEfeito<=data);
