import {describe,expect,it} from "vitest";
import {controleVagasStore,type ControleVagasState} from "./controleVagasStore";
import {calcularPosicaoVaga} from "./distribuicaoIndividual";
import {construirHistoricoTemporal,eventosAte} from "./historicoTemporal";
import {cancelarAposPublicacao} from "./movimentacoesEspeciais";
import {efetivarRemocaoInterna} from "./movimentacoesBasicas";
import {registrarCessao} from "./cessoes";
import {criarComprometimentosTransferencia,efetivarTransferenciaAtomica,validarCompatibilidadeTransferencia} from "./transferencias";
import type {MovimentacaoFuncional} from "./types";
const responsavel={usuarioId:"TESTE",nome:"Teste integrado",unidade:"SEPLAG",perfil:"Teste",data:"2026-07-24"};
function preparar(data="2026-08-01"){const base=controleVagasStore.getState();const ocupacao=base.ocupacoes.find(o=>o.situacao==="ATIVA"&&base.vagas.some(v=>v.id===o.vagaId&&v.estado==="OCUPADA"))!;const origem=base.vagas.find(v=>v.id===ocupacao.vagaId)!;const destino=base.vagas.find(v=>v.id!==origem.id&&v.estado==="DISPONIVEL"&&v.tipo===origem.tipo&&v.cargo===origem.cargo&&v.carreira===origem.carreira&&!base.ocupacoes.some(o=>o.vagaId===v.id&&o.situacao==="ATIVA")&&!base.comprometimentos.some(c=>c.vagaId===v.id&&c.situacao==="ATIVO"))!;const orgaoDestino=calcularPosicaoVaga(destino,base.movimentos,"2026-07-24").orgaoDistribuicao!;const compatibilidade=validarCompatibilidadeTransferencia(origem,destino,ocupacao,base,orgaoDestino);const reservas=criarComprometimentosTransferencia("INT",ocupacao,destino.id,"PROC-INT",data);const mov:MovimentacaoFuncional={id:"MOV-INT",tipo:"TRANSFERENCIA",subtipo:"TRANSFERENCIA_ENTRE_VAGAS",situacao:"PUBLICADA",pessoaId:ocupacao.pessoaId,vinculoId:ocupacao.vinculoId,ocupacaoOrigemId:ocupacao.id,vagaOrigemId:origem.id,vagaDestinoId:destino.id,orgaoOrigem:ocupacao.orgaoLotacao,unidadeOrigem:ocupacao.orgaoLotacao,orgaoDestino,unidadeDestino:"Unidade destino",processo:"PROC-INT",ato:"ATO-INT",detalhesTransferencia:{orgaoDestino,unidadeDestino:"Unidade destino",vagaDestinoId:destino.id,dataEfeito:data,compatibilidade,simuladaEm:"2026-07-24",situacaoOperacional:"RESERVADA"},dataSolicitacao:"2026-07-24",dataEfeito:data,criadoEm:"2026-07-24",atualizadoEm:"2026-07-24",registradoPor:responsavel,comprometimentos:{origem:reservas.origem.id,destino:reservas.destino.id},validacoes:[],fases:[],historico:[]};const state:ControleVagasState={...base,comprometimentos:[reservas.origem,reservas.destino,...base.comprometimentos],movimentacoesFuncionais:[mov,...base.movimentacoesFuncionais]};return{state,mov,ocupacao,origem,destino}}
describe("Etapa 10 — integração do Controle de Vagas",()=>{
 it("transfere um vínculo entre duas vagas em uma transação",()=>{const c=preparar();const r=efetivarTransferenciaAtomica(c.state,c.mov.id);expect(r.erro).toBeUndefined();expect(r.state.vagas.find(v=>v.id===c.origem.id)?.estado).toBe("DISPONIVEL");expect(r.state.vagas.find(v=>v.id===c.destino.id)?.estado).toBe("OCUPADA")});
 it("bloqueia transferência por incompatibilidade",()=>{const base=controleVagasStore.getState(),ocupacao=base.ocupacoes.find(o=>o.situacao==="ATIVA")!,origem=base.vagas.find(v=>v.id===ocupacao.vagaId)!,destino=base.vagas.find(v=>v.id!==origem.id&&v.cargo!==origem.cargo)!;const r=validarCompatibilidadeTransferencia(origem,destino,ocupacao,base,destino.orgaoTitular);expect(r.valida).toBe(false);expect(r.mensagens.length).toBeGreaterThan(0)});
 it("cancela uma transferência publicada antes da efetivação",()=>{const c=preparar();const r=cancelarAposPublicacao(c.state,c.mov.id,"Ato revogado");expect(r.erro).toBeUndefined();expect(r.state.movimentacoesFuncionais.find(m=>m.id===c.mov.id)?.situacao).toBe("CANCELADA");expect(r.state.vagas.find(v=>v.id===c.origem.id)?.estado).toBe("OCUPADA");expect(r.state.comprometimentos.filter(x=>Object.values(c.mov.comprometimentos).includes(x.id)).every(x=>x.situacao==="CANCELADO")).toBe(true)});
 it("agenda uma efetivação futura sem alterar as vagas e efetiva na data",()=>{const c=preparar("2026-09-01");const antes=efetivarTransferenciaAtomica(c.state,c.mov.id,"2026-08-01");expect(antes.state.movimentacoesFuncionais.find(m=>m.id===c.mov.id)?.situacao).toBe("AGENDADA_EFETIVACAO");expect(antes.state.vagas.find(v=>v.id===c.origem.id)?.estado).toBe("OCUPADA");const depois=efetivarTransferenciaAtomica(antes.state,c.mov.id,"2026-09-01");expect(depois.state.vagas.find(v=>v.id===c.destino.id)?.estado).toBe("OCUPADA")});
 it("reconstrói a consulta histórica antes e depois da transferência",()=>{const c=preparar();const r=efetivarTransferenciaAtomica(c.state,c.mov.id);const eventos=construirHistoricoTemporal(r.state);expect(eventosAte(eventos,"2026-07-31").some(e=>e.entidadeId===c.mov.id&&e.tipo.includes("EFETIVACAO"))).toBe(false);expect(eventosAte(eventos,"2026-08-01").some(e=>e.entidadeId===c.mov.id&&e.tipo.includes("EFETIVACAO"))).toBe(true)});
 it("confirma que cessão altera exercício sem desocupar a vaga",()=>{const base=controleVagasStore.getState(),ocupacao=base.ocupacoes.find(o=>o.situacao==="ATIVA"&&base.vagas.find(v=>v.id===o.vagaId)?.carreira==="Gestão Governamental")!,vaga=base.vagas.find(v=>v.id===ocupacao.vagaId)!;const r=registrarCessao(vaga,ocupacao,{destino:"CGE",inicio:"2026-08-01",onus:"DESTINO",processo:"PROC-CES",ato:"ATO-CES"});expect(r.validacao.valido).toBe(true);expect(r.ocupacao.vagaId).toBe(ocupacao.vagaId);expect(r.ocupacao.orgaoExercicio).toBe("CGE");expect(vaga.estado).toBe("OCUPADA")});
 it("confirma que remoção interna mantém a vaga",()=>{const ocupacao=controleVagasStore.getState().ocupacoes.find(o=>o.situacao==="ATIVA")!;const r=efetivarRemocaoInterna(ocupacao,{orgaoDestino:ocupacao.orgaoLotacao,unidadeDestino:"Nova unidade",data:"2026-08-01",processo:"PROC-REM"});expect(r.vagaId).toBe(ocupacao.vagaId);expect(r.unidadeLotacao).toBe("Nova unidade")});
 it("confirma que transferência encerra a origem e cria ocupação no destino",()=>{const c=preparar();const r=efetivarTransferenciaAtomica(c.state,c.mov.id);expect(r.state.ocupacoes.find(o=>o.id===c.ocupacao.id)?.situacao).toBe("ENCERRADA");const nova=r.state.ocupacoes.find(o=>o.vinculoId===c.ocupacao.vinculoId&&o.vagaId===c.destino.id&&o.situacao==="ATIVA");expect(nova).toBeTruthy()});
});
