import type { QuadroAutorizadoRow, RegraEvento, Vaga } from "./types";
import { gerarVagasDoQuadro } from "./vagaUtils";

export const regrasControleVagasMock: RegraEvento[] = [
  {
    id: 1,
    evento: "Ampliação legal do quadro",
    origem: "Lei ou ato autorizativo",
    impacto: "Autorização",
    comportamento:
      "Cria novas vagas individualizadas e numeradas após a vigência",
    validacao: "Provisória",
  },
  {
    id: 2,
    evento: "Redução legal do quadro",
    origem: "Lei ou ato autorizativo",
    impacto: "Autorização",
    comportamento:
      "Extingue vagas disponíveis e marca ocupadas para extinção progressiva",
    validacao: "Provisória",
  },
  {
    id: 3,
    evento: "Transformação de cargo",
    origem: "Lei ou ato autorizativo",
    impacto: "Autorização",
    comportamento:
      "Preserva a identidade e o histórico da vaga, registrando cargo de origem e destino",
    validacao: "Provisória",
  },
  {
    id: 4,
    evento: "Início de processo de ocupação",
    origem: "Ingresso do Servidor",
    impacto: "Comprometimento",
    comportamento: "Adiciona fases à vaga disponível sem alterar seu estado",
    validacao: "Provisória",
  },
  {
    id: 5,
    evento: "Efetivo exercício",
    origem: "Vida funcional",
    impacto: "Ocupação",
    comportamento: "Relaciona um vínculo à vaga e altera o estado para ocupada",
    validacao: "Provisória",
  },
  {
    id: 6,
    evento: "Início de processo de disponibilização",
    origem: "Vida funcional",
    impacto: "Comprometimento",
    comportamento: "Adiciona fases à vaga ocupada sem antecipar sua liberação",
    validacao: "Provisória",
  },
  {
    id: 7,
    evento: "Encerramento definitivo do vínculo",
    origem: "Vida funcional",
    impacto: "Liberação",
    comportamento: "Encerra a ocupação nominal e torna a vaga disponível",
    validacao: "Provisória",
  },
  {
    id: 8,
    evento: "Cancelamento de processo",
    origem: "Sistema de origem",
    impacto: "Liberação",
    comportamento: "Cancela as fases ativas sem alterar o estado da vaga",
    validacao: "Provisória",
  },
  {
    id: 9,
    evento: "Cessão funcional",
    origem: "Vida funcional",
    impacto: "Ocupação",
    comportamento:
      "Altera apenas o órgão de exercício; a titularidade da vaga é preservada",
    validacao: "Provisória",
  },
  {
    id: 10,
    evento: "Movimento de distribuição",
    origem: "Controle de Vagas",
    impacto: "Autorização",
    comportamento:
      "Distribui ou redistribui a vaga numerada por ato formal sem apagar movimentos anteriores",
    validacao: "Provisória",
  },
  {
    id: 11,
    evento: "Decisão judicial extraquadro",
    origem: "Decisão judicial",
    impacto: "Exceção",
    comportamento:
      "Registra vínculo excepcional separado das vagas legais e não amplia o quadro",
    validacao: "Provisória",
  },
  {
    id: 12,
    evento: "Movimento retroativo",
    origem: "Sistema de origem",
    impacto: "Exceção",
    comportamento:
      "Recalcula a posição temporal desde a data de efeito, preservando a data de registro",
    validacao: "Provisória",
  },
];
export const pendenciasRegrasMock = [
  "Marco definitivo e documento que comprovam o efetivo exercício",
  "Eventos definitivos de disponibilização por tipo de vínculo",
  "Órgãos de exercício permitidos por carreira e hipóteses de autorização especial",
  "Critério de encerramento de ocupação judicial extraquadro",
  "Periodicidade de homologação da metodologia e das taxas de projeção",
];

export const quadrosAutorizadosMock: QuadroAutorizadoRow[] = [
  {
    id: 1,
    codigo: "QA-0001",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Gestão Governamental",
    cargo: "Analista Administrativo",
    perfilProfissional: "Administração",
    orgao: "SEPLAG",
    abrangencia: "Órgão específico",
    autorizadas: 120,
    ocupadas: 108,
    comprometidas: 4,
    bloqueadas: 0,
    inicioVigencia: "01/01/2025",
    fimVigencia: "",
    ato: "Lei Complementar nº 550/2014",
    processo: "SEPLAG-PRO-2025/00120",
    situacao: "Vigente",
    versao: 3,
    atualizadoEm: "10/07/2026",
  },
  {
    id: 2,
    codigo: "QA-0002",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Saúde Pública",
    cargo: "Técnico em Enfermagem",
    perfilProfissional: "",
    orgao: "SES",
    abrangencia: "Órgão específico",
    autorizadas: 500,
    ocupadas: 472,
    comprometidas: 8,
    bloqueadas: 2,
    inicioVigencia: "01/03/2025",
    fimVigencia: "",
    ato: "Lei nº 12.104/2023",
    processo: "SES-PRO-2025/00871",
    situacao: "Vigente",
    versao: 2,
    atualizadoEm: "08/07/2026",
  },
  {
    id: 3,
    codigo: "QA-0003",
    tipoQuadro: "Comissionado",
    vinculo: "Exclusivamente comissionado",
    regime: "Administrativo",
    carreira: "Direção e Assessoramento",
    cargo: "DGA-6",
    perfilProfissional: "",
    orgao: "SEFAZ",
    abrangencia: "Órgão específico",
    situacaoVigencia: "ENCERRADO",
    dataAtivacao: "2026-01-01",
    dataEncerramento: "2026-12-31",
    motivoEncerramento: "Encerramento programado",
    autorizadas: 42,
    ocupadas: 40,
    comprometidas: 1,
    bloqueadas: 0,
    inicioVigencia: "01/01/2026",
    fimVigencia: "",
    ato: "Lei Complementar nº 266/2006",
    processo: "SEFAZ-PRO-2026/00045",
    situacao: "Vigente",
    versao: 1,
    atualizadoEm: "02/07/2026",
  },
  {
    id: 4,
    codigo: "QA-0004",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Perícia Oficial e Identificação Técnica",
    cargo: "Perito Oficial Criminal",
    perfilProfissional: "Perícia Criminal",
    orgao: "POLITEC",
    abrangencia: "Órgão específico",
    formaDestinacaoLegal: "DEFINIDA_NA_LEI",
    orgaosDefinidosLei: ["POLITEC"],
    documentosLegaisIds: ["lei-8321-2005"],
    situacaoVigencia: "ATIVO",
    dataAtivacao: "2025-02-01",
    autorizadas: 90,
    ocupadas: 76,
    comprometidas: 14,
    bloqueadas: 0,
    inicioVigencia: "01/02/2025",
    fimVigencia: "",
    ato: "Lei nº 8.321/2005",
    processo: "POLITEC-PRO-2025/00317",
    situacao: "Vigente",
    versao: 1,
    atualizadoEm: "05/07/2026",
  },
  {
    id: 5,
    codigo: "QA-0005",
    tipoQuadro: "Comissionado",
    vinculo: "Exclusivamente comissionado",
    regime: "Administrativo",
    carreira: "Direção e Assessoramento",
    cargo: "DGA-4",
    perfilProfissional: "",
    orgao: "CASA CIVIL",
    abrangencia: "Órgão específico",
    formaDestinacaoLegal: "DEFINIDA_NA_LEI",
    orgaosDefinidosLei: ["CASA CIVIL"],
    documentosLegaisIds: ["lc-846-2026"],
    situacaoVigencia: "ATIVO",
    dataAtivacao: "2026-01-01",
    autorizadas: 25,
    ocupadas: 19,
    comprometidas: 6,
    bloqueadas: 0,
    inicioVigencia: "01/01/2026",
    fimVigencia: "",
    ato: "LC nº 846/2026",
    processo: "CASACIVIL-PRO-2026/00105",
    situacao: "Vigente",
    versao: 1,
    atualizadoEm: "06/07/2026",
  },
  {
    id: 6,
    codigo: "QA-0006",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Segurança Pública",
    cargo: "Investigador de Polícia",
    perfilProfissional: "",
    orgao: "PJC",
    abrangencia: "Quadro geral",
    autorizadas: 850,
    ocupadas: 822,
    comprometidas: 17,
    bloqueadas: 0,
    inicioVigencia: "01/01/2026",
    fimVigencia: "",
    ato: "Lei Complementar nº 407/2010",
    processo: "PJC-PRO-2026/00091",
    situacao: "Vigente",
    versao: 4,
    atualizadoEm: "09/07/2026",
  },
  {
    id: 7,
    codigo: "QA-0007",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Carreira dos Profissionais da Área Meio",
    cargo: "Técnico Administrativo",
    perfilProfissional: "",
    orgao: "ESTADO DE MATO GROSSO",
    abrangencia: "Destinação definida na lei",
    formaDestinacaoLegal: "DEFINIDA_NA_LEI",
    orgaosDefinidosLei: ["SEPLAG", "SEFAZ", "SEMA"],
    quantitativosLegaisPorOrgao: [
      { orgao: "SEPLAG", quantidade: 20 },
      { orgao: "SEFAZ", quantidade: 15 },
      { orgao: "SEMA", quantidade: 10 },
    ],
    documentosLegaisIds: ["lei-10052-2014", "decreto-1447-2022"],
    situacaoVigencia: "EXTINTO",
    dataAtivacao: "2026-06-01",
    dataExtincao: "2027-01-31",
    motivoExtincao: "Extinção progressiva programada",
    autorizadas: 45,
    ocupadas: 34,
    comprometidas: 3,
    bloqueadas: 0,
    inicioVigencia: "01/06/2026",
    fimVigencia: "",
    ato: "Lei nº 10.052/2014; Decreto nº 1.447/2022",
    processo: "SEPLAG-PRO-2026/02140",
    situacao: "Vigente",
    versao: 1,
    atualizadoEm: "18/07/2026",
  },
  {
    id: 8,
    codigo: "QA-0008",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Grupo Ocupacional TAF - Tributação, Arrecadação e Fiscalização",
    cargo: "Fiscal de Tributos Estaduais",
    perfilProfissional: "",
    orgao: "SEFAZ",
    abrangencia: "Destinação definida na lei",
    formaDestinacaoLegal: "DEFINIDA_NA_LEI",
    orgaosDefinidosLei: ["SEFAZ"],
    documentosLegaisIds: ["lc-851-2026"],
    situacaoVigencia: "ATIVO",
    dataAtivacao: "2026-09-01",
    autorizadas: 80,
    ocupadas: 0,
    comprometidas: 0,
    bloqueadas: 0,
    inicioVigencia: "01/09/2026",
    fimVigencia: "",
    ato: "LC nº 851/2026",
    processo: "SEFAZ-PRO-2026/04112",
    situacao: "Vigência futura",
    versao: 1,
    atualizadoEm: "18/07/2026",
  },
  {
    id: 9,
    codigo: "QA-0009",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Efetivo da Polícia Militar do Estado de Mato Grosso",
    cargo: "Coronel",
    perfilProfissional: "",
    orgao: "PM",
    abrangencia: "Órgão específico",
    formaDestinacaoLegal: "DEFINIDA_NA_LEI",
    orgaosDefinidosLei: ["PM"],
    situacaoVigencia: "ENCERRADO",
    dataAtivacao: "2024-01-01",
    dataEncerramento: "2026-06-30",
    motivoEncerramento: "Quadro encerrado por alteração legal",
    autorizadas: 24,
    ocupadas: 21,
    comprometidas: 1,
    bloqueadas: 0,
    inicioVigencia: "01/01/2024",
    fimVigencia: "",
    ato: "Lei Complementar estadual",
    processo: "PM-PRO-2024/00180",
    situacao: "Encerrada",
    versao: 2,
    atualizadoEm: "15/07/2026",
  },
  {
    id: 10,
    codigo: "QA-0010",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Efetivo do Corpo de Bombeiros Militar do Estado de Mato Grosso",
    cargo: "Capitão",
    perfilProfissional: "",
    orgao: "CBM",
    abrangencia: "Órgão específico",
    formaDestinacaoLegal: "DEFINIDA_NA_LEI",
    orgaosDefinidosLei: ["CBM"],
    situacaoVigencia: "EXTINTO",
    dataAtivacao: "2025-01-01",
    dataExtincao: "2026-05-31",
    motivoExtincao: "Quadro extinto por lei",
    autorizadas: 36,
    ocupadas: 31,
    comprometidas: 2,
    bloqueadas: 0,
    inicioVigencia: "01/01/2025",
    fimVigencia: "",
    ato: "Lei Complementar estadual",
    processo: "CBM-PRO-2025/00221",
    situacao: "Encerrada",
    versao: 1,
    atualizadoEm: "16/07/2026",
  },
  {
    id: 11,
    codigo: "QA-0011",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Quadro Administrativo da Procuradoria-Geral do Estado",
    cargo: "Analista da Procuradoria-Geral",
    perfilProfissional: "",
    orgao: "PGE",
    abrangencia: "Órgão específico",
    formaDestinacaoLegal: "DEFINIDA_NA_LEI",
    orgaosDefinidosLei: ["PGE"],
    autorizadas: 55,
    ocupadas: 47,
    comprometidas: 2,
    bloqueadas: 0,
    inicioVigencia: "01/04/2025",
    fimVigencia: "",
    ato: "Lei nº 7.554/2001",
    processo: "PGE-PRO-2025/00614",
    situacao: "Vigente",
    versao: 1,
    atualizadoEm: "17/07/2026",
  },
  {
    id: 12,
    codigo: "QA-0012",
    tipoQuadro: "Efetivo",
    vinculo: "Servidor efetivo",
    regime: "Estatutário",
    carreira: "Carreira dos Profissionais do Meio Ambiente",
    cargo: "Analista de Meio Ambiente",
    perfilProfissional: "",
    orgao: "ESTADO DE MATO GROSSO",
    abrangencia: "Distribuição posterior pelo Estado",
    formaDestinacaoLegal: "DISTRIBUICAO_POSTERIOR",
    documentosLegaisIds: ["lc-851-2026"],
    autorizadas: 30,
    ocupadas: 0,
    comprometidas: 0,
    bloqueadas: 0,
    inicioVigencia: "01/07/2026",
    fimVigencia: "",
    ato: "LC nº 851/2026",
    processo: "SEMA-PRO-2026/03081",
    situacao: "Vigente",
    versao: 1,
    atualizadoEm: "18/07/2026",
  },
];
export const vagasIndividualizadasMock: Vaga[] = quadrosAutorizadosMock
  .filter(
    (quadro) =>
      quadro.situacao === "Vigente" &&
      (quadro.tipoQuadro === "Efetivo" || quadro.tipoQuadro === "Comissionado"),
  )
  .flatMap(gerarVagasDoQuadro);
