import type { MovimentacaoFuncional, SituacaoMovimentacaoFuncional, SubtipoMovimentacaoFuncional, TipoMovimentacaoFuncional } from "./types";

const responsavel={usuarioId:"USR-001",nome:"Débora Almeida",unidade:"SEPLAG — Gestão de Pessoas",perfil:"Analista",data:"2026-07-23 09:00"};
const criar=(id:string,tipo:TipoMovimentacaoFuncional,subtipo:SubtipoMovimentacaoFuncional,situacao:SituacaoMovimentacaoFuncional,pessoaId:string,vinculoId:string,vagaOrigemId:string,orgaoOrigem:string,orgaoDestino:string,data:string):MovimentacaoFuncional=>({id,tipo,subtipo,situacao,pessoaId,vinculoId,ocupacaoOrigemId:`OCU-${vinculoId}`,vagaOrigemId,orgaoOrigem,unidadeOrigem:`${orgaoOrigem} — Unidade de origem`,orgaoDestino,unidadeDestino:`${orgaoDestino} — Unidade de destino`,processo:`SEPLAG-PRO-2026/${id.slice(-5)}`,fundamentoLegal:"Fundamentação em análise",motivo:"Movimentação funcional simulada",detalhesCessao:tipo==="CESSAO"?{esferaDestino:subtipo==="CESSAO_EXTERNA_OUTRO_PODER"?"OUTRO_PODER":"EXECUTIVO_ESTADUAL",unidadeDestino:`${orgaoDestino} — Unidade de destino`,motivo:"Colaboração institucional",cargoOuFuncao:"Função de assessoramento",inicio:data,fim:"2027-07-22",orgaoResponsavelFolha:orgaoOrigem,orgaoResponsavelCusto:orgaoDestino,semOnus:false,exigeRessarcimento:true,periodicidadeRessarcimento:"MENSAL",fonteRecursos:"Recursos próprios do cessionário",situacaoRessarcimento:"REGULAR",mesesInadimplencia:0,situacaoOperacional:situacao==="EFETIVADA"?"ATIVA":"AGENDADA",prorrogacoes:[],retificacoes:[]}:undefined,dataSolicitacao:data,dataEfeito:situacao==="EFETIVADA"?data:undefined,criadoEm:`${data} 09:00`,atualizadoEm:`${data} 10:30`,registradoPor:responsavel,comprometimentos:{},validacoes:[],fases:[{id:`${id}-F1`,nome:"Registro pela origem",ordem:1,situacao:"CONCLUIDA",iniciadaEm:data,concluidaEm:data,responsavel},{id:`${id}-F2`,nome:"Conferência documental",ordem:2,situacao:situacao==="EM_PREENCHIMENTO"?"PENDENTE":"CONCLUIDA"},{id:`${id}-F3`,nome:"Análise da SEPLAG",ordem:3,situacao:situacao==="EM_ANALISE"?"EM_ANDAMENTO":"PENDENTE"},{id:`${id}-F4`,nome:"Autorização e validação",ordem:4,situacao:situacao==="AGUARDANDO_VALIDACAO"?"EM_ANDAMENTO":"PENDENTE"},{id:`${id}-F5`,nome:"Publicação",ordem:5,situacao:situacao==="PUBLICADA"||situacao==="EFETIVADA"?"CONCLUIDA":"PENDENTE"},{id:`${id}-F6`,nome:"Efetivação",ordem:6,situacao:situacao==="EFETIVADA"?"CONCLUIDA":"PENDENTE"}],historico:[{id:`${id}-H1`,data,registradoEm:`${data} 09:00`,tipo:"REGISTRO",descricao:"Movimentação registrada pela unidade de origem.",origem:"Movimentações Funcionais",usuario:responsavel.nome,responsavel,situacaoPosterior:"EM_PREENCHIMENTO"}]});

export const movimentacoesFuncionaisMock:MovimentacaoFuncional[]=[
 criar("MOV-00001","CESSAO","CESSAO_EXTERNA_ORGAO_ESTADUAL","EM_ANALISE","PES-001","VIN-1045892","VAG-SEPLAG-ANALISTAAD-00001","SEPLAG","SEFAZ","2026-07-18"),
 criar("MOV-00002","CESSAO","CESSAO_EXTERNA_OUTRO_PODER","AGUARDANDO_VALIDACAO","PES-002","VIN-1046017","VAG-SEPLAG-ANALISTAAD-00002","SEPLAG","TJMT","2026-07-19"),
 criar("MOV-00003","REMOCAO","REMOCAO_INTERNA","PUBLICADA","PES-003","VIN-0005000","VAG-SEPLAG-ANALISTAAD-00003","SEPLAG","SEPLAG","2026-07-20"),
 criar("MOV-00004","TRANSFERENCIA","TRANSFERENCIA_ENTRE_VAGAS","EM_PREENCHIMENTO","PES-004","VIN-0005001","VAG-SEPLAG-ANALISTAAD-00004","SEPLAG","SEFAZ","2026-07-21"),
 criar("MOV-00005","TRANSFERENCIA","TRANSFERENCIA_POR_DECISAO_JUDICIAL","EFETIVADA","PES-005","VIN-0005002","VAG-SEPLAG-ANALISTAAD-00005","SEPLAG","PGE","2026-07-15"),
 criar("MOV-00006","REMOCAO","REMOCAO_A_PEDIDO","DEVOLVIDA","PES-006","VIN-0005003","VAG-SEPLAG-ANALISTAAD-00006","SEPLAG","SEPLAG","2026-07-22")
];