import type { ControleVagasState } from "./controleVagasStore";
import type { EventoMovimentacaoFuncional, MovimentacaoFuncional, OcupacaoVaga, ResponsavelMovimentacao } from "./types";

const agora="2026-07-24 14:30";
const evento=(mov:MovimentacaoFuncional,tipo:string,descricao:string,situacaoPosterior:MovimentacaoFuncional["situacao"]):EventoMovimentacaoFuncional=>({id:`${mov.id}-H${mov.historico.length+1}`,data:"2026-07-24",registradoEm:agora,tipo,descricao,origem:"Movimentações Funcionais — Operações especiais",usuario:"Sistema",situacaoAnterior:mov.situacao,situacaoPosterior});

function registrarEventoOcupacao(ocupacao:OcupacaoVaga,descricao:string,processo:string,data:string):OcupacaoVaga{return{...ocupacao,eventos:[...ocupacao.eventos,{id:`EVT-${ocupacao.id}-${ocupacao.eventos.length+1}`,tipo:"CORRECAO",data,registradoEm:agora,descricao,origem:"Movimentações Funcionais — Operações especiais",processo,usuario:"Sistema"}]}}

export function efetivarMovimentacaoEspecial(state:ControleVagasState,id:string):{state:ControleVagasState;erro?:string}{
 const mov=state.movimentacoesFuncionais.find((item)=>item.id===id);const d=mov?.detalhesEspeciais;if(!mov||!d)return{state,erro:"Movimentação especial não encontrada."};if(!["PUBLICADA","AGENDADA_EFETIVACAO"].includes(mov.situacao))return{state,erro:"A operação precisa estar publicada antes da efetivação."};
 const primeira=state.ocupacoes.find((item)=>item.id===mov.ocupacaoOrigemId&&item.situacao==="ATIVA");const segunda=state.ocupacoes.find((item)=>item.id===d.segundaOcupacaoId&&item.situacao==="ATIVA");if(!primeira)return{state,erro:"O vínculo principal não possui ocupação ativa."};if(["REMOCAO_PERMUTA","TRANSFERENCIA_COORDENADA"].includes(d.modalidade)&&!segunda)return{state,erro:"O segundo vínculo não possui ocupação ativa."};
 const data=mov.dataEfeito??"2026-07-24";let ocupacoes=state.ocupacoes;
 if(d.modalidade==="REMOCAO_PERMUTA"&&segunda){const a=registrarEventoOcupacao({...primeira,orgaoLotacao:segunda.orgaoLotacao,unidadeLotacao:segunda.unidadeLotacao,orgaoExercicio:segunda.orgaoExercicio,unidadeExercicio:segunda.unidadeExercicio},"Lotação e exercício alterados por permuta.",mov.processo,data);const b=registrarEventoOcupacao({...segunda,orgaoLotacao:primeira.orgaoLotacao,unidadeLotacao:primeira.unidadeLotacao,orgaoExercicio:primeira.orgaoExercicio,unidadeExercicio:primeira.unidadeExercicio},"Lotação e exercício alterados por permuta.",mov.processo,data);ocupacoes=ocupacoes.map((o)=>o.id===a.id?a:o.id===b.id?b:o)}
 if((d.modalidade==="DECISAO_JUDICIAL"||d.modalidade==="MOVIMENTACAO_RETROATIVA")&&mov.orgaoDestino){const a=registrarEventoOcupacao({...primeira,orgaoLotacao:mov.orgaoDestino,unidadeLotacao:mov.unidadeDestino,orgaoExercicio:mov.orgaoDestino,unidadeExercicio:mov.unidadeDestino},"Posição funcional alterada por movimentação especial.",mov.processo,data);ocupacoes=ocupacoes.map((o)=>o.id===a.id?a:o)}
 if(d.modalidade==="TRANSFERENCIA_COORDENADA"&&segunda){const a=registrarEventoOcupacao({...primeira,vagaId:segunda.vagaId,orgaoLotacao:segunda.orgaoLotacao,unidadeLotacao:segunda.unidadeLotacao,orgaoExercicio:segunda.orgaoExercicio,unidadeExercicio:segunda.unidadeExercicio},"Vínculo transferido para a vaga do segundo participante em operação coordenada.",mov.processo,data);const b=registrarEventoOcupacao({...segunda,vagaId:primeira.vagaId,orgaoLotacao:primeira.orgaoLotacao,unidadeLotacao:primeira.unidadeLotacao,orgaoExercicio:primeira.orgaoExercicio,unidadeExercicio:primeira.unidadeExercicio},"Vínculo transferido para a vaga do primeiro participante em operação coordenada.",mov.processo,data);ocupacoes=ocupacoes.map((o)=>o.id===a.id?a:o.id===b.id?b:o)}
 const e=evento(mov,"EFETIVACAO_ESPECIAL",`${d.modalidade.replaceAll("_"," ")} efetivada de forma atômica.`,"EFETIVADA");const atualizado={...mov,situacao:"EFETIVADA" as const,detalhesEspeciais:d,atualizadoEm:agora,fases:mov.fases.map((f)=>({...f,situacao:"CONCLUIDA" as const,concluidaEm:agora})),historico:[...mov.historico,e]};
 return{state:{...state,ocupacoes,movimentacoesFuncionais:state.movimentacoesFuncionais.map((m)=>m.id===id?atualizado:m)}};
}
export function retificarAtoMovimentacao(state:ControleVagasState,id:string,novoAto:string,justificativa:string,responsavel:ResponsavelMovimentacao):ControleVagasState{const mov=state.movimentacoesFuncionais.find((m)=>m.id===id);if(!mov?.detalhesEspeciais)return state;const r={id:`${id}-RET-${mov.detalhesEspeciais.retificacoes.length+1}`,campo:"ato",valorAnterior:mov.ato??"",valorPosterior:novoAto,ato:novoAto,justificativa,registradoEm:agora,responsavel};const e=evento(mov,"RETIFICACAO_ATO",`Ato retificado de ${mov.ato??"não informado"} para ${novoAto}. Motivo: ${justificativa}`,mov.situacao);return{...state,movimentacoesFuncionais:state.movimentacoesFuncionais.map((m)=>m.id===id?{...m,ato:novoAto,detalhesEspeciais:{...m.detalhesEspeciais!,retificacoes:[...m.detalhesEspeciais!.retificacoes,r]},atualizadoEm:agora,historico:[...m.historico,e]}:m)}}
export function cancelarAposPublicacao(state:ControleVagasState,id:string,motivo:string):{state:ControleVagasState;erro?:string}{const mov=state.movimentacoesFuncionais.find((m)=>m.id===id);if(!mov||!["PUBLICADA","AGENDADA_EFETIVACAO"].includes(mov.situacao))return{state,erro:"Somente uma movimentação publicada e ainda não efetivada pode ser cancelada."};const e=evento(mov,"CANCELAMENTO_POS_PUBLICACAO",`Operação cancelada após publicação. ${motivo}`,"CANCELADA");return{state:{...state,comprometimentos:state.comprometimentos.map((c)=>Object.values(mov.comprometimentos).includes(c.id)&&c.situacao==="ATIVO"?{...c,situacao:"CANCELADO" as const,fases:c.fases.map((f)=>f.situacao==="CONCLUIDA"?f:{...f,situacao:"CANCELADA" as const})}:c),movimentacoesFuncionais:state.movimentacoesFuncionais.map((m)=>m.id===id?{...m,situacao:"CANCELADA" as const,detalhesEspeciais:m.detalhesEspeciais?{...m.detalhesEspeciais,canceladaAposPublicacao:true,motivoCancelamento:motivo}:undefined,atualizadoEm:agora,historico:[...m.historico,e]}:m)}}}
export function retornarMovimentacaoEspecial(state:ControleVagasState,id:string,motivo:string):{state:ControleVagasState;erro?:string}{const mov=state.movimentacoesFuncionais.find((m)=>m.id===id);const d=mov?.detalhesEspeciais;if(!mov||!d||mov.situacao!=="EFETIVADA")return{state,erro:"Somente uma operação especial efetivada pode ser retornada."};const primeira=state.ocupacoes.find((o)=>o.id===mov.ocupacaoOrigemId&&o.situacao==="ATIVA");const segunda=state.ocupacoes.find((o)=>o.id===d.segundaOcupacaoId&&o.situacao==="ATIVA");if(!primeira||(["REMOCAO_PERMUTA","TRANSFERENCIA_COORDENADA"].includes(d.modalidade)&&!segunda))return{state,erro:"Não foi possível reconstruir as ocupações anteriores."};let ocupacoes=state.ocupacoes;if(!segunda&&(d.modalidade==="DECISAO_JUDICIAL"||d.modalidade==="MOVIMENTACAO_RETROATIVA")){const a=registrarEventoOcupacao({...primeira,orgaoLotacao:d.orgaoAnterior??primeira.orgaoLotacao,unidadeLotacao:d.unidadeAnterior,orgaoExercicio:d.orgaoAnterior??primeira.orgaoExercicio,unidadeExercicio:d.unidadeAnterior},"Retorno à posição anterior.",mov.processo,"2026-07-24");ocupacoes=ocupacoes.map((o)=>o.id===a.id?a:o)}if(segunda&&["REMOCAO_PERMUTA","TRANSFERENCIA_COORDENADA"].includes(d.modalidade)){const trocaVaga=d.modalidade==="TRANSFERENCIA_COORDENADA";const a=registrarEventoOcupacao({...primeira,vagaId:trocaVaga?segunda.vagaId:primeira.vagaId,orgaoLotacao:segunda.orgaoLotacao,unidadeLotacao:segunda.unidadeLotacao,orgaoExercicio:segunda.orgaoExercicio,unidadeExercicio:segunda.unidadeExercicio},"Retorno à posição anterior.",mov.processo,"2026-07-24");const b=registrarEventoOcupacao({...segunda,vagaId:trocaVaga?primeira.vagaId:segunda.vagaId,orgaoLotacao:primeira.orgaoLotacao,unidadeLotacao:primeira.unidadeLotacao,orgaoExercicio:primeira.orgaoExercicio,unidadeExercicio:primeira.unidadeExercicio},"Retorno à posição anterior.",mov.processo,"2026-07-24");ocupacoes=ocupacoes.map((o)=>o.id===a.id?a:o.id===b.id?b:o)}const e=evento(mov,"RETORNO_POSICAO_ANTERIOR",`Retorno registrado. ${motivo}`,"ENCERRADA");return{state:{...state,ocupacoes,movimentacoesFuncionais:state.movimentacoesFuncionais.map((m)=>m.id===id?{...m,situacao:"ENCERRADA" as const,detalhesEspeciais:{...m.detalhesEspeciais!,retornadaEm:agora,motivoRetorno:motivo},atualizadoEm:agora,historico:[...m.historico,e]}:m)}}}
