import { useMemo, useState, type FormEvent } from "react";
import { vagasIndividualizadasMock } from "./mockData";
import { ocupacoesVagasMock } from "./ocupacoesMock";
import { encerrarOcupacao, historicoOcupantesDaVaga, registrarEfetivoExercicio } from "./ocupacoes";
import type { OcupacaoVaga, Vaga } from "./types";
import "./ocupacoesNominais.css";

export function OcupacoesNominaisContent(){
 const [vagas,setVagas]=useState(vagasIndividualizadasMock);const [ocupacoes,setOcupacoes]=useState(ocupacoesVagasMock);const [busca,setBusca]=useState("");const [situacao,setSituacao]=useState("");const [detalhe,setDetalhe]=useState<OcupacaoVaga|null>(null);const [nova,setNova]=useState(false);const [encerrar,setEncerrar]=useState<OcupacaoVaga|null>(null);
 const filtradas=useMemo(()=>{const t=busca.toLowerCase().trim();return ocupacoes.filter((item)=>(!t||`${item.pessoaNome} ${item.matricula} ${item.vinculoId} ${item.vagaId}`.toLowerCase().includes(t))&&(!situacao||item.situacao===situacao))},[ocupacoes,busca,situacao]);
 const ativas=ocupacoes.filter((item)=>item.situacao==="ATIVA");const pessoasComMaisVinculos=new Set(ativas.filter((item,_,todos)=>todos.some((outro)=>outro.id!==item.id&&outro.pessoaId===item.pessoaId)).map((item)=>item.pessoaId));
 const criar=(vaga:Vaga,dados:Parameters<typeof registrarEfetivoExercicio>[1])=>{const r=registrarEfetivoExercicio(vaga,dados);setVagas((itens)=>itens.map((item)=>item.id===vaga.id?r.vaga:item));setOcupacoes((itens)=>[r.ocupacao,...itens]);setNova(false);setDetalhe(r.ocupacao)};
 const confirmarEncerramento=(ocupacao:OcupacaoVaga,data:string,motivo:string,processo:string)=>{const vaga=vagas.find((item)=>item.id===ocupacao.vagaId)!;const r=encerrarOcupacao(vaga,ocupacao,data,motivo,processo);setVagas((itens)=>itens.map((item)=>item.id===vaga.id?r.vaga:item));setOcupacoes((itens)=>itens.map((item)=>item.id===ocupacao.id?r.ocupacao:item));setEncerrar(null);setDetalhe(r.ocupacao)};
 return <div className="prototype-occup-page"><header className="prototype-occup-header"><div><span>Controle de Vagas</span><h1>Ocupações Nominais</h1><p>Cada ocupação relaciona uma vaga a um vínculo funcional específico.</p></div><button onClick={()=>setNova(true)}><i className="pi pi-user-plus"/> Registrar efetivo exercício</button></header><div className="prototype-occup-rule"><i className="pi pi-id-card"/><div><strong>A vaga é ocupada pelo vínculo, não diretamente pela pessoa</strong><span>Uma pessoa com duas matrículas mantém duas ocupações independentes e rastreáveis.</span></div></div>
 <section className="prototype-occup-kpis"><article><span>Ocupações ativas identificadas</span><strong>{ativas.length}</strong></article><article><span>Vagas com histórico anterior</span><strong>{new Set(ocupacoes.filter((i)=>i.situacao==="ENCERRADA").map((i)=>i.vagaId)).size}</strong></article><article className="dual"><span>Pessoas com mais de um vínculo</span><strong>{pessoasComMaisVinculos.size}</strong></article><article><span>Ocupações encerradas</span><strong>{ocupacoes.filter((i)=>i.situacao==="ENCERRADA").length}</strong></article></section>
 <section className="prototype-occup-card"><header><div><h2>Ocupantes atuais e anteriores</h2><p>Consulte pessoa, matrícula, vínculo, exercício e encerramento.</p></div><div><input value={busca} onChange={(e)=>setBusca(e.target.value)} placeholder="Pessoa, matrícula, vínculo ou vaga"/><select value={situacao} onChange={(e)=>setSituacao(e.target.value)}><option value="">Todas</option><option value="ATIVA">Ativas</option><option value="ENCERRADA">Encerradas</option></select></div></header><div className="prototype-occup-table"><table><thead><tr><th>Pessoa</th><th>Matrícula e vínculo</th><th>Vaga</th><th>Cargo</th><th>Órgão de exercício</th><th>Efetivo exercício</th><th>Encerramento</th><th>Situação</th><th/></tr></thead><tbody>{filtradas.map((item)=><tr key={item.id}><td><strong>{item.pessoaNome}</strong><small>{item.cpf}</small>{pessoasComMaisVinculos.has(item.pessoaId)&&<span className="prototype-occup-dual"><i className="pi pi-clone"/> Mais de um vínculo</span>}</td><td><strong>{item.matricula}</strong><small>{item.vinculoId} • {item.tipoVinculo}</small></td><td><strong className="prototype-occup-vaga">{item.vagaId}</strong></td><td>{item.cargo}</td><td>{item.orgaoExercicio}</td><td>{item.efetivoExercicioEm}</td><td>{item.encerradaEm??"—"}<small>{item.motivoEncerramento}</small></td><td><span className={`prototype-occup-status ${item.situacao.toLowerCase()}`}>{item.situacao}</span></td><td><div className="prototype-occup-actions"><button title="Detalhes" onClick={()=>setDetalhe(item)}><i className="pi pi-eye"/></button>{item.situacao==="ATIVA"&&<button title="Encerrar" onClick={()=>setEncerrar(item)}><i className="pi pi-sign-out"/></button>}</div></td></tr>)}</tbody></table></div></section>
 {detalhe&&<Detalhe ocupacao={detalhe} historico={historicoOcupantesDaVaga(ocupacoes,detalhe.vagaId)} onClose={()=>setDetalhe(null)} onEnd={()=>{setDetalhe(null);setEncerrar(detalhe)}}/>}{nova&&<NovaOcupacao vagas={vagas.filter((vaga)=>vaga.estado==="DISPONIVEL"&&!ocupacoes.some((item)=>item.vagaId===vaga.id&&item.situacao==="ATIVA"))} onClose={()=>setNova(false)} onCreate={criar}/>} {encerrar&&<Encerrar ocupacao={encerrar} onClose={()=>setEncerrar(null)} onConfirm={confirmarEncerramento}/>}</div>
}

function Detalhe({ocupacao,historico,onClose,onEnd}:{ocupacao:OcupacaoVaga;historico:OcupacaoVaga[];onClose:()=>void;onEnd:()=>void}){return <div className="prototype-occup-backdrop" onMouseDown={onClose}><section className="prototype-occup-modal" onMouseDown={(e)=>e.stopPropagation()}><header><div><span>Ocupação nominal</span><h2>{ocupacao.pessoaNome}</h2><p>{ocupacao.matricula} • {ocupacao.vinculoId}</p></div><button onClick={onClose}><i className="pi pi-times"/></button></header><div className="prototype-occup-identity"><i className="pi pi-link"/><div><strong>{ocupacao.vagaId}</strong><span>{ocupacao.cargo} • {ocupacao.orgaoExercicio}</span></div><span className={`prototype-occup-status ${ocupacao.situacao.toLowerCase()}`}>{ocupacao.situacao}</span></div><dl><div><dt>Pessoa</dt><dd>{ocupacao.pessoaNome}</dd></div><div><dt>CPF</dt><dd>{ocupacao.cpf}</dd></div><div><dt>Matrícula</dt><dd>{ocupacao.matricula}</dd></div><div><dt>Tipo de vínculo</dt><dd>{ocupacao.tipoVinculo}</dd></div><div><dt>Órgão do vínculo</dt><dd>{ocupacao.orgaoVinculo}</dd></div><div><dt>Lotação do vínculo</dt><dd>{ocupacao.orgaoLotacao}</dd></div><div><dt>Órgão de exercício</dt><dd>{ocupacao.orgaoExercicio}</dd></div><div><dt>Posse</dt><dd>{ocupacao.dataPosse??"Não informada"}</dd></div><div><dt>Efetivo exercício</dt><dd>{ocupacao.efetivoExercicioEm}</dd></div></dl><section className="prototype-occup-events"><h3>Eventos desta ocupação</h3>{ocupacao.eventos.map((evento)=><article key={evento.id}><i className="pi pi-check-circle"/><div><strong>{evento.tipo.replaceAll("_"," ")}</strong><span>{evento.descricao}</span><small>{evento.data} • {evento.origem} • {evento.usuario}</small></div></article>)}</section><section className="prototype-occup-previous"><h3>Todos os ocupantes desta vaga</h3><table><thead><tr><th>Pessoa</th><th>Matrícula</th><th>Início</th><th>Fim</th><th>Motivo</th></tr></thead><tbody>{historico.map((item)=><tr key={item.id}><td>{item.pessoaNome}</td><td>{item.matricula}</td><td>{item.efetivoExercicioEm}</td><td>{item.encerradaEm??"Atual"}</td><td>{item.motivoEncerramento??"—"}</td></tr>)}</tbody></table></section><footer><button onClick={onClose}>Fechar</button>{ocupacao.situacao==="ATIVA"&&<button className="end" onClick={onEnd}>Encerrar ocupação</button>}</footer></section></div>}

function NovaOcupacao({vagas,onClose,onCreate}:{vagas:Vaga[];onClose:()=>void;onCreate:(vaga:Vaga,dados:Parameters<typeof registrarEfetivoExercicio>[1])=>void}){const [vagaId,setVagaId]=useState("");const [nome,setNome]=useState("");const [cpf,setCpf]=useState("");const [vinculo,setVinculo]=useState("");const [matricula,setMatricula]=useState("");const [orgao,setOrgao]=useState("");const [exercicio,setExercicio]=useState("");const [posse,setPosse]=useState("");const [processo,setProcesso]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();const vaga=vagas.find((i)=>i.id===vagaId);if(!vaga||!nome||!vinculo||!matricula||!exercicio)return;onCreate(vaga,{pessoaId:`PES-${cpf.replace(/\D/g,"").slice(-5)||Date.now()}`,pessoaNome:nome,cpf,vinculoId:vinculo,matricula,tipoVinculo:vaga.tipo,orgaoVinculo:vaga.orgaoTitular,orgaoExercicio:orgao||vaga.orgaoTitular,dataPosse:posse,efetivoExercicioEm:exercicio,processo})};return <div className="prototype-occup-backdrop" onMouseDown={onClose}><form className="prototype-occup-modal form" onSubmit={submit} onMouseDown={(e)=>e.stopPropagation()}><header><div><span>Evento definitivo</span><h2>Registrar efetivo exercício</h2><p>A vaga será alterada para ocupada após a confirmação.</p></div><button type="button" onClick={onClose}><i className="pi pi-times"/></button></header><div className="prototype-occup-form"><label className="full"><span>Vaga disponível *</span><select value={vagaId} onChange={(e)=>setVagaId(e.target.value)}><option value="">Selecione</option>{vagas.slice(0,100).map((v)=><option key={v.id} value={v.id}>{v.id} — {v.cargo}</option>)}</select></label><label><span>Pessoa *</span><input value={nome} onChange={(e)=>setNome(e.target.value)}/></label><label><span>CPF</span><input value={cpf} onChange={(e)=>setCpf(e.target.value)}/></label><label><span>ID do vínculo *</span><input value={vinculo} onChange={(e)=>setVinculo(e.target.value)} placeholder="VIN-0000000"/></label><label><span>Matrícula *</span><input value={matricula} onChange={(e)=>setMatricula(e.target.value)}/></label><label><span>Órgão de exercício</span><input value={orgao} onChange={(e)=>setOrgao(e.target.value)}/></label><label><span>Data da posse</span><input type="date" value={posse} onChange={(e)=>setPosse(e.target.value)}/></label><label><span>Efetivo exercício *</span><input type="date" value={exercicio} onChange={(e)=>setExercicio(e.target.value)}/></label><label><span>Processo administrativo</span><input value={processo} onChange={(e)=>setProcesso(e.target.value)}/></label></div><footer><button type="button" onClick={onClose}>Cancelar</button><button className="save" type="submit">Confirmar efetivo exercício</button></footer></form></div>}

function Encerrar({ocupacao,onClose,onConfirm}:{ocupacao:OcupacaoVaga;onClose:()=>void;onConfirm:(o:OcupacaoVaga,d:string,m:string,p:string)=>void}){const [data,setData]=useState("");const [motivo,setMotivo]=useState("");const [processo,setProcesso]=useState("");return <div className="prototype-occup-backdrop" onMouseDown={onClose}><form className="prototype-occup-modal end-form" onSubmit={(e)=>{e.preventDefault();if(data&&motivo)onConfirm(ocupacao,data,motivo,processo)}} onMouseDown={(e)=>e.stopPropagation()}><header><div><span>Evento definitivo</span><h2>Encerrar ocupação</h2><p>{ocupacao.pessoaNome} • {ocupacao.matricula}</p></div><button type="button" onClick={onClose}><i className="pi pi-times"/></button></header><div className="prototype-occup-form"><label><span>Data do encerramento *</span><input type="date" value={data} onChange={(e)=>setData(e.target.value)}/></label><label><span>Motivo *</span><select value={motivo} onChange={(e)=>setMotivo(e.target.value)}><option value="">Selecione</option><option>Aposentadoria</option><option>Exoneração</option><option>Demissão</option><option>Falecimento</option><option>Posse em cargo inacumulável</option><option>Decisão judicial</option><option>Vacância</option></select></label><label className="full"><span>Processo administrativo</span><input value={processo} onChange={(e)=>setProcesso(e.target.value)}/></label></div><div className="prototype-occup-warning"><i className="pi pi-info-circle"/> A ocupação será encerrada e a vaga voltará ao estado disponível.</div><footer><button type="button" onClick={onClose}>Cancelar</button><button className="end" type="submit">Confirmar encerramento</button></footer></form></div>}
