import type { FatorProjecaoVagas, MetodologiaProjecao, TaxaEvasaoHistorica } from "./types";
const ids=(prefix:string,quantidade:number)=>Array.from({length:quantidade},(_,i)=>`${prefix}-${String(i+1).padStart(3,"0")}`);
export const fatoresProjecaoMock:FatorProjecaoVagas[]=[
 {id:"PRJ-001",categoria:"COMPULSORIA",cargo:"Analista Administrativo",orgao:"SEPLAG",quantidade:2,dataPrevista:"2027-03-01",probabilidade:1,vinculoIds:["VIN-PRJ-ANA-004","VIN-PRJ-ANA-005"],origem:"Vida Funcional",referencia:"Idade limite constitucional",atualizadoEm:"15/07/2026"},
 {id:"PRJ-002",categoria:"COMPULSORIA",cargo:"Técnico em Enfermagem",orgao:"SES",quantidade:7,dataPrevista:"2027-06-30",probabilidade:1,vinculoIds:ids("VIN-PRJ-TEC-C",7),origem:"Vida Funcional",referencia:"Idade limite constitucional",atualizadoEm:"15/07/2026"},
 {id:"PRJ-003",categoria:"COMPULSORIA",cargo:"Técnico em Enfermagem",orgao:"SES",quantidade:11,dataPrevista:"2029-06-30",probabilidade:1,vinculoIds:ids("VIN-PRJ-TEC-C2",11),origem:"Vida Funcional",referencia:"Idade limite constitucional",atualizadoEm:"15/07/2026"},
 {id:"PRJ-004",categoria:"ELEGIBILIDADE_APOSENTADORIA",cargo:"Analista Administrativo",orgao:"SEPLAG",quantidade:9,dataPrevista:"2027-07-01",probabilidade:.55,vinculoIds:ids("VIN-PRJ-ANA",9),origem:"Simulador Previdenciário",referencia:"Requisitos preenchidos",atualizadoEm:"14/07/2026"},
 {id:"PRJ-005",categoria:"ELEGIBILIDADE_APOSENTADORIA",cargo:"Técnico em Enfermagem",orgao:"SES",quantidade:28,dataPrevista:"2028-07-01",probabilidade:.55,vinculoIds:ids("VIN-PRJ-TEC-E",28),origem:"Simulador Previdenciário",referencia:"Requisitos preenchidos",atualizadoEm:"14/07/2026"},
 {id:"PRJ-006",categoria:"ELEGIBILIDADE_APOSENTADORIA",cargo:"DGA-6",orgao:"SEFAZ",quantidade:3,dataPrevista:"2027-12-01",probabilidade:.55,vinculoIds:ids("VIN-PRJ-DGA",3),origem:"Vida Funcional",referencia:"Critério analítico",atualizadoEm:"14/07/2026"},
 {id:"PRJ-007",categoria:"APOSENTADORIA_REQUERIDA",cargo:"Analista Administrativo",orgao:"SEPLAG",quantidade:3,dataPrevista:"2026-11-30",probabilidade:1,vinculoIds:ids("VIN-PRJ-ANA",3),origem:"Processo Previdenciário",referencia:"3 requerimentos em análise",atualizadoEm:"16/07/2026"},
 {id:"PRJ-008",categoria:"APOSENTADORIA_REQUERIDA",cargo:"Técnico em Enfermagem",orgao:"SES",quantidade:12,dataPrevista:"2027-02-28",probabilidade:1,vinculoIds:ids("VIN-PRJ-TEC-R",12),origem:"Processo Previdenciário",referencia:"12 requerimentos em análise",atualizadoEm:"16/07/2026"},
 {id:"PRJ-009",categoria:"EXONERACAO_CONHECIDA",cargo:"DGA-6",orgao:"SEFAZ",quantidade:2,dataPrevista:"2026-08-01",probabilidade:1,vinculoIds:ids("VIN-PRJ-DGA-X",2),origem:"Vida Funcional",referencia:"Atos em elaboração",atualizadoEm:"16/07/2026"},
 {id:"PRJ-010",categoria:"EXONERACAO_CONHECIDA",cargo:"Analista Administrativo",orgao:"SEPLAG",quantidade:1,dataPrevista:"2026-09-01",probabilidade:1,vinculoIds:["VIN-PRJ-ANA-X-001"],origem:"Vida Funcional",referencia:"Exoneração a pedido",atualizadoEm:"16/07/2026"},
];
export const taxasEvasaoMock:TaxaEvasaoHistorica[]=[
 {cargo:"Analista Administrativo",orgao:"SEPLAG",ano:2023,ocupadosMedios:102,desligamentosVoluntarios:4,taxa:.0392},{cargo:"Analista Administrativo",orgao:"SEPLAG",ano:2024,ocupadosMedios:105,desligamentosVoluntarios:5,taxa:.0476},{cargo:"Analista Administrativo",orgao:"SEPLAG",ano:2025,ocupadosMedios:107,desligamentosVoluntarios:4,taxa:.0374},
 {cargo:"Técnico em Enfermagem",orgao:"SES",ano:2023,ocupadosMedios:451,desligamentosVoluntarios:31,taxa:.0687},{cargo:"Técnico em Enfermagem",orgao:"SES",ano:2024,ocupadosMedios:460,desligamentosVoluntarios:36,taxa:.0783},{cargo:"Técnico em Enfermagem",orgao:"SES",ano:2025,ocupadosMedios:468,desligamentosVoluntarios:34,taxa:.0726},
 {cargo:"DGA-6",orgao:"SEFAZ",ano:2023,ocupadosMedios:37,desligamentosVoluntarios:7,taxa:.1892},{cargo:"DGA-6",orgao:"SEFAZ",ano:2024,ocupadosMedios:39,desligamentosVoluntarios:9,taxa:.2308},{cargo:"DGA-6",orgao:"SEFAZ",ano:2025,ocupadosMedios:40,desligamentosVoluntarios:8,taxa:.2},
];
export const metodologiasProjecaoMock:MetodologiaProjecao[]=[
 {id:"MET-PRJ-003",versao:3,nome:"Projeção de disponibilização de vagas",vigenteDesde:"01/07/2026",criadaEm:"28/06/2026 14:00",responsavel:"Superintendência de Gestão de Pessoas",status:"VIGENTE",pesosElegibilidade:{CONSERVADOR:.25,PROVAVEL:.55,AMPLIADO:.85},multiplicadoresEvasao:{CONSERVADOR:.7,PROVAVEL:1,AMPLIADO:1.3},regras:["Compulsórias, aposentadorias requeridas e exonerações conhecidas têm peso integral.","Elegibilidade recebe peso conforme o cenário.","Evasão usa a média ponderada dos três últimos anos.","Eventos sobre o mesmo vínculo são deduplicados pela prioridade: requerida, compulsória, elegibilidade."]},
 {id:"MET-PRJ-002",versao:2,nome:"Projeção de vacâncias",vigenteDesde:"01/01/2026",vigenteAte:"30/06/2026",criadaEm:"18/12/2025 09:30",responsavel:"Coordenadoria de Provimento",status:"SUBSTITUIDA",pesosElegibilidade:{CONSERVADOR:.2,PROVAVEL:.5,AMPLIADO:.8},multiplicadoresEvasao:{CONSERVADOR:.6,PROVAVEL:1,AMPLIADO:1.4},regras:["Média simples de evasão dos dois últimos anos.","Elegibilidade ponderada por cenário."]},
 {id:"MET-PRJ-001",versao:1,nome:"Estimativa inicial de vacâncias",vigenteDesde:"01/01/2025",vigenteAte:"31/12/2025",criadaEm:"10/12/2024 11:00",responsavel:"Coordenadoria de Provimento",status:"SUBSTITUIDA",pesosElegibilidade:{CONSERVADOR:0,PROVAVEL:.5,AMPLIADO:1},multiplicadoresEvasao:{CONSERVADOR:.5,PROVAVEL:1,AMPLIADO:1.5},regras:["Estimativa anual baseada em eventos conhecidos."]},
];
