export type ImpactoRegra = "Autorização" | "Comprometimento" | "Ocupação" | "Liberação" | "Bloqueio" | "Exceção";
export interface RegraEvento { id:number; evento:string; origem:string; impacto:ImpactoRegra; comportamento:string; validacao:"Provisória"|"Confirmada"; }
export type TipoQuadroLegal = "Efetivo" | "Comissionado";
export type SituacaoQuadro = "Vigente"|"Vigência futura"|"Encerrada";
export type FormaDestinacaoLegal = "DISTRIBUICAO_POSTERIOR" | "DEFINIDA_NA_LEI";
export interface QuantitativoLegalOrgao { readonly orgao:string; readonly quantidade:number; }
export interface QuadroAutorizadoRow { id:number; codigo:string; tipoQuadro:TipoQuadroLegal; vinculo:string; regime:string; carreira:string; cargo:string; especialidade:string; orgao:string; abrangencia:string; formaDestinacaoLegal?:FormaDestinacaoLegal; orgaosDefinidosLei?:readonly string[]; quantitativosLegaisPorOrgao?:readonly QuantitativoLegalOrgao[]; documentosLegaisIds?:readonly string[]; situacaoVigencia?: "ATIVO"|"ENCERRADO"|"EXTINTO"; dataAtivacao?:string; dataEncerramento?:string; motivoEncerramento?:string; dataExtincao?:string; motivoExtincao?:string; autorizadas:number; ocupadas:number; comprometidas:number; bloqueadas:number; inicioVigencia:string; fimVigencia:string; ato:string; processo:string; situacao:SituacaoQuadro; versao:number; atualizadoEm:string; }

export type TipoVagaLegal = "EFETIVO" | "COMISSIONADO";
export type EstadoVaga = "DISPONIVEL" | "OCUPADA";
export type SituacaoLegalVaga = "REGULAR" | "DECISAO_JUDICIAL" | "EM_EXTINCAO" | "EXTINTA" | "EM_TRANSFORMACAO";
export type TipoEventoHistoricoVaga = "CRIACAO" | "ALTERACAO_ESTADO" | "ALTERACAO_LEGAL" | "DISTRIBUICAO" | "CORRECAO";
export interface HistoricoVaga { readonly id:string; readonly vagaId:string; readonly ocorridoEm:string; readonly dataEfeito:string; readonly tipo:TipoEventoHistoricoVaga; readonly titulo:string; readonly descricao:string; readonly estadoAnterior?:EstadoVaga; readonly estadoPosterior?:EstadoVaga; readonly situacaoLegalAnterior?:SituacaoLegalVaga; readonly situacaoLegalPosterior?:SituacaoLegalVaga; readonly origem:string; readonly usuario:string; readonly processo?:string; }
export interface Vaga { readonly id:string; readonly sequencial:number; readonly quadroAutorizadoId:number; readonly quadroCodigo:string; readonly tipo:TipoVagaLegal; readonly lei:string; readonly carreira:string; readonly cargo:string; readonly orgaoTitular:string; readonly criadaEm:string; readonly inicioVigencia:string; estado:EstadoVaga; situacaoLegal:SituacaoLegalVaga; readonly historico:readonly HistoricoVaga[]; }
export type NaturezaComprometimento = "OCUPACAO" | "DISPONIBILIZACAO";
export type SituacaoComprometimento = "ATIVO" | "CONCLUIDO" | "CANCELADO";
export type SituacaoFaseComprometimento = "PENDENTE" | "EM_ANDAMENTO" | "CONCLUIDA" | "CANCELADA";
export interface FaseComprometimento { readonly id:string; readonly nome:string; readonly ordem:number; situacao:SituacaoFaseComprometimento; readonly origem:string; readonly processo:string; readonly iniciadaEm?:string; readonly concluidaEm?:string; readonly observacao?:string; }
export interface ComprometimentoVaga { readonly id:string; readonly vagaId:string; readonly natureza:NaturezaComprometimento; situacao:SituacaoComprometimento; readonly origem:string; readonly processo:string; readonly criadoEm:string; readonly dataEfeitoPrevista?:string; readonly motivo:string; readonly pessoaId?:string; readonly pessoaNome?:string; readonly cpf?:string; readonly vinculoId?:string; readonly matricula?:string; readonly fases:readonly FaseComprometimento[]; readonly eventoDefinitivo?:string; readonly concluidoEm?:string; }

export type SituacaoOcupacao = "ATIVA" | "ENCERRADA";
export interface EventoOcupacao { readonly id:string; readonly tipo:"REGISTRO"|"EFETIVO_EXERCICIO"|"ENCERRAMENTO"|"CORRECAO"; readonly data:string; readonly registradoEm:string; readonly descricao:string; readonly origem:string; readonly processo?:string; readonly usuario:string; }
export interface OcupacaoVaga { readonly id:string; readonly vagaId:string; readonly pessoaId:string; readonly pessoaNome:string; readonly cpf:string; readonly vinculoId:string; readonly matricula:string; readonly tipoVinculo:"EFETIVO"|"COMISSIONADO"; readonly orgaoVinculo:string; readonly orgaoLotacao:string; readonly orgaoExercicio:string; readonly cargo:string; readonly dataPosse?:string; readonly efetivoExercicioEm:string; situacao:SituacaoOcupacao; readonly encerradaEm?:string; readonly motivoEncerramento?:string; readonly eventos:readonly EventoOcupacao[]; }

export type SituacaoCessao = "ATIVA" | "ENCERRADA" | "AGENDADA";
export interface CessaoFuncional { readonly id:string; readonly ocupacaoId:string; readonly vinculoId:string; readonly vagaId:string; readonly orgaoCedente:string; readonly orgaoCessionario:string; readonly inicio:string; readonly fim?:string; readonly onus:"ORIGEM"|"DESTINO"|"RESSARCIMENTO"|"SEM_ONUS"; readonly processo:string; readonly ato:string; situacao:SituacaoCessao; readonly encerradaEm?:string; readonly motivoEncerramento?:string; }
export interface RegraOrgaosCarreira { readonly carreira:string; readonly orgaoTitularPadrao:string; readonly orgaosLotacaoPermitidos:readonly string[]; readonly orgaosExercicioPermitidos:readonly string[]; readonly permiteCessaoExterna:boolean; readonly exigeAutorizacaoEspecial:boolean; readonly fundamento:string; }

export type TipoMovimentoVagaIndividual = "DISTRIBUICAO"|"TRANSFERENCIA"|"RECOLHIMENTO"|"DECRETO"|"EXTINCAO"|"TRANSFORMACAO"|"DECISAO_JUDICIAL";
export interface MovimentoVagaIndividual { readonly id:string; readonly vagaId:string; readonly quadroAutorizadoId?:number; readonly quadroCodigo?:string; readonly quadroVersao?:number; readonly loteId?:string; readonly tipo:TipoMovimentoVagaIndividual; readonly dataEfeito:string; readonly registradoEm:string; readonly retroativo:boolean; readonly orgaoAnterior?:string; readonly unidadeAnterior?:string; readonly orgaoPosterior?:string; readonly unidadePosterior?:string; readonly situacaoLegalAnterior?:SituacaoLegalVaga; readonly situacaoLegalPosterior?:SituacaoLegalVaga; readonly ato:string; readonly processo:string; readonly justificativa:string; readonly cargoDestino?:string; readonly usuario:string; }
export interface PosicaoDistribuicaoVaga { readonly vagaId:string; readonly quadroAutorizadoId:number; readonly quadroCodigo:string; readonly dataReferencia:string; readonly orgaoTitular:string; readonly orgaoDistribuicao?:string; readonly unidadeDistribuicao?:string; readonly cargo:string; readonly situacaoLegal:SituacaoLegalVaga; readonly ultimoMovimento?:string; }

export interface SaldoControleVagas { vagasLegais:number; disponiveis:number; disponiveisLivres:number; disponiveisComprometidas:number; ocupadas:number; ocupadasEmDisponibilizacao:number; emExtincao:number; excedentesJudiciais:number; divergentes:number; }
export interface SaldoControleVagasGrupo extends SaldoControleVagas { readonly chave:string; readonly cargo:string; readonly orgaoTitular:string; readonly tipo:TipoVagaLegal; readonly totalFisico:number; }

export type CategoriaFatorProjecao = "COMPULSORIA"|"ELEGIBILIDADE_APOSENTADORIA"|"APOSENTADORIA_REQUERIDA"|"EXONERACAO_CONHECIDA";
export type CenarioProjecao = "CONSERVADOR"|"PROVAVEL"|"AMPLIADO";
export type HorizonteProjecao = 12|24|36|48;
export interface FatorProjecaoVagas { readonly id:string; readonly categoria:CategoriaFatorProjecao; readonly cargo:string; readonly orgao:string; readonly quantidade:number; readonly dataPrevista:string; readonly probabilidade:number; readonly vinculoIds?:readonly string[]; readonly origem:string; readonly referencia:string; readonly atualizadoEm:string; }
export interface TaxaEvasaoHistorica { readonly cargo:string; readonly orgao:string; readonly ano:number; readonly ocupadosMedios:number; readonly desligamentosVoluntarios:number; readonly taxa:number; }
export interface MetodologiaProjecao { readonly id:string; readonly versao:number; readonly nome:string; readonly vigenteDesde:string; readonly vigenteAte?:string; readonly criadaEm:string; readonly responsavel:string; readonly status:"VIGENTE"|"SUBSTITUIDA"; readonly pesosElegibilidade:Readonly<Record<CenarioProjecao,number>>; readonly multiplicadoresEvasao:Readonly<Record<CenarioProjecao,number>>; readonly regras:readonly string[]; }
export interface ResultadoProjecaoGrupo { readonly chave:string; readonly cargo:string; readonly orgao:string; readonly cenario:CenarioProjecao; readonly horizonte:HorizonteProjecao; readonly saldoDisponivelAtual:number; readonly compulsorias:number; readonly elegibilidade:number; readonly aposentadoriasRequeridas:number; readonly exoneracoesConhecidas:number; readonly evasaoEstimada:number; readonly novasDisponibilizacoes:number; readonly necessidadeProjetada:number; readonly metodologiaId:string; }

export interface ExcecaoJudicialVaga { readonly id:string; readonly pessoaNome:string; readonly vinculoId:string; readonly matricula:string; readonly cargo:string; readonly orgao:string; readonly decisao:string; readonly processo:string; readonly inicio:string; readonly situacao:"ATIVA"|"ENCERRADA"; readonly encerradaEm?:string; }
export type DominioEventoTemporal = "QUADRO_LEGAL"|"VAGA"|"COMPROMETIMENTO"|"OCUPACAO"|"CESSAO"|"DISTRIBUICAO"|"EXCECAO_JUDICIAL";
export interface EventoTemporalControleVagas { readonly id:string; readonly dominio:DominioEventoTemporal; readonly entidadeId:string; readonly vagaId?:string; readonly dataEfeito:string; readonly registradoEm:string; readonly tipo:string; readonly descricao:string; readonly origem:string; readonly processo?:string; }
