export type ImpactoRegra = "Autorização" | "Comprometimento" | "Ocupação" | "Liberação" | "Bloqueio" | "Exceção";
export interface RegraEvento { id:number; evento:string; origem:string; impacto:ImpactoRegra; comportamento:string; validacao:"Provisória"|"Confirmada"; }
export type TipoQuadroLegal = "Efetivo" | "Comissionado";
export type SituacaoQuadro = "Vigente"|"Vigência futura"|"Encerrada";
export type FormaDestinacaoLegal = "DISTRIBUICAO_POSTERIOR" | "DEFINIDA_NA_LEI";
export interface QuantitativoLegalOrgao { readonly orgao:string; readonly quantidade:number; }
export interface QuadroAutorizadoRow { id:number; codigo:string; tipoQuadro:TipoQuadroLegal; vinculo:string; regime:string; carreira:string; cargo:string; perfilProfissional:string; orgao:string; abrangencia:string; formaDestinacaoLegal?:FormaDestinacaoLegal; orgaosDefinidosLei?:readonly string[]; quantitativosLegaisPorOrgao?:readonly QuantitativoLegalOrgao[]; documentosLegaisIds?:readonly string[]; situacaoVigencia?: "ATIVO"|"ENCERRADO"|"EXTINTO"; dataAtivacao?:string; dataEncerramento?:string; motivoEncerramento?:string; dataExtincao?:string; motivoExtincao?:string; autorizadas:number; ocupadas:number; comprometidas:number; bloqueadas:number; inicioVigencia:string; fimVigencia:string; ato:string; processo:string; situacao:SituacaoQuadro; versao:number; atualizadoEm:string; }

export type TipoVagaLegal = "EFETIVO" | "COMISSIONADO";
export type EstadoVaga = "DISPONIVEL" | "OCUPADA";
export type SituacaoLegalVaga = "REGULAR" | "DECISAO_JUDICIAL" | "EM_EXTINCAO" | "EXTINTA" | "EM_TRANSFORMACAO";
export type TipoEventoHistoricoVaga = "CRIACAO" | "ALTERACAO_ESTADO" | "ALTERACAO_LEGAL" | "DISTRIBUICAO" | "CORRECAO";
export interface HistoricoVaga { readonly id:string; readonly vagaId:string; readonly ocorridoEm:string; readonly dataEfeito:string; readonly tipo:TipoEventoHistoricoVaga; readonly titulo:string; readonly descricao:string; readonly estadoAnterior?:EstadoVaga; readonly estadoPosterior?:EstadoVaga; readonly situacaoLegalAnterior?:SituacaoLegalVaga; readonly situacaoLegalPosterior?:SituacaoLegalVaga; readonly origem:string; readonly usuario:string; readonly processo?:string; }
export type SituacaoDistribuicaoVaga = "PENDENTE_ATO" | "DISTRIBUIDA";
export interface Vaga { readonly id:string; readonly sequencial:number; readonly quadroAutorizadoId:number; readonly quadroCodigo:string; readonly tipo:TipoVagaLegal; readonly lei:string; readonly carreira:string; readonly cargo:string; readonly perfilProfissional:string; readonly orgaoTitular:string; readonly destinacaoPrevistaLei:string; readonly orgaoDistribuicaoInicial?:string; readonly atoDistribuicaoInicial?:string; readonly inicioVigenciaDistribuicao?:string; readonly criadaEm:string; readonly inicioVigencia:string; estado:EstadoVaga; situacaoLegal:SituacaoLegalVaga; readonly historico:readonly HistoricoVaga[]; }
export type NaturezaComprometimento = "OCUPACAO" | "DISPONIBILIZACAO";
export type SituacaoComprometimento = "ATIVO" | "CONCLUIDO" | "CANCELADO";
export type SituacaoFaseComprometimento = "PENDENTE" | "EM_ANDAMENTO" | "CONCLUIDA" | "CANCELADA";
export interface FaseComprometimento { readonly id:string; readonly nome:string; readonly ordem:number; situacao:SituacaoFaseComprometimento; readonly origem:string; readonly processo:string; readonly iniciadaEm?:string; readonly concluidaEm?:string; readonly observacao?:string; }
export interface ComprometimentoVaga { readonly id:string; readonly vagaId:string; readonly natureza:NaturezaComprometimento; situacao:SituacaoComprometimento; readonly origem:string; readonly processo:string; readonly criadoEm:string; readonly dataEfeitoPrevista?:string; readonly motivo:string; readonly pessoaId?:string; readonly pessoaNome?:string; readonly cpf?:string; readonly vinculoId?:string; readonly matricula?:string; readonly fases:readonly FaseComprometimento[]; readonly eventoDefinitivo?:string; readonly concluidoEm?:string; }

export type SituacaoOcupacao = "ATIVA" | "ENCERRADA";
export interface EventoOcupacao { readonly id:string; readonly tipo:"REGISTRO"|"EFETIVO_EXERCICIO"|"ENCERRAMENTO"|"CORRECAO"; readonly data:string; readonly registradoEm:string; readonly descricao:string; readonly origem:string; readonly processo?:string; readonly usuario:string; }
export interface OcupacaoVaga { readonly id:string; readonly vagaId:string; readonly pessoaId:string; readonly pessoaNome:string; readonly cpf:string; readonly vinculoId:string; readonly matricula:string; readonly tipoVinculo:"EFETIVO"|"COMISSIONADO"; readonly orgaoVinculo:string; readonly orgaoLotacao:string; readonly orgaoExercicio:string; readonly cargo:string; readonly dataPosse?:string; readonly efetivoExercicioEm:string; situacao:SituacaoOcupacao; readonly encerradaEm?:string; readonly motivoEncerramento?:string; readonly eventos:readonly EventoOcupacao[]; }

export type TipoMovimentacaoFuncional = "CESSAO" | "REMOCAO" | "TRANSFERENCIA";
export type SubtipoCessao = "CESSAO_INTERNA" | "CESSAO_EXTERNA_ORGAO_ESTADUAL" | "CESSAO_EXTERNA_OUTRO_PODER" | "CESSAO_EXTERNA_OUTRO_ENTE";
export type SubtipoRemocao = "REMOCAO_INTERNA" | "REMOCAO_ENTRE_UNIDADES" | "REMOCAO_ENTRE_ORGAOS" | "REMOCAO_A_PEDIDO" | "REMOCAO_DE_OFICIO" | "REMOCAO_SAUDE" | "REMOCAO_ACOMPANHAMENTO_CONJUGE" | "REMOCAO_PROCESSO_SELETIVO" | "REMOCAO_PERMUTA";
export type SubtipoTransferencia = "TRANSFERENCIA_ENTRE_VAGAS" | "TRANSFERENCIA_POR_DECISAO_JUDICIAL";
export type SubtipoMovimentacaoFuncional = SubtipoCessao | SubtipoRemocao | SubtipoTransferencia;
export type SituacaoMovimentacaoFuncional = "EM_PREENCHIMENTO" | "EM_ANALISE" | "AGUARDANDO_VALIDACAO" | "AUTORIZADA" | "PUBLICADA" | "AGENDADA_EFETIVACAO" | "EFETIVADA" | "DEVOLVIDA" | "REJEITADA" | "CANCELADA" | "ENCERRADA";
export type DecisaoValidacaoMovimentacao = "APROVADA" | "DEVOLVIDA" | "REJEITADA";
export interface ResponsavelMovimentacao { readonly usuarioId:string; readonly nome:string; readonly unidade:string; readonly perfil:string; readonly data:string; }
export interface PublicacaoMovimentacao { readonly ato:string; readonly numero?:string; readonly veiculo:string; readonly dataPublicacao:string; readonly pagina?:string; readonly urlDocumento?:string; }
export interface ValidacaoMovimentacao { readonly id:string; readonly etapa:string; readonly decisao:DecisaoValidacaoMovimentacao; readonly responsavel:ResponsavelMovimentacao; readonly observacao?:string; }
export interface VinculosComprometimentoMovimentacao { readonly origem?:string; readonly destino?:string; }
export interface EfeitoAtomicoVaga { readonly vagaId:string; readonly papel:"ORIGEM"|"DESTINO"; readonly estadoAnterior:EstadoVaga; readonly estadoPosterior:EstadoVaga; readonly ocupacaoAnteriorId?:string; readonly ocupacaoPosteriorId?:string; }
export interface TransacaoAtomicaMovimentacao { readonly id:string; readonly situacao:"PENDENTE"|"PREPARADA"|"EFETIVADA"|"REVERTIDA"|"FALHOU"; readonly efetivadaEm?:string; readonly efeitos:readonly EfeitoAtomicoVaga[]; readonly erro?:string; }
export interface FaseMovimentacaoFuncional { readonly id:string; readonly nome:string; readonly ordem:number; readonly situacao:"PENDENTE"|"EM_ANDAMENTO"|"CONCLUIDA"|"CANCELADA"; readonly iniciadaEm?:string; readonly concluidaEm?:string; readonly responsavel?:ResponsavelMovimentacao; readonly observacao?:string; }
export interface EventoMovimentacaoFuncional { readonly id:string; readonly data:string; readonly registradoEm:string; readonly tipo:string; readonly descricao:string; readonly origem:string; readonly usuario:string; readonly responsavel?:ResponsavelMovimentacao; readonly situacaoAnterior?:SituacaoMovimentacaoFuncional; readonly situacaoPosterior?:SituacaoMovimentacaoFuncional; }
export type SituacaoOperacionalCessao = "AGENDADA" | "ATIVA" | "DEVOLVIDA" | "ENCERRADA";
export type TipoEncerramentoCessao = "TERMINO_PRAZO" | "DEVOLUCAO_ANTECIPADA" | "CANCELAMENTO";
export interface ProrrogacaoCessao { readonly id:string; readonly fimAnterior?:string; readonly novoFim:string; readonly ato:string; readonly processo:string; readonly registradoEm:string; readonly responsavel:ResponsavelMovimentacao; }
export interface RetificacaoCessao { readonly id:string; readonly campo:string; readonly valorAnterior:string; readonly valorPosterior:string; readonly ato:string; readonly registradoEm:string; readonly responsavel:ResponsavelMovimentacao; }
export interface DetalhesCessaoMovimentacao { readonly esferaDestino:"EXECUTIVO_ESTADUAL"|"OUTRO_PODER"|"UNIAO"|"MUNICIPIO"|"OUTRO_ESTADO"; readonly unidadeDestino:string; readonly motivo:string; readonly cargoOuFuncao?:string; readonly inicio:string; readonly fim?:string; readonly orgaoResponsavelFolha:string; readonly orgaoResponsavelCusto:string; readonly semOnus:boolean; readonly exigeRessarcimento:boolean; readonly periodicidadeRessarcimento?:"MENSAL"|"TRIMESTRAL"|"ANUAL"; readonly fonteRecursos?:string; readonly situacaoRessarcimento?:"NAO_APLICAVEL"|"REGULAR"|"PENDENTE"|"INADIMPLENTE"; readonly mesesInadimplencia?:number; readonly observacoes?:string; readonly situacaoOperacional:SituacaoOperacionalCessao; readonly prorrogacoes:readonly ProrrogacaoCessao[]; readonly retificacoes:readonly RetificacaoCessao[]; readonly encerradaEm?:string; readonly tipoEncerramento?:TipoEncerramentoCessao; readonly motivoEncerramento?:string; }
export interface MovimentacaoFuncional { readonly id:string; readonly tipo:TipoMovimentacaoFuncional; readonly subtipo:SubtipoMovimentacaoFuncional; situacao:SituacaoMovimentacaoFuncional; readonly pessoaId:string; readonly vinculoId:string; readonly ocupacaoOrigemId:string; readonly vagaOrigemId:string; readonly vagaDestinoId?:string; readonly orgaoOrigem:string; readonly unidadeOrigem:string; readonly orgaoDestino:string; readonly unidadeDestino?:string; readonly processo:string; readonly fundamentoLegal?:string; readonly motivo?:string; readonly ato?:string; readonly publicacao?:PublicacaoMovimentacao; readonly detalhesCessao?:DetalhesCessaoMovimentacao; readonly dataSolicitacao:string; readonly dataEfeito?:string; readonly criadoEm:string; readonly atualizadoEm:string; readonly registradoPor:ResponsavelMovimentacao; readonly analisadoPor?:ResponsavelMovimentacao; readonly validadoPor?:ResponsavelMovimentacao; readonly comprometimentos:VinculosComprometimentoMovimentacao; readonly transacaoAtomica?:TransacaoAtomicaMovimentacao; readonly validacoes:readonly ValidacaoMovimentacao[]; readonly fases:readonly FaseMovimentacaoFuncional[]; readonly historico:readonly EventoMovimentacaoFuncional[]; }
export type SituacaoCessao = "ATIVA" | "ENCERRADA" | "AGENDADA";
export interface CessaoFuncional { readonly id:string; readonly ocupacaoId:string; readonly vinculoId:string; readonly vagaId:string; readonly orgaoCedente:string; readonly orgaoCessionario:string; readonly inicio:string; readonly fim?:string; readonly onus:"ORIGEM"|"DESTINO"|"RESSARCIMENTO"|"SEM_ONUS"; readonly processo:string; readonly ato:string; situacao:SituacaoCessao; readonly encerradaEm?:string; readonly motivoEncerramento?:string; }
export interface RegraOrgaosCarreira { readonly carreira:string; readonly orgaoTitularPadrao:string; readonly orgaosLotacaoPermitidos:readonly string[]; readonly orgaosExercicioPermitidos:readonly string[]; readonly permiteCessaoExterna:boolean; readonly exigeAutorizacaoEspecial:boolean; readonly fundamento:string; }

export type TipoMovimentoVagaIndividual = "DISTRIBUICAO"|"REDISTRIBUICAO"|"DECRETO"|"EXTINCAO"|"TRANSFORMACAO"|"DECISAO_JUDICIAL";
export interface MovimentoVagaIndividual { readonly id:string; readonly vagaId:string; readonly quadroAutorizadoId?:number; readonly quadroCodigo?:string; readonly quadroVersao?:number; readonly loteId?:string; readonly tipo:TipoMovimentoVagaIndividual; readonly dataEfeito:string; readonly registradoEm:string; readonly retroativo:boolean; readonly orgaoAnterior?:string; readonly unidadeAnterior?:string; readonly orgaoPosterior?:string; readonly unidadePosterior?:string; readonly situacaoLegalAnterior?:SituacaoLegalVaga; readonly situacaoLegalPosterior?:SituacaoLegalVaga; readonly ato:string; readonly processo:string; readonly justificativa:string; readonly cargoDestino?:string; readonly usuario:string; }
export interface PosicaoDistribuicaoVaga { readonly vagaId:string; readonly quadroAutorizadoId:number; readonly quadroCodigo:string; readonly dataReferencia:string; readonly orgaoTitular:string; readonly destinacaoPrevistaLei:string; readonly situacaoDistribuicao:SituacaoDistribuicaoVaga; readonly orgaoDistribuicao?:string; readonly unidadeDistribuicao?:string; readonly atoDistribuicao?:string; readonly inicioVigenciaDistribuicao?:string; readonly cargo:string; readonly situacaoLegal:SituacaoLegalVaga; readonly ultimoMovimento?:string; }

export interface SaldoControleVagas { vagasLegais:number; disponiveis:number; disponiveisLivres:number; disponiveisComprometidas:number; ocupadas:number; ocupadasEmDisponibilizacao:number; emExtincao:number; excedentesJudiciais:number; divergentes:number; }
export interface SaldoControleVagasGrupo extends SaldoControleVagas { readonly chave:string; readonly cargo:string; readonly perfilProfissional:string; readonly orgaoTitular:string; readonly tipo:TipoVagaLegal; readonly totalFisico:number; }

export type CategoriaFatorProjecao = "COMPULSORIA"|"ELEGIBILIDADE_APOSENTADORIA"|"APOSENTADORIA_REQUERIDA"|"EXONERACAO_CONHECIDA";
export type CenarioProjecao = "CONSERVADOR"|"PROVAVEL"|"AMPLIADO";
export type HorizonteProjecao = 12|24|36|48;
export interface FatorProjecaoVagas { readonly id:string; readonly categoria:CategoriaFatorProjecao; readonly cargo:string; readonly orgao:string; readonly quantidade:number; readonly dataPrevista:string; readonly probabilidade:number; readonly vinculoIds?:readonly string[]; readonly origem:string; readonly referencia:string; readonly atualizadoEm:string; }
export interface TaxaEvasaoHistorica { readonly cargo:string; readonly orgao:string; readonly ano:number; readonly ocupadosMedios:number; readonly desligamentosVoluntarios:number; readonly taxa:number; }
export interface MetodologiaProjecao { readonly id:string; readonly versao:number; readonly nome:string; readonly vigenteDesde:string; readonly vigenteAte?:string; readonly criadaEm:string; readonly responsavel:string; readonly status:"VIGENTE"|"SUBSTITUIDA"; readonly pesosElegibilidade:Readonly<Record<CenarioProjecao,number>>; readonly multiplicadoresEvasao:Readonly<Record<CenarioProjecao,number>>; readonly regras:readonly string[]; }
export interface ResultadoProjecaoGrupo { readonly chave:string; readonly cargo:string; readonly orgao:string; readonly cenario:CenarioProjecao; readonly horizonte:HorizonteProjecao; readonly saldoDisponivelAtual:number; readonly compulsorias:number; readonly elegibilidade:number; readonly aposentadoriasRequeridas:number; readonly exoneracoesConhecidas:number; readonly evasaoEstimada:number; readonly novasDisponibilizacoes:number; readonly necessidadeProjetada:number; readonly metodologiaId:string; }

export interface ExcecaoJudicialVaga { readonly id:string; readonly pessoaNome:string; readonly vinculoId:string; readonly matricula:string; readonly cargo:string; readonly orgao:string; readonly decisao:string; readonly processo:string; readonly inicio:string; readonly situacao:"ATIVA"|"ENCERRADA"; readonly encerradaEm?:string; }
export type DominioEventoTemporal = "QUADRO_LEGAL"|"VAGA"|"COMPROMETIMENTO"|"OCUPACAO"|"CESSAO"|"MOVIMENTACAO_FUNCIONAL"|"DISTRIBUICAO"|"EXCECAO_JUDICIAL";
export interface EventoTemporalControleVagas { readonly id:string; readonly dominio:DominioEventoTemporal; readonly entidadeId:string; readonly vagaId?:string; readonly dataEfeito:string; readonly registradoEm:string; readonly tipo:string; readonly descricao:string; readonly origem:string; readonly processo?:string; }
