import type { QuadroAutorizadoRow, RegraEvento, Vaga } from "./types";

export const regrasControleVagasMock: RegraEvento[] = [
  {
    id: 1,
    evento: "Ampliação legal do quadro",
    origem: "Lei ou ato autorizativo",
    impacto: "Autorização",
    comportamento:
      "Cria novas vagas individualizadas e numeradas após a vigência",
    validacao: "Provisória",
  },
  {
    id: 2,
    evento: "Redução legal do quadro",
    origem: "Lei ou ato autorizativo",
    impacto: "Autorização",
    comportamento:
      "Extingue vagas disponíveis e marca ocupadas para extinção progressiva",
    validacao: "Provisória",
  },
  {
    id: 3,
    evento: "Transformação de cargo",
    origem: "Lei ou ato autorizativo",
    impacto: "Autorização",
    comportamento:
      "Preserva a identidade e o histórico da vaga, registrando cargo de origem e destino",
    validacao: "Provisória",
  },
  {
    id: 4,
    evento: "Início de processo de ocupação",
    origem: "Ingresso do Servidor",
    impacto: "Comprometimento",
    comportamento: "Adiciona fases à vaga disponível sem alterar seu estado",
    validacao: "Provisória",
  },
  {
    id: 5,
    evento: "Efetivo exercício",
    origem: "Vida funcional",
    impacto: "Ocupação",
    comportamento: "Relaciona um vínculo à vaga e altera o estado para ocupada",
    validacao: "Provisória",
  },
  {
    id: 6,
    evento: "Início de processo de disponibilização",
    origem: "Vida funcional",
    impacto: "Comprometimento",
    comportamento: "Adiciona fases à vaga ocupada sem antecipar sua liberação",
    validacao: "Provisória",
  },
  {
    id: 7,
    evento: "Encerramento definitivo do vínculo",
    origem: "Vida funcional",
    impacto: "Liberação",
    comportamento: "Encerra a ocupação nominal e torna a vaga disponível",
    validacao: "Provisória",
  },
  {
    id: 8,
    evento: "Cancelamento de processo",
    origem: "Sistema de origem",
    impacto: "Liberação",
    comportamento: "Cancela as fases ativas sem alterar o estado da vaga",
    validacao: "Provisória",
  },
  {
    id: 9,
    evento: "Cessão funcional",
    origem: "Vida funcional",
    impacto: "Ocupação",
    comportamento:
      "Altera apenas o órgão de exercício; a titularidade da vaga é preservada",
    validacao: "Provisória",
  },
  {
    id: 10,
    evento: "Movimento de distribuição",
    origem: "Controle de Vagas",
    impacto: "Autorização",
    comportamento:
      "Distribui ou redistribui a vaga numerada por ato formal sem apagar movimentos anteriores",
    validacao: "Provisória",
  },
  {
    id: 11,
    evento: "Decisão judicial extraquadro",
    origem: "Decisão judicial",
    impacto: "Exceção",
    comportamento:
      "Registra vínculo excepcional separado das vagas legais e não amplia o quadro",
    validacao: "Provisória",
  },
  {
    id: 12,
    evento: "Movimento retroativo",
    origem: "Sistema de origem",
    impacto: "Exceção",
    comportamento:
      "Recalcula a posição temporal desde a data de efeito, preservando a data de registro",
    validacao: "Provisória",
  },
];
export const pendenciasRegrasMock = [
  "Marco definitivo e documento que comprovam o efetivo exercício",
  "Eventos definitivos de disponibilização por tipo de vínculo",
  "Órgãos de exercício permitidos por carreira e hipóteses de autorização especial",
  "Critério de encerramento de ocupação judicial extraquadro",
  "Periodicidade de homologação da metodologia e das taxas de projeção",
];

const estadoDeMatoGrosso = "ESTADO DE MATO GROSSO";

export const quadrosAutorizadosMock: QuadroAutorizadoRow[] = [
  {
    id: 101,
    codigo: "QAB-0001",
    tipoQuadro: "Efetivo",
    vinculo: "Bolsista",
    regime: "Sem Vínculo Empregatício",
    carreira: "Bolsistas",
    cargo: "Bolsista de Nível Médio",
    perfilProfissional: "Bolsista de Nível Médio",
    orgao: estadoDeMatoGrosso,
    abrangencia: "Estadual",
    formaDestinacaoLegal: "DISTRIBUICAO_POSTERIOR",
    autorizadas: 12,
    ocupadas: 0,
    comprometidas: 0,
    bloqueadas: 0,
    inicioVigencia: "2026-01-01",
    fimVigencia: "",
    ato: "Lei nº 12.001/2025",
    processo: "SEPLAG-PRO-2026/01001",
    situacao: "Vigente",
    situacaoVigencia: "ATIVO",
    dataAtivacao: "2026-01-01",
    versao: 1,
    atualizadoEm: "2026-01-02 09:00",
  },
  {
    id: 102,
    codigo: "QAB-0002",
    tipoQuadro: "Efetivo",
    vinculo: "Bolsista",
    regime: "Sem Vínculo Empregatício",
    carreira: "Bolsistas",
    cargo: "Bolsista de Pós-Graduação",
    perfilProfissional: "Bolsista de Pós-Graduação",
    orgao: estadoDeMatoGrosso,
    abrangencia: "Estadual",
    formaDestinacaoLegal: "DISTRIBUICAO_POSTERIOR",
    autorizadas: 8,
    ocupadas: 0,
    comprometidas: 0,
    bloqueadas: 0,
    inicioVigencia: "2026-02-01",
    fimVigencia: "",
    ato: "Lei nº 12.002/2025",
    processo: "SEPLAG-PRO-2026/01002",
    situacao: "Vigente",
    situacaoVigencia: "ATIVO",
    dataAtivacao: "2026-02-01",
    versao: 1,
    atualizadoEm: "2026-02-02 09:00",
  },
  {
    id: 103,
    codigo: "QAB-0003",
    tipoQuadro: "Efetivo",
    vinculo: "Bolsista",
    regime: "Sem Vínculo Empregatício",
    carreira: "Bolsistas",
    cargo: "Residente Técnico",
    perfilProfissional: "Residente Técnico",
    orgao: estadoDeMatoGrosso,
    abrangencia: "Estadual",
    formaDestinacaoLegal: "DISTRIBUICAO_POSTERIOR",
    autorizadas: 6,
    ocupadas: 0,
    comprometidas: 0,
    bloqueadas: 0,
    inicioVigencia: "2025-01-01",
    fimVigencia: "2026-04-30",
    ato: "Lei nº 11.900/2024",
    processo: "SEPLAG-PRO-2025/00811",
    situacao: "Encerrada",
    situacaoVigencia: "EXTINTO",
    dataAtivacao: "2025-01-01",
    dataExtincao: "2026-04-30",
    motivoExtincao: "Encerramento do programa de residência técnica.",
    versao: 1,
    atualizadoEm: "2026-04-30 18:00",
  },
  {
    id: 104,
    codigo: "QAB-0004",
    tipoQuadro: "Efetivo",
    vinculo: "Bolsista",
    regime: "Sem Vínculo Empregatício",
    carreira: "Bolsistas",
    cargo: "Bolsista de Apoio Técnico",
    perfilProfissional: "Bolsista de Apoio Técnico",
    orgao: estadoDeMatoGrosso,
    abrangencia: "Estadual",
    formaDestinacaoLegal: "DISTRIBUICAO_POSTERIOR",
    autorizadas: 5,
    ocupadas: 0,
    comprometidas: 0,
    bloqueadas: 0,
    inicioVigencia: "2025-06-01",
    fimVigencia: "2026-06-30",
    ato: "Lei nº 11.901/2024",
    processo: "SEPLAG-PRO-2025/00812",
    situacao: "Encerrada",
    situacaoVigencia: "ENCERRADO",
    dataAtivacao: "2025-06-01",
    dataEncerramento: "2026-06-30",
    motivoEncerramento: "Término da vigência do programa de bolsas.",
    versao: 1,
    atualizadoEm: "2026-06-30 18:00",
  },
];

const criarVagasBolsistas = (
  quadroAutorizadoId: number,
  quadroCodigo: string,
  cargo: string,
  quantidade: number,
  orgaosDistribuidos: readonly string[],
): Vaga[] =>
  Array.from({ length: quantidade }, (_, indice): Vaga => {
    const orgao = orgaosDistribuidos[indice] ?? estadoDeMatoGrosso;
    const distribuida = orgao !== estadoDeMatoGrosso;
    const sequencial = indice + 1;
    return {
      id: "VB-" + quadroCodigo + "-" + String(sequencial).padStart(3, "0"),
      sequencial,
      quadroAutorizadoId,
      quadroCodigo,
      tipo: "EFETIVO",
      lei: "Lei autorizativa do quadro " + quadroCodigo,
      carreira: "Bolsistas",
      cargo,
      perfilProfissional: cargo,
      orgaoTitular: orgao,
      destinacaoPrevistaLei: "Distribuição posterior por ato administrativo",
      ...(distribuida
        ? {
            orgaoDistribuicaoInicial: orgao,
            atoDistribuicaoInicial: "Portaria nº " + String(300 + sequencial) + "/2026",
            inicioVigenciaDistribuicao: "2026-03-01",
          }
        : {}),
      criadaEm: "2026-01-02 09:00",
      inicioVigencia: "2026-01-01",
      estado: "DISPONIVEL",
      situacaoLegal: "REGULAR",
      historico: [
        {
          id: "H-" + quadroCodigo + "-" + String(sequencial),
          vagaId: "VB-" + quadroCodigo + "-" + String(sequencial).padStart(3, "0"),
          ocorridoEm: "2026-01-02 09:00",
          dataEfeito: "2026-01-01",
          tipo: "CRIACAO",
          titulo: "Vaga de bolsa autorizada",
          descricao: "Vaga criada a partir do quadro autorizado " + quadroCodigo + ".",
          origem: "Controle de Vagas",
          usuario: "Usuário do protótipo",
        },
      ],
    };
  });

export const vagasIndividualizadasMock: Vaga[] = [
  ...criarVagasBolsistas(101, "QAB-0001", "Bolsista de Nível Médio", 12, [
    "SEDUC",
    "SEDUC",
    "SEDUC",
    "SEDUC",
    "SEDUC",
    "SES",
    "SES",
    "SES",
  ]),
  ...criarVagasBolsistas(102, "QAB-0002", "Bolsista de Pós-Graduação", 8, [
    "SEPLAG",
    "SEPLAG",
    "SES",
  ]),
  ...criarVagasBolsistas(103, "QAB-0003", "Residente Técnico", 6, []),
  ...criarVagasBolsistas(104, "QAB-0004", "Bolsista de Apoio Técnico", 5, []),
];
