import type { MovimentacaoFuncional, SituacaoMovimentacaoFuncional, SubtipoMovimentacaoFuncional, TipoMovimentacaoFuncional } from "./types";

const responsavel={usuarioId:"USR-001",nome:"Débora Almeida",unidade:"SEPLAG — Gestão de Pessoas",perfil:"Analista",data:"2026-07-23 09:00"};
const criar=(id:string,tipo:TipoMovimentacaoFuncional,subtipo:SubtipoMovimentacaoFuncional,situacao:SituacaoMovimentacaoFuncional,pessoaId:string,vinculoId:string,vagaOrigemId:string,orgaoOrigem:string,orgaoDestino:string,data:string):MovimentacaoFuncional=>({id,tipo,subtipo,situacao,pessoaId,vinculoId,ocupacaoOrigemId:`OCU-${vinculoId}`,vagaOrigemId,orgaoOrigem,unidadeOrigem:`${orgaoOrigem} — Unidade de origem`,orgaoDestino,unidadeDestino:`${orgaoDestino} — Unidade de destino`,processo:`SEPLAG-PRO-2026/${id.slice(-5)}`,fundamentoLegal:"Fundamentação em análise",motivo:"Movimentação funcional simulada",detalhesCessao:tipo==="CESSAO"?{esferaDestino:subtipo==="CESSAO_EXTERNA_OUTRO_PODER"?"OUTRO_PODER":"EXECUTIVO_ESTADUAL",unidadeDestino:`${orgaoDestino} — Unidade de destino`,motivo:"Colaboração institucional",cargoOuFuncao:"Função de assessoramento",inicio:data,fim:"2027-07-22",orgaoResponsavelFolha:orgaoOrigem,orgaoResponsavelCusto:orgaoDestino,semOnus:false,exigeRessarcimento:true,periodicidadeRessarcimento:"MENSAL",fonteRecursos:"Recursos próprios do cessionário",situacaoRessarcimento:"REGULAR",mesesInadimplencia:0,situacaoOperacional:situacao==="EFETIVADA"?"ATIVA":"AGENDADA",prorrogacoes:[],retificacoes:[]}:undefined,detalhesRemocao:tipo==="REMOCAO"?{abrangencia:"ENTRE_UNIDADES",fundamento:subtipo==="REMOCAO_DE_OFICIO"?"DE_OFICIO":"A_PEDIDO",orgaoDestino,unidadeOrigem:`${orgaoOrigem} — Unidade de origem`,unidadeDestino:`${orgaoDestino} — Nova unidade`,alteraLotacao:true,alteraExercicio:true,pedidoOuOficio:"Ofício nº 145/2026",situacaoOperacional:situacao==="EFETIVADA"?"EFETIVADA":"AGENDADA",efetivadaEm:situacao==="EFETIVADA"?data:undefined}:undefined,dataSolicitacao:data,dataEfeito:situacao==="EFETIVADA"?data:undefined,criadoEm:`${data} 09:00`,atualizadoEm:`${data} 10:30`,registradoPor:responsavel,comprometimentos:{},validacoes:[],fases:[{id:`${id}-F1`,nome:"Registro pela origem",ordem:1,situacao:"CONCLUIDA",iniciadaEm:data,concluidaEm:data,responsavel},{id:`${id}-F2`,nome:"Conferência documental",ordem:2,situacao:situacao==="EM_PREENCHIMENTO"?"PENDENTE":"CONCLUIDA"},{id:`${id}-F3`,nome:"Análise da SEPLAG",ordem:3,situacao:situacao==="EM_ANALISE"?"EM_ANDAMENTO":"PENDENTE"},{id:`${id}-F4`,nome:"Autorização e validação",ordem:4,situacao:situacao==="AGUARDANDO_VALIDACAO"?"EM_ANDAMENTO":"PENDENTE"},{id:`${id}-F5`,nome:"Publicação",ordem:5,situacao:situacao==="PUBLICADA"||situacao==="EFETIVADA"?"CONCLUIDA":"PENDENTE"},{id:`${id}-F6`,nome:"Efetivação",ordem:6,situacao:situacao==="EFETIVADA"?"CONCLUIDA":"PENDENTE"}],historico:[{id:`${id}-H1`,data,registradoEm:`${data} 09:00`,tipo:"REGISTRO",descricao:"Movimentação registrada pela unidade de origem.",origem:"Movimentações Funcionais",usuario:responsavel.nome,responsavel,situacaoPosterior:"EM_PREENCHIMENTO"}]});

const comCessao=(base:MovimentacaoFuncional,detalhes:Partial<NonNullable<MovimentacaoFuncional["detalhesCessao"]>>={}):MovimentacaoFuncional=>({...base,ato:`Ato nº ${base.id.slice(-5)}/2026`,detalhesCessao:{...base.detalhesCessao!,...detalhes}});
const comRemocao=(base:MovimentacaoFuncional,detalhes:Partial<NonNullable<MovimentacaoFuncional["detalhesRemocao"]>>={}):MovimentacaoFuncional=>({...base,ato:`Portaria nº ${base.id.slice(-5)}/2026`,detalhesRemocao:{...base.detalhesRemocao!,...detalhes}});
const comEspecial=(base:MovimentacaoFuncional,modalidade:NonNullable<MovimentacaoFuncional["detalhesEspeciais"]>["modalidade"],extras:Partial<NonNullable<MovimentacaoFuncional["detalhesEspeciais"]>>={}):MovimentacaoFuncional=>({...base,ato:`Ato especial nº ${base.id.slice(-5)}/2026`,detalhesEspeciais:{modalidade,retroativa:false,orgaoAnterior:base.orgaoOrigem,unidadeAnterior:base.unidadeOrigem,vagaAnteriorId:base.vagaOrigemId,retificacoes:[],...extras}});

export const movimentacoesFuncionaisMock:MovimentacaoFuncional[]=[
 // Cessões: modalidades, fases, ônus, ressarcimento e encerramento.
 comCessao(criar("MOV-00001","CESSAO","CESSAO_INTERNA","EM_ANALISE","PES-001","VIN-1045892","VAG-SEPLAG-ANALISTAAD-00001","SEPLAG","SEFAZ","2026-07-18")),
 comCessao(criar("MOV-00002","CESSAO","CESSAO_EXTERNA_OUTRO_PODER","AGUARDANDO_VALIDACAO","PES-002","VIN-1046017","VAG-SEPLAG-ANALISTAAD-00002","SEPLAG","TJMT","2026-07-19"),{esferaDestino:"OUTRO_PODER"}),
 comCessao(criar("MOV-00007","CESSAO","CESSAO_INTERNA","EFETIVADA","PES-007","VIN-0005004","VAG-SEPLAG-ANALISTAAD-00007","SEPLAG","SEPLAG","2026-06-01"),{semOnus:true,exigeRessarcimento:false,situacaoRessarcimento:"NAO_APLICAVEL",orgaoResponsavelCusto:"SEPLAG",unidadeDestino:"SEPLAG — Coordenadoria de Sistemas",situacaoOperacional:"ATIVA"}),
 comCessao(criar("MOV-00008","CESSAO","CESSAO_EXTERNA_OUTRO_ENTE","AUTORIZADA","PES-008","VIN-0005005","VAG-SEPLAG-ANALISTAAD-00008","SEPLAG","PREFEITURA DE CUIABÁ","2026-07-10"),{esferaDestino:"MUNICIPIO",situacaoOperacional:"AGENDADA"}),
 comCessao(criar("MOV-00009","CESSAO","CESSAO_EXTERNA_ORGAO_ESTADUAL","EFETIVADA","PES-009","VIN-0005006","VAG-SEPLAG-ANALISTAAD-00009","SEPLAG","SES","2026-04-15"),{exigeRessarcimento:true,situacaoRessarcimento:"PENDENTE",mesesInadimplencia:2,situacaoOperacional:"ATIVA"}),
 comCessao(criar("MOV-00010","CESSAO","CESSAO_EXTERNA_ORGAO_ESTADUAL","EFETIVADA","PES-010","VIN-0005007","VAG-SEPLAG-ANALISTAAD-00010","SEPLAG","SINFRA","2025-08-01"),{fim:"2028-07-31",situacaoOperacional:"ATIVA",prorrogacoes:[{id:"MOV-00010-PRO-1",fimAnterior:"2026-07-31",novoFim:"2028-07-31",ato:"Ato nº 411/2026",processo:"SIGADOC 2026/00411",registradoEm:"2026-06-20 10:00",responsavel}],retificacoes:[{id:"MOV-00010-RET-1",campo:"unidadeDestino",valorAnterior:"SINFRA — Gabinete",valorPosterior:"SINFRA — Superintendência de Obras",ato:"Retificação nº 52/2026",registradoEm:"2026-06-25 11:00",responsavel}]}),
 comCessao(criar("MOV-00011","CESSAO","CESSAO_EXTERNA_OUTRO_PODER","ENCERRADA","PES-011","VIN-0005008","VAG-SEPLAG-ANALISTAAD-00011","SEPLAG","ALMT","2025-01-10"),{esferaDestino:"OUTRO_PODER",situacaoOperacional:"DEVOLVIDA",encerradaEm:"2026-05-30",tipoEncerramento:"DEVOLUCAO_ANTECIPADA",motivoEncerramento:"Retorno solicitado pelo órgão de origem"}),
 // Remoções: internas, externas, a pedido, de ofício, processo seletivo e permuta.
 comRemocao(criar("MOV-00003","REMOCAO","REMOCAO_INTERNA","PUBLICADA","PES-003","VIN-0005000","VAG-SEPLAG-ANALISTAAD-00003","SEPLAG","SEPLAG","2026-07-20")),
 comRemocao(criar("MOV-00006","REMOCAO","REMOCAO_A_PEDIDO","DEVOLVIDA","PES-006","VIN-0005003","VAG-SEPLAG-ANALISTAAD-00006","SEPLAG","SEPLAG","2026-07-22")),
 comRemocao(criar("MOV-00012","REMOCAO","REMOCAO_DE_OFICIO","EFETIVADA","PES-012","VIN-0005009","VAG-SEPLAG-ANALISTAAD-00012","SEPLAG","SEPLAG","2026-06-15"),{fundamento:"DE_OFICIO",situacaoOperacional:"EFETIVADA",efetivadaEm:"2026-06-15"}),
 comRemocao({...criar("MOV-00013","REMOCAO","REMOCAO_EXTERNA","EM_ANALISE","PES-013","VIN-0005010","VAG-SEPLAG-ANALISTAAD-00013","SEPLAG","SEFAZ","2026-07-11"),vagaDestinoId:"VAG-SEFAZ-ANALISTAAD-00001"},{abrangencia:"EXTERNA",fundamento:"A_PEDIDO",orgaoDestino:"SEFAZ",unidadeDestino:"SEFAZ — Unidade de destino",vagaDestinoId:"VAG-SEFAZ-ANALISTAAD-00001"}),
 comRemocao({...criar("MOV-00014","REMOCAO","REMOCAO_EXTERNA","AGUARDANDO_VALIDACAO","PES-014","VIN-0005011","VAG-SEPLAG-ANALISTAAD-00014","SEPLAG","CGE","2026-07-12"),vagaDestinoId:"VAG-CGE-ANALISTAAD-00001"},{abrangencia:"EXTERNA",fundamento:"DE_OFICIO",orgaoDestino:"CGE",unidadeDestino:"CGE — Unidade de destino",vagaDestinoId:"VAG-CGE-ANALISTAAD-00001"}),
 comRemocao(criar("MOV-00015","REMOCAO","REMOCAO_PROCESSO_SELETIVO","AUTORIZADA","PES-015","VIN-0005012","VAG-SEPLAG-ANALISTAAD-00015","SEPLAG","SEPLAG","2026-07-13"),{fundamento:"PROCESSO_SELETIVO",editalProcessoSeletivo:"Edital interno nº 08/2026"}),
 comEspecial(criar("MOV-00018","REMOCAO","REMOCAO_PERMUTA","EM_ANALISE","PES-018","VIN-0005015","VAG-SEPLAG-ANALISTAAD-00018","SEPLAG","SEPLAG","2026-07-16"),"REMOCAO_PERMUTA",{segundoVinculoId:"VIN-0005016",segundaOcupacaoId:"OCU-VIN-0005016",segundaVagaId:"VAG-SEPLAG-ANALISTAAD-00019"}),
 criar("MOV-00021","REMOCAO","REMOCAO_ENTRE_UNIDADES","REJEITADA","PES-021","VIN-0005018","VAG-SEPLAG-ANALISTAAD-00021","SEPLAG","SEPLAG","2026-07-19")
];
